### ISSUE TITLE
High Firefox Extension Memory Usage

### ISSUE THREAD

**Issue by OctopusProteins** [bitwarden/clients#10222]
### Steps To Reproduce

1. Keep browser open for days-weeks with extension enabled and normal usage
2. Observe high memory usage as reported by system task manager and Firefox's built-in memory profiler, which reveals this extension as the issue.

### Expected Result

None of my other extensions consume more than a couple hundred MB. 

### Actual Result

After a week or so, Bitwarden was using almost 6 GB of memory. After disabling and reenabling the extension, the usage ballooned to more than 8GB. Usage returns to normal levels after restarting browser.

### Additional Context

There seem to be similar issues reported in other browsers (#2249 #1770).

### Operating System

Windows, MacOS

### Operating System Version

Version 21H2, Sonoma 14.2.1

### Web Browser

Firefox

### Build Version

2024.6.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by HardenedSteel** [comment]
reproducible except restarting the extension didn't cause more memory usage.

**Comment by OctopusProteins** [comment]
The issue is also present in MacOS (Sonoma 14.2.1), where Bitwarden is presently using ~2GB of RAM, about half that of Firefox overall as verified by the built-in memory profiler.

**Comment by sammbw** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by OctopusProteins** [comment]
Here is the output from Firefox's memory profiler. Not sure how useful this is, if there are other reports or logs that might be helpful I am happy to provide.
 This is after a couple days of regular usage, and while not as high as previously reported because of the shorter time between resets, the extension is using ~850MB of RAM out of the total 1.2GB used by all extensions (of which I have many), which seems very excessive. I have verified this extension is Bitwarden -- the report is anonymized.
 
```1,142.58 MB (100.0%) -- explicit
├────991.80 MB (86.80%) -- window-objects
│    ├──853.70 MB (74.72%) -- top(<anonymized-4294967314>, id=40)
│    │  ├──819.64 MB (71.74%) -- active/window(<anonymized-4294967314>)
│    │  │  ├──819.53 MB (71.73%) -- js-realm(<anonymized-17>)
│    │  │  │  ├──816.86 MB (71.49%) -- classes
│    │  │  │  │  ├──273.54 MB (23.94%) -- class(Function)/objects
│    │  │  │  │  │  ├──273.46 MB (23.93%) ── gc-heap
│    │  │  │  │  │  └────0.08 MB (00.01%) ++ malloc-heap
│    │  │  │  │  ├──250.86 MB (21.96%) -- class(Call)/objects
│    │  │  │  │  │  ├──250.84 MB (21.95%) ── gc-heap
│    │  │  │  │  │  └────0.01 MB (00.00%) ── malloc-heap/slots
│    │  │  │  │  ├──184.45 MB (16.14%) -- class(Object)/objects
│    │  │  │  │  │  ├──101.47 MB (08.88%) -- malloc-heap
│    │  │  │  │  │  │  ├──101.44 MB (08.88%) ── slots
│    │  │  │  │  │  │  └────0.03 MB (00.00%) ── elements/normal
│    │  │  │  │  │  └───82.98 MB (07.26%) ── gc-heap
│    │  │  │  │  ├──107.63 MB (09.42%) -- class(Array)/objects
│    │  │  │  │  │  ├──103.00 MB (09.02%) ── gc-heap
│    │  │  │  │  │  └────4.62 MB (00.40%) ++ malloc-heap
│    │  │  │  │  └────0.39 MB (00.03%) ++ (7 tiny)
│    │  │  │  └────2.68 MB (00.23%) ++ (7 tiny)
│    │  │  └────0.11 MB (00.01%) ++ (3 tiny)
│    │  └───34.06 MB (02.98%) -- js-zone(0x208d540c200)
│    │      ├──18.18 MB (01.59%) ++ (17 tiny)
│    │      └──15.88 MB (01.39%) -- strings
│    │         ├──13.41 MB (01.17%) ++ malloc-heap
│    │         └───2.47 MB (00.22%) ++ gc-heap
```

**Comment by dchusovitin** [comment]
Same problem, the extension is using ~1.7G of RAM, after 10 days.

```
│  ├──1,690.91 MB (65.71%) -- top(moz-extension://9fe4e99f/background.html, id=47)
│  │  ├──1,651.05 MB (64.16%) -- active/window(moz-extension://9fe4e99f/background.html)
│  │  │  ├──1,650.96 MB (64.16%) -- js-realm(moz-extension://9fe4e99f/background.html)
│  │  │  │  ├──1,648.55 MB (64.06%) -- classes
│  │  │  │  │  ├────548.92 MB (21.33%) -- class(Function)/objects
│  │  │  │  │  │    ├──548.84 MB (21.33%) ── gc-heap
│  │  │  │  │  │    └────0.08 MB (00.00%) ++ malloc-heap
│  │  │  │  │  ├────504.64 MB (19.61%) -- class(Call)/objects
│  │  │  │  │  │    ├──504.62 MB (19.61%) ── gc-heap
│  │  │  │  │  │    └────0.01 MB (00.00%) ── malloc-heap/slots
│  │  │  │  │  ├────368.00 MB (14.30%) -- class(Object)/objects
│  │  │  │  │  │    ├──202.28 MB (07.86%) -- malloc-heap
│  │  │  │  │  │    │  ├──202.25 MB (07.86%) ── slots
│  │  │  │  │  │    │  └────0.03 MB (00.00%) ── elements/normal
│  │  │  │  │  │    └──165.72 MB (06.44%) ── gc-heap
│  │  │  │  │  ├────226.60 MB (08.81%) -- class(Array)/objects
│  │  │  │  │  │    ├──219.72 MB (08.54%) ── gc-heap
│  │  │  │  │  │    └────6.88 MB (00.27%) ++ malloc-heap
│  │  │  │  │  └──────0.39 MB (00.02%) ++ (7 tiny)
│  │  │  │  └──────2.41 MB (00.09%) ++ (7 tiny)
│  │  │  └──────0.09 MB (00.00%) ++ (3 tiny)
│  │  └─────39.86 MB (01.55%) ++ js-zone(0x7ea9089f2c00)
```

**Comment by marceldev89** [comment]
Just hit 4GB... turning off the extensions made it grow to a huge 10GB before coming down.. This is ridiculous...

**Comment by soulwa** [comment]
noticed firefox taking up a lot of memory and it was similarly bitwarden using ~2.5GB of RAM, out of 3GB total
```
2,756.98 MB (100.0%) -- explicit
├──2,515.67 MB (91.25%) -- window-objects
│  ├──2,474.76 MB (89.76%) -- top(<anonymized-2147483690>, id=1658)
│  │  ├──2,400.23 MB (87.06%) -- active/window(<anonymized-2147483690>)
│  │  │  ├──2,400.13 MB (87.06%) -- js-realm(<anonymized-15>)
│  │  │  │  ├──2,397.45 MB (86.96%) -- classes
│  │  │  │  │  ├────801.12 MB (29.06%) -- class(Function)/objects
│  │  │  │  │  │    ├──801.04 MB (29.05%) ── gc-heap
│  │  │  │  │  │    └────0.08 MB (00.00%) ++ malloc-heap
│  │  │  │  │  ├────736.58 MB (26.72%) -- class(Call)/objects
│  │  │  │  │  │    ├──736.57 MB (26.72%) ── gc-heap
│  │  │  │  │  │    └────0.01 MB (00.00%) ── malloc-heap/slots
│  │  │  │  │  ├────540.15 MB (19.59%) -- class(Object)/objects
│  │  │  │  │  │    ├──296.96 MB (10.77%) -- malloc-heap
│  │  │  │  │  │    │  ├──296.93 MB (10.77%) ── slots
│  │  │  │  │  │    │  └────0.03 MB (00.00%) ── elements/normal
│  │  │  │  │  │    └──243.19 MB (08.82%) ── gc-heap
│  │  │  │  │  ├────318.58 MB (11.56%) -- class(Array)/objects
│  │  │  │  │  │    ├──305.67 MB (11.09%) ── gc-heap
│  │  │  │  │  │    └───12.91 MB (00.47%) ++ malloc-heap
│  │  │  │  │  └──────1.02 MB (00.04%) ++ (8 tiny)
│  │  │  │  └──────2.68 MB (00.10%) ++ (7 tiny)
│  │  │  └──────0.10 MB (00.00%) ++ (3 tiny)
│  │  └─────74.53 MB (02.70%) -- js-zone(0x12a7b2000)
│  │        ├──36.68 MB (01.33%) -- strings
│  │        │  ├──33.74 MB (01.22%) -- malloc-heap
│  │        │  │  ├──30.84 MB (01.12%) ── two-byte
│  │        │  │  └───2.90 MB (00.11%) ── latin1
│  │        │  └───2.94 MB (00.11%) ++ gc-heap
│  │        ├──31.22 MB (01.13%) ── gc-heap-arena-admin
│  │        └───6.64 MB (00.24%) ++ (16 tiny)
│  └─────40.91 MB (01.48%) ++ (12 tiny)
```

Bitwarden Version: 2024.7.1
Browser: Firefox 128.0.3
OS: Sonoma 14.5
on an Intel 2019 Mac with 32GB RAM

**Comment by crishnakh** [comment]
Any solution on this?

**Comment by tyteen4a03** [comment]
+1

**Comment by yannleretaille** [comment]
2.64 GB after 10.7 days runtime (Firefox 130.0, Arch Linux 6.10.10, BW 2024.9.1):
```
│  ├──2,639,573,744 B (86.56%) -- top(moz-extension://<BW-EXT-ID>/background.html, id=38)
│  │  ├──2,561,324,968 B (84.00%) -- active/window(moz-extension://<BW-EXT-ID>/background.html)
│  │  │  ├──2,561,209,144 B (83.99%) -- js-realm(moz-extension://<BW-EXT-ID>/background.html)
│  │  │  │  ├──2,558,273,416 B (83.90%) -- classes
│  │  │  │  │  ├────853,798,448 B (28.00%) -- class(Function)/objects
│  │  │  │  │  │    ├──853,707,680 B (28.00%) ── gc-heap
│  │  │  │  │  │    └───────90,768 B (00.00%) -- malloc-heap
│  │  │  │  │  │            ├──82,576 B (00.00%) ── slots
│  │  │  │  │  │            └───8,192 B (00.00%) ── elements/normal
│  │  │  │  │  ├────784,917,216 B (25.74%) -- class(Call)/objects
│  │  │  │  │  │    ├──784,902,880 B (25.74%) ── gc-heap
│  │  │  │  │  │    └───────14,336 B (00.00%) ── malloc-heap/slots
│  │  │  │  │  ├────576,653,304 B (18.91%) -- class(Object)/objects
│  │  │  │  │  │    ├──316,556,448 B (10.38%) -- malloc-heap
│  │  │  │  │  │    │  ├──316,498,624 B (10.38%) ── slots
│  │  │  │  │  │    │  └───────57,824 B (00.00%) ── elements/normal
│  │  │  │  │  │    └──260,096,856 B (08.53%) ── gc-heap
│  │  │  │  │  ├────341,665,120 B (11.20%) -- class(Array)/objects
│  │  │  │  │  │    ├──328,028,384 B (10.76%) ── gc-heap
│  │  │  │  │  │    └───13,636,736 B (00.45%) -- malloc-heap
│  │  │  │  │  │        ├──13,598,928 B (00.45%) ── elements/normal
│  │  │  │  │  │        └──────37,808 B (00.00%) ── slots
│  │  │  │  │  ├────────687,680 B (00.02%) ── class(Proxy)/objects/gc-heap
│  │  │  │  │  ├────────216,392 B (00.01%) ── class(Date)/objects/gc-heap
│  │  │  │  │  ├────────100,400 B (00.00%) -- class(Map)/objects
│  │  │  │  │  │        ├───82,928 B (00.00%) ── malloc-heap/misc
│  │  │  │  │  │        └───17,472 B (00.00%) ── gc-heap
│  │  │  │  │  ├─────────52,928 B (00.00%) -- class(Set)/objects
│  │  │  │  │  │         ├──51,136 B (00.00%) ── malloc-heap/misc
│  │  │  │  │  │         └───1,792 B (00.00%) ── gc-heap
│  │  │  │  │  ├─────────44,592 B (00.00%) -- class(<non-notable classes>)/objects
│  │  │  │  │  │         ├──32,224 B (00.00%) -- malloc-heap
│  │  │  │  │  │         │  ├──20,736 B (00.00%) ── slots
│  │  │  │  │  │         │  ├───8,640 B (00.00%) ── elements/normal
│  │  │  │  │  │         │  ├───2,224 B (00.00%) ── global-data
│  │  │  │  │  │         │  └─────624 B (00.00%) ── misc
│  │  │  │  │  │         └──12,368 B (00.00%) ── gc-heap
│  │  │  │  │  ├─────────35,136 B (00.00%) -- class(LexicalEnvironment)/objects
│  │  │  │  │  │         ├──24,448 B (00.00%) ── gc-heap
│  │  │  │  │  │         └──10,688 B (00.00%) ── malloc-heap/slots
│  │  │  │  │  ├─────────21,824 B (00.00%) ── class(PromiseReactionRecord)/objects/gc-heap
│  │  │  │  │  ├─────────21,736 B (00.00%) ── class(BoundFunctionObject)/objects/gc-heap
│  │  │  │  │  ├─────────20,552 B (00.00%) ── class(RegExp)/objects/gc-heap
│  │  │  │  │  ├─────────20,048 B (00.00%) ── class(Promise)/objects/gc-heap
│  │  │  │  │  └─────────18,040 B (00.00%) ── class(Generator)/objects/gc-heap
│  │  │  │  ├──────2,112,160 B (00.07%) -- scripts
│  │  │  │  │      ├──1,094,960 B (00.04%) ── malloc-heap/data
│  │  │  │  │      └──1,017,200 B (00.03%) ── gc-heap
│  │  │  │  ├────────492,336 B (00.02%) ── jit-scripts
│  │  │  │  ├────────151,168 B (00.00%) ── ion-data
│  │  │  │  ├────────129,264 B (00.00%) ── baseline/data
│  │  │  │  ├─────────32,280 B (00.00%) ── alloc-sites
│  │  │  │  ├─────────16,768 B (00.00%) ── saved-stacks-set
│  │  │  │  └──────────1,752 B (00.00%) ── sundries/malloc-heap
│  │  │  ├─────────60,976 B (00.00%) -- dom
│  │  │  │         ├──51,728 B (00.00%) ── performance/resource-entries
│  │  │  │         ├───5,200 B (00.00%) ── other
│  │  │  │         └───4,048 B (00.00%) ── element-nodes
│  │  │  ├─────────54,368 B (00.00%) -- layout
│  │  │  │         ├──20,096 B (00.00%) ── style-structs/sundries
│  │  │  │         ├──14,152 B (00.00%) ── pres-shell
│  │  │  │         ├──12,320 B (00.00%) -- style-sets
│  │  │  │         │  ├───8,960 B (00.00%) ── other
│  │  │  │         │  └───3,360 B (00.00%) ── stylist/rule-tree
│  │  │  │         ├───3,584 B (00.00%) -- computed-values
│  │  │  │         │   ├──2,816 B (00.00%) ── dom
│  │  │  │         │   └────768 B (00.00%) ── non-dom
│  │  │  │         ├───2,744 B (00.00%) ── pres-arena/sundries
│  │  │  │         ├─────768 B (00.00%) ── pres-contexts
│  │  │  │         ├─────352 B (00.00%) ── element-data-objects
│  │  │  │         ├─────192 B (00.00%) ── frame-properties
│  │  │  │         └─────160 B (00.00%) ── style-sheets
│  │  │  └────────────480 B (00.00%) ── property-tables
│  │  └─────78,248,776 B (02.57%) -- js-zone(0x7eda76a5a800)
│  │        ├──36,838,808 B (01.21%) ++ strings
│  │        ├──33,310,952 B (01.09%) ── gc-heap-arena-admin
│  │        ├───3,102,464 B (00.10%) -- property-maps
│  │        │   ├──2,147,008 B (00.07%) -- gc-heap
│  │        │   │  ├──1,571,840 B (00.05%) ── dict
│  │        │   │  ├────292,808 B (00.01%) ── normal
│  │        │   │  └────282,360 B (00.01%) ── compact
│  │        │   └────955,456 B (00.03%) -- malloc-heap
│  │        │        ├──919,616 B (00.03%) ── tables
│  │        │        └───35,840 B (00.00%) ── children
│  │        ├───1,897,888 B (00.06%) -- code
│  │        │   ├────766,960 B (00.03%) ── baseline
│  │        │   ├────717,456 B (00.02%) ── unused
│  │        │   ├────403,968 B (00.01%) ── ion
│  │        │   └──────9,504 B (00.00%) ── other
│  │        ├───1,362,528 B (00.04%) -- scopes
│  │        │   ├────797,792 B (00.03%) ── malloc-heap
│  │        │   └────564,736 B (00.02%) ── gc-heap
│  │        ├─────524,288 B (00.02%) ── cacheir-stubs
│  │        ├─────369,024 B (00.01%) ── compartments/cross-compartment-wrapper-tables
│  │        ├─────262,240 B (00.01%) ── shape-tables
│  │        ├─────237,432 B (00.01%) -- shapes
│  │        │     ├──236,104 B (00.01%) -- gc-heap
│  │        │     │  ├──200,640 B (00.01%) ── shared
│  │        │     │  ├───34,440 B (00.00%) ── base
│  │        │     │  └────1,024 B (00.00%) ── dict
│  │        │     └────1,328 B (00.00%) ── malloc-heap/shape-cache
│  │        ├──────95,232 B (00.00%) -- regexp-shareds
│  │        │      ├──74,752 B (00.00%) ── malloc-heap
│  │        │      └──20,480 B (00.00%) ── gc-heap
│  │        ├──────79,040 B (00.00%) ── unused-gc-things
│  │        ├──────53,360 B (00.00%) ── jit-codes-gc-heap
│  │        ├──────31,984 B (00.00%) ── bigints/gc-heap
│  │        ├──────24,576 B (00.00%) ── propmap-tables
│  │        ├──────24,000 B (00.00%) ── getter-setters-gc-heap
│  │        ├──────13,024 B (00.00%) ── jit-zone
│  │        ├──────12,288 B (00.00%) ── unique-id-map
│  │        └───────9,648 B (00.00%) -- sundries
│  │                ├──6,992 B (00.00%) ── malloc-heap
│  │                └──2,656 B (00.00%) ── other-heap
```

**Comment by erikdemarco** [comment]
this issue already exist since 2021 and still not solved? Just asking, is it possible the developer ship different version of software than in this repo and put something in this software to freely use our computer resources for something fishy? 🤔

**Comment by httpsWina** [comment]
any fix for this? i've had to resort to using the desktop client which is not comfortable at all.

**Comment by crishnakh** [comment]
I need to kill it every some hours.

**Comment by jpiesing** [comment]
Same problem here.

![image](https://github.com/user-attachments/assets/2bfb744d-ece7-445c-8585-300253b2f810)

and

![image](https://github.com/user-attachments/assets/e57ab3b1-35c0-4434-99d0-55905868fba7)

**Comment by crishnakh** [comment]
This still is a problem in macos. ¿Any solution? The extension eats 1gb or more of RAM over time.

**Comment by vale981** [comment]
Normally, my stance would be to either wait patiently or try to fix this myself. But since I'm a paying customer, I'll just jump ship and use something different. I suppose that Firefox users are a negligible fraction of the total user base and this issue doesn't have much priority.

**Comment by trmartin4** [comment]
Hello,

We believe we have addressed this with the upcoming `2024.12.0` release of the Firefox extension, which is currently in app store review.  We will be keeping this open until the release is available and we can verify that the issue reported here is the same one that we were able to reproduce internally and address with this update.

**Comment by trmartin4** [comment]
As this has been addressed with the `2024.12.0` release that is now available, we will be closing this issue.

If you continue to encounter memory issues, please re-open or create a new issue.

Thank you!

**Comment by vale981** [comment]
I'm glad to be proven wrong. Thanks!

**Comment by crishnakh** [comment]
At last!!

**Comment by bipin-lekhak** [comment]
Still having issues with this. I seem to be on version `2024.12.3`. Running on firefox `34.0b10 (aarch64)` on a M3 Pro. The memory logs read:
```
1,679.27 MB (100.0%) -- explicit
├──1,256.57 MB (74.83%) -- window-objects
│  ├──1,078.00 MB (64.19%) -- top(moz-extension://f41d1f2c-7101-4c3b-8dc0-0ba256159c25/background.html, id=9778)
│  │  ├──1,053.57 MB (62.74%) -- active/window(moz-extension://f41d1f2c-7101-4c3b-8dc0-0ba256159c25/background.html)
│  │  │  ├──1,053.46 MB (62.73%) -- js-realm(moz-extension://f41d1f2c-7101-4c3b-8dc0-0ba256159c25/background.html)
│  │  │  │  ├──1,051.13 MB (62.59%) -- classes
│  │  │  │  │  ├────350.28 MB (20.86%) -- class(Function)/objects
│  │  │  │  │  │    ├──350.20 MB (20.85%) ── gc-heap
│  │  │  │  │  │    └────0.08 MB (00.00%) ++ malloc-heap
│  │  │  │  │  ├────321.60 MB (19.15%) -- class(Call)/objects
│  │  │  │  │  │    ├──321.59 MB (19.15%) ── gc-heap
│  │  │  │  │  │    └────0.01 MB (00.00%) ── malloc-heap/slots
│  │  │  │  │  ├────234.75 MB (13.98%) -- class(Object)/objects
│  │  │  │  │  │    ├──129.08 MB (07.69%) -- malloc-heap
│  │  │  │  │  │    │  ├──129.03 MB (07.68%) ── slots
│  │  │  │  │  │    │  └────0.05 MB (00.00%) ── elements/normal
│  │  │  │  │  │    └──105.67 MB (06.29%) ── gc-heap
│  │  │  │  │  ├────136.06 MB (08.10%) -- class(Array)/objects
│  │  │  │  │  │    ├──132.18 MB (07.87%) ── gc-heap
│  │  │  │  │  │    └────3.88 MB (00.23%) ++ malloc-heap
│  │  │  │  │  └──────8.43 MB (00.50%) ++ (8 tiny)
│  │  │  │  └──────2.33 MB (00.14%) ++ (5 tiny)
│  │  │  └──────0.11 MB (00.01%) ++ (3 tiny)
```

**Comment by Saruspete** [comment]
Hello,

Same thing here, using 2024.12.3 under Linux:

```
Explicit Allocations

1,231,774,504 B (100.0%) -- explicit
├──1,110,818,312 B (90.18%) -- window-objects
│  ├──1,062,078,536 B (86.22%) -- top(moz-extension://9b05a0a6-04e9-4ea9-96e1-0ca93fab6fb2/background.html, id=43)
│  │  ├──1,017,571,672 B (82.61%) -- active/window(moz-extension://9b05a0a6-04e9-4ea9-96e1-0ca93fab6fb2/background.html)
│  │  │  ├──1,017,470,136 B (82.60%) -- js-realm(moz-extension://9b05a0a6-04e9-4ea9-96e1-0ca93fab6fb2/background.html)
│  │  │  │  ├──1,014,656,392 B (82.37%) -- classes
│  │  │  │  │  ├────338,573,376 B (27.49%) ++ class(Function)/objects
│  │  │  │  │  ├────310,628,384 B (25.22%) ++ class(Call)/objects
│  │  │  │  │  ├────227,806,432 B (18.49%) ++ class(Object)/objects
│  │  │  │  │  ├────132,063,872 B (10.72%) ++ class(Array)/objects
│  │  │  │  │  ├──────3,805,520 B (00.31%) ++ class(WebAssembly.Instance)/objects
│  │  │  │  │  ├──────1,445,592 B (00.12%) ++ class(ArrayBuffer)/objects
│  │  │  │  │  ├────────148,008 B (00.01%) ── class(Proxy)/objects/gc-heap
│  │  │  │  │  ├─────────64,728 B (00.01%) ++ class(<non-notable classes>)/objects
│  │  │  │  │  ├─────────43,856 B (00.00%) ++ class(Map)/objects
│  │  │  │  │  ├─────────29,456 B (00.00%) ++ class(LexicalEnvironment)/objects
│  │  │  │  │  ├─────────24,600 B (00.00%) ++ class(Set)/objects
│  │  │  │  │  └─────────22,568 B (00.00%) ── class(RegExp)/objects/gc-heap
│  │  │  │  ├──────2,257,168 B (00.18%) ++ scripts
│  │  │  │  ├────────371,952 B (00.03%) ── jit-scripts
│  │  │  │  ├────────100,880 B (00.01%) ── baseline/data
│  │  │  │  ├─────────39,552 B (00.00%) ── ion-data
│  │  │  │  ├─────────24,848 B (00.00%) ── alloc-sites
│  │  │  │  ├─────────16,768 B (00.00%) ── saved-stacks-set
│  │  │  │  └──────────2,576 B (00.00%) ── sundries/malloc-heap
│  │  │  ├─────────54,368 B (00.00%) ++ layout
│  │  │  ├─────────46,688 B (00.00%) ++ dom
│  │  │  └────────────480 B (00.00%) ── property-tables
│  │  └─────44,506,864 B (03.61%) ++ js-zone(0x7ff684aa1a00)
```

**Comment by BDtetra** [comment]
Same issue here as well, on client version 2024.12.4 on Firefox.
This is with approximately 2 days open.
![Image](https://github.com/user-attachments/assets/83515356-40c6-4cc1-821e-eeb680e227ad)

**Comment by crishnakh** [comment]
Yep, still happening.

**Comment by jpiesing** [comment]
Still happening here too. 

![Image](https://github.com/user-attachments/assets/5fff72ba-8f4a-4090-9c58-2598448eca5d)

**Comment by lrod55** [comment]
Same here

**Comment by anttitelio** [comment]
Here the extension took roughly 7 GB of memory and raised the CPU usage from 7 % to 90-100 %.

**Comment by mamatsa** [comment]
Same issue on fedora 43, zen browser. Disabling and re-enabling add-on or restarting the browser fixes the problem but its happening every few days. RAM consumption from bitwarden goes to 4-6 GB and loads the CPU as well

**Comment by piperswe** [comment]
Still seeing the same issue on extension 2025.6.1 on Orion, using the Firefox extension.

**Comment by MulverineX** [comment]
Not nearly as high as some of the reports in here but:

<img width="1243" height="778" alt="Image" src="https://github.com/user-attachments/assets/7c53f5f5-19bc-4b86-934f-14481755c26f" />

still pretty high. @trmartin4 an official update on this would be appreciated

**Comment by krax1337** [comment]
Same here! It's really annoying, computer becomes very laggy. High memory pressure. Dear @trmartin4 could you reopen the issue. I hope we can provide more feedback.

<img width="693" height="189" alt="Image" src="https://github.com/user-attachments/assets/3cc1f11f-a1c5-442b-a6b3-080851d43c26" />
<img width="1031" height="434" alt="Image" src="https://github.com/user-attachments/assets/ca37b345-f1af-499f-a6d4-cf79666b9f27" />

**Comment by Artcas2** [comment]
same issue with latest version on Firefox

<img width="1086" height="483" alt="Image" src="https://github.com/user-attachments/assets/b0e93b38-9972-43a3-a292-652ea5b8d263" />

**Comment by Saruspete** [comment]
@trmartin4 can you please reopen this issue ? it seems it's still not resolved, as we're still 12 to have the issue since start of 2025.
Or should we add our reports to issue created by @jpiesing (14143) ?

**Comment by Avrution** [comment]
Still no resolution in 2026.  I'm sitting here at over 1GB of usage - looks exactly like Artcas2 above

**Comment by stateless** [comment]
I found if I set Bitwarden under Account Security to "Lock" after a period of time that memory seems to get freed (gc by firefox?) as well. At least I'm not having to restart the browser as often to clear memory.

**Comment by MulverineX** [comment]
I just disable the extension and re-enable it

**Comment by dorkulon** [comment]
The easiest way I've found to reclaim the memory without restarting the entire browser is do shift-ESC/about:processes, find the "Extensions" process, and click the X there; it'll kill and restart Bitwarden without having to restart the browser or do the disable/reenable dance. ("lock now" looks like it'll deallocate the memory, but won't actually free it back to the OS; the extensions process needs to be killed entirely for that.)

**Comment by BDtetra** [comment]
while many temporary solutions and workarounds exist, I find it kind of unacceptable for this to not be fixed for over an year at this point on what is essentially a paid product.
@trmartin4 can you reopen this case please.

**Comment by Snuupy** [comment]
<img width="1676" height="62" alt="Image" src="https://github.com/user-attachments/assets/a229c30e-d6f0-4368-bd88-daf3682803aa" />

lol 8GB used

Explicit Allocations

```
1,916.79 MB (100.0%) -- explicit
├──1,590.29 MB (82.97%) -- window-objects
│  ├────972.57 MB (50.74%) ++ top(moz-extension://58cffb35-63f2-4b08-bcd6-f61d319c6008/background.html, id=127)
```

**Comment by yannleretaille** [comment]
As this issue is closed I suggest reporting here instead: #14143

**Comment by Snuupy** [comment]
done, thanks
