### ISSUE TITLE
[Safari extension] Vault timeout doesn't work

### ISSUE THREAD

**Issue by FournierNico** [bitwarden/clients#10238]
### Steps To Reproduce

1. In Settings / Account security, configure the Vault extension timeout to **lock** after **30 minutes**
2. Wait 30 minutes

### Expected Result

The Vault is locked and I need to enter my password again

### Actual Result

Nothing happen. The vault is still unlocked, regardless of the time I wait

### Operating System

macOS

### Web Browser

Safari

### Browser Version

Version 17.5 (19618.2.12.11.6)

### Build Version

Version: 2024.6.1  Server version: 2024.6.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by Thumpxr** [comment]
I have the same issue.

macOS, Safari (17.5 (19618.2.12.11.6))
Version: 2024.6.1
Server-Version: 2024.7.2

**Comment by insurw** [comment]
> Hi there,
> 
> Thank you for your report!
> 
> I was able to reproduce this issue, and I have flagged this to our engineering team.
> 
> If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.
> 
> Thanks once again!

Same issue with Win11 Chrome (all updated). Isn't this the 2nd time same bug appears in ~2 years?

You guys aren't making it easy to pay to just support you. I could just use the free tier. I'll probably switch pw manager.
For over a month email wasn't saved. It was just fixed, but of course you pushed another update to break vault timeout.
Why can't you devs _test basic functions_ before pushing updates?

**Comment by nicofrenchy** [comment]
I don't know if you changed something in the past weeks, but I don't have the issue anymore. The only thing I did is clear my cache / reboot my Mac.

**Comment by SergeantConfused** [comment]
Hello everyone,

Thank you for following up on this, @nicofrenchy. @Thumpxr, are you still able to reproduce this behaviour?


Thank you in advance,

**Comment by Lainemac** [comment]
I still have this issue. Tried setting my vault to never timeout, tried setting the default action to "lock" even tried setting up a pin. Nothing works. Only happening in safari.

**Comment by zeweichen** [comment]
I just experienced this issue between yesterday and today: have session timeout at 15min; unlocked the vault in the afternoon; closed the laptop around 5pm; opened the laptop 9am today; the vault is still unlocked.  

That's quite unbelievable -- both how long it had disregarded the session timeout setting and how long this issue remained unresolved.

The environment where I observed this behavior:

MacOS 26.5.2 (on a 4 year old MacBook Pro)
Safari browser: Version 26.5.2 (21624.2.5.11.8)
