### ISSUE TITLE
Firefox addon causes freezing some web applications after last update to 2024.9.1

### ISSUE THREAD

**Issue by kamil-novak** [bitwarden/clients#11234]
### Steps To Reproduce

1. Go to https://mapy.mesto-most.cz/app/uzemni-plany/
2. Click on first button (four squares icon) on top right toolbar
3. Tool doesn't load expected content after this action and there is TypeError: wa.parentNode is null in the browser javascript console

Similar behavior is recognized in multiple places of the application.

### Expected Result

The tool loads items of the basemap gallery.

### Actual Result

The tool freezes

### Screenshots or Videos

![Image 004](https://github.com/user-attachments/assets/c8b9cc86-5d07-4c15-be45-e1297de1de23)

### Operating System

Windows

### Web Browser

Firefox

### Build Version

2024.9.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by t7yang** [comment]
yeah, sometimes I see Firefox warms Bitwarden taking too much time to run when I switching tabs on YouTube.

**Comment by Krychaz** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by t7yang** [comment]
@Krychaz
OK, I'll try if I could use the profiler to record something next time when YouTube running slow

**Comment by clavicon** [comment]
I am having the exact same issue, I was about to put in a new issue but I thought I should add on here. 

ISSUE: 
Certain components of our arcgis-based web applications fail to load when Bitwarden extension is enabled. By enabled, I mean even if it is freshly installed with no previous login history or settings on that browser/device. The issue symptoms are resolved by either loading the pages in an InCognito/InPrivate window with Bitwarden disabled, or by uninstalling Bitwarden. I can reproduce this across Edge on Windows 10, Edge on Windows 11, Firefox on Windows 10, Firefox on Windows 11, Edge on MacOS, Firefox on MacOS. Different machines, different networks. I am also able to reproduce the exactly behavior of the OP of this issue. 

TEST CASE TO REPRODUCE:
Our [main public web map](https://gis.fuquay-varina.org/portal/apps/webappviewer/index.html?id=ead47b770049477b949fc3efdf1f43f9) can be used to reproduce this issue similar to OP's case: the main map window will load, but the 'tools' windows will fail to load. Maybe one or three out of 10 will load correctly, but mostly not. Disabling or uninstalling Bitwarden and refreshing the page immediately resolves the issues. 

![image](https://github.com/user-attachments/assets/f77a4af8-8555-49e6-8a19-f41c4d9fef66)

I wonder if this is related to this issue where Bitwarden is injecting some code on page loads that may disrupt the load order of other things? This is definitely not my wheelhouse but it had a flavor that felt similar. 
https://github.com/bitwarden/clients/issues/6767

This is more violently affecting another application we use called Cityworks that uses the same underlying arcgis based javascript api for map functionality. In that case, the map view will load inconsistently and users are unable to perform normal tasks for work order management. We are asking them to use InPrivate windows as workaround in the meantime so that Bitwarden is disabled.

**Comment by cagonzalezcs** [comment]
Just chiming in, I was able to replicate this behavior as well as a potential fix for the problem on the web app listed here. 

Problems like this appear due to the passkeys feature that the extension has. If you'd like to resolve this in the immediate, you can go to `Settings > Notifications > Ask to save and use passkeys` and check off the box to disable the feature.

A more permanent fix is in being discussed internally.

**Comment by clavicon** [comment]
> Just chiming in, I was able to replicate this behavior as well as a potential fix for the problem on the web app listed here.
> 
> Problems like this appear due to the passkeys feature that the extension has. If you'd like to resolve this in the immediate, you can go to `Settings > Notifications > Ask to save and use passkeys` and check off the box to disable the feature.
> 
> A more permanent fix is in being discussed internally.

@cagonzalezcs Many thanks, that specific options does appear to be the culprit and disabling it does seem to prevent these issues from occurring on my end in my tests in Edge and Firefox. I appreciate the response. If I subscribe and pay attention here, do you think support will communicate that potential future fix in this thread so I can stay on top of the permanent solution in the future?

**Comment by bscmattanderson** [comment]
Same issue, I closed my issue. Turning off passkey did fix the issue:

Steps To Reproduce
Install bitwarden extension on Microsoft Edge (Version 2024.9.1) - You do not even need to sign in
Go to https://gis.bigstonecounty.gov/link/wab/
Click on top right 4 squares to change to a new base map
Page does not load new base map menu.
Expected Result
New basemap should be shown. If you remove the extension it works, if you view in private mode without extension it works. Version of browser does not matter, clean browser does not matter.

Actual Result
No item loads, errors in dev console.

widget [widgets/OverviewMap/Widget] created.
WidgetManager.js?wab_dv=2.20:121 widget [widgets/Search/Widget] created.
WidgetManager.js?wab_dv=2.20:121 widget [widgets/AttributeTable/Widget] created.
AbsolutePositionLayoutManager.js?wab_dv=2.20:110 Load widgetOnScreen: 502.97802734375 ms
init.js:116 TypeError: Cannot read properties of null (reading 'insertBefore')
at d.injectUrl (init.js:36:479)
at global.avoidRequireCache.require.injectUrl (env.js:324:7)
at Sa (init.js:33:338)
at a (init.js:10:436)
at init.js:20:121
at Na (init.js:29:294)
at ua (init.js:20:107)
at sa (init.js:20:467)
at G (init.js:21:132)
at x.loadPBFReader (init.js:2801:160) "TypeError: Cannot read properties of null (reading 'insertBefore')\n at d.injectUrl ([https://js.arcgis.com/3.36/init.js:36:479)\n](https://js.arcgis.com/3.36/init.js:36:479)%5Cn) at global.avoidRequireCache.require.injectUrl ([https://gis.bigstonecounty.gov/link/wab/env.js:324:7)\n](https://gis.bigstonecounty.gov/link/wab/env.js:324:7)%5Cn) at Sa ([https://js.arcgis.com/3.36/init.js:33:338)\n](https://js.arcgis.com/3.36/init.js:33:338)%5Cn) at a ([https://js.arcgis.com/3.36/init.js:10:436)\n](https://js.arcgis.com/3.36/init.js:10:436)%5Cn) at [https://js.arcgis.com/3.36/init.js:20:121\n](https://js.arcgis.com/3.36/init.js:20:121%5Cn) at Na ([https://js.arcgis.com/3.36/init.js:29:294)\n](https://js.arcgis.com/3.36/init.js:29:294)%5Cn) at ua ([https://js.arcgis.com/3.36/init.js:20:107)\n](https://js.arcgis.com/3.36/init.js:20:107)%5Cn) at sa ([https://js.arcgis.com/3.36/init.js:20:467)\n](https://js.arcgis.com/3.36/init.js:20:467)%5Cn) at G ([https://js.arcgis.com/3.36/init.js:21:132)\n](https://js.arcgis.com/3.36/init.js:21:132)%5Cn) at x.loadPBFReader (https://js.arcgis.com/3.36/init.js:2801:160)"
r @ init.js:116
init.js:29 Uncaught TypeError: Cannot read properties of null (reading 'insertBefore')
at d.injectUrl (init.js:36:479)
at global.avoidRequireCache.require.injectUrl (env.js:324:7)
at Sa (init.js:33:338)
at a (init.js:10:436)
at init.js:20:121
at Na (init.js:29:294)
at ua (init.js:20:107)
at sa (init.js:20:467)
at G (init.js:21:132)
at Object._loadPanelClass (PanelManager.js?wab_dv=2.20:623:7)
init.js:29 Uncaught TypeError: Cannot read properties of null (reading 'insertBefore')
at d.injectUrl (init.js:36:479)
at global.avoidRequireCache.require.injectUrl (env.js:324:7)
at Sa (init.js:33:338)
at a (init.js:10:436)
at init.js:20:121
at Na (init.js:29:294)
at ua (init.js:20:107)
at sa (init.js:20:467)
at G (init.js:21:132)
at d (init.js:78:10)

Screenshots or Videos
image

Additional Context
No response

Operating System
Windows

Operating System Version
Windows 11 23H2

Web Browser
Microsoft Edge

Browser Version
129.0.2792.52

Build Version
2024.9.1

Issue Tracking Info
 I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cagonzalezcs** [comment]
Thank you for the detailed information about the issue.

We've implemented [a fix for this problem](https://github.com/bitwarden/clients/pull/11304) that is going into code review. These changes should appear in an upcoming version of the browser extension.

**Comment by isaiahaguilera** [comment]
I would like to add that this exact same issue does appear to affect the Microsoft Edge version of the extension as well.

**Comment by isaiahaguilera** [comment]
> Thank you for the detailed information about the issue.
> 
> We've implemented [a fix for this problem](https://github.com/bitwarden/clients/pull/11304) that is going into code review. These changes should appear in an upcoming version of the browser extension.

Will this fix change behavior on all extensions. I know Firefox is the mentioned browser but my organization is using Edge and is also affected.

**Comment by cagonzalezcs** [comment]
@isaiahaguilera 

Yes, it will. Edge, Firefox, Safari, and any non-mv3 browsers share the same implementation for this. The fix isn't really dependent on a browser-specific concern outside of the manifest version.

**Comment by daveolson53** [comment]
This issue is back again.  I'm on ubuntu 22.04 with firefox 151 (ubuntu package firefox 151.0.4+build1-0ubuntu0.22.04.1~mt), and bitwarden 2026.5.1 extension.

I see the same js error message and failure of the page to open with the arcgis site to look at historic USGS topo maps (https://livingatlas.arcgis.com/topomapexplorer).  Same symptoms, and turning off asking for passkeys in the bitwarden extension "fixed" the problem.

I don't have permissions to reopen the issue.  If there's no response in a bit, then I'll open a new issue and link to this one.

- [ ]
