### ISSUE TITLE
Locked for no reason

### ISSUE THREAD

**Issue by csicky** [bitwarden/clients#11386]
### Steps To Reproduce

I have it set up so that lock timeout is never. I find it that is unexpectedly locked. 

### Expected Result

To not be locked EVER!

### Actual Result

It is locked.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/305fc123-32ce-41b7-bfae-b0376f37fd21)

### Additional Context

My settings should be respected even if some developer thinks they are not safe.

### Operating System

Windows

### Operating System Version

10

### Web Browser

Firefox

### Browser Version

131.0

### Build Version

Version: 2024.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Please keep in mind that by default, if you close your browser window, your browser extension will require you to login with your master password regardless of your selected vault timeout action.

If you'd like, you can allow the browser extension to unlock with a PIN after closing the browser window by unchecking the Lock with master password on browser restart option that is presented when you setup your PIN. More info here: https://bitwarden.com/help/unlock-with-pin/

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by selimsum** [comment]
Lately I've been having this issue on Firefox as well and I was about to file an issue.

> Please keep in mind that by default, if you close your browser window, your browser extension will require you to login with your master password regardless of your selected vault timeout action.

Is this a recent change? This was not the case until recently, probably version 2024.8.

**Comment by BBGhub** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by selimsum** [comment]
FYI: I've been using [this build](https://github.com/bitwarden/clients/actions/runs/10928574843) for the past few days and I couldn't reproduce the issue on that build. So there's a chance that it might have already been fixed in version 2024.10, which should have an official release for Firefox very soon.

**Comment by MichalSznajder** [comment]
I am on Firefox/Mac. This issue started to pop-up recently (like 3-4 months). I sit down in the morning and Bitwarden Vault is locked. Tab are there, there was no browser restart. 

I am on 2024.9.1 right now and I feel it is also happening. I am looking forward for 2024.10.

**Comment by trmartin4** [comment]
@csicky thank you for following up.  I've re-opened this issue internally as well and assigned to the team responsible for this area of the code.

**Comment by ywwry66** [comment]
I am also having this issue on Safari 18.1 macOS Sequoia 15.1. Bitwarden browser extension version is 2024.10.1.

**Comment by markywarky** [comment]
I have also had this issue for a couple of months, viz. browser plugin locking before it should.
Tried various timeout settings, particularly 4 hours and On browser restart. Locking happens seemingly intermittently, sometimes after just minutes.
Have reinstalled Bitwarden, deleted all browser cookies: problem persists.
Safari 18.1.1, Sequoia 15.1.1, Plugin 2024.11.2, Server 2024.11.0.

**Comment by SergeantConfused** [comment]
Hello everyone,

I'd like to confirm a small detail, what you're all reporting is that the browser extension is following the (Vault Timeout Action), be it (Log out) or (Lock), unexpectedly earlier than when it's supposed to if it were to accurately follow the (Vault Timeout), correct? Meaning, if the (Vault Timeout Action) is set to (Log out), the extension logs out, and if it's set to (Lock), the extension locks; no one here is encountering a situation where the extension is locking instead of logging out or vice versa, right?

Also, could you please let me know if changing Safari's User Agent, under the Develop menu, affects this behaviour in any way?

Thank you in advance,

**Comment by ywwry66** [comment]
> I'd like to confirm a small detail, what you're all reporting is that the browser extension is following the (Vault Timeout Action), be it (Log out) or (Lock), unexpectedly earlier than when it's supposed to if it were to accurately follow the (Vault Timeout), correct? Meaning, if the (Vault Timeout Action) is set to (Log out), the extension logs out, and if it's set to (Lock), the extension locks; no one here is encountering a situation where the extension is locking instead of logging out or vice versa, right?

That is correct. I also haven't encounter this issue since Sequoia 15.2, Safari 18.2, Browser extension 2024.12.0.

**Comment by MineGene** [comment]
Also experiencing this, support ticket: #574006.

**Comment by jlf0dev** [comment]
Hi everyone,

Thank you for the reports, I am closing this as we have not been able to reproduce this behavior. Please let me know if you're still experiencing this, if so I'd like to discuss any details we might have missed in our reproduction steps.
