### ISSUE TITLE
Toggling password visibility fails to display full password

### ISSUE THREAD

**Issue by BenjaminMichaelis** [bitwarden/clients#12641]
### Steps To Reproduce

Have a long password stored and toggle visibility button, notice password is not entirely visible like it was in 2024.11.2.

### Expected Result

Entire password to be visible like it was in 2024.11.2. and also to match the behavior that occurs on other clients like mobile where entire password is visible.

From 2024.11.2 extension:
![image](https://github.com/user-attachments/assets/28e4d569-9393-42e0-9e3a-326c659c2ce9)

### Actual Result

Password is not entirely visible in 2024.12.4

![image](https://github.com/user-attachments/assets/1271c1be-f239-41bf-859e-56589bd21e68)

### Screenshots or Videos

ios:
![iosShowPassword](https://github.com/user-attachments/assets/938ef318-d41a-4329-9fcc-f8f8137d465b)

browser extension:
![browserShowPassword](https://github.com/user-attachments/assets/73aa5c24-86ea-4d19-952e-c69f62071b1b)

### Additional Context

Brought over from Community Forum after pointed out that this could be categorized as a bug: 
[https://community.bitwarden.com/t/restore-ability-to-see-full-password-when-visibility-is-toggled/78152](https://community.bitwarden.com/t/restore-ability-to-see-full-password-when-visibility-is-toggled/78152?u=unmanaged312)

### Operating System

Windows

### Web Browser

Chrome, Microsoft Edge, Brave

### Build Version

2024.12.4

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by djsmith85** [comment]
@BenjaminMichaelis: This has been addressed with https://github.com/bitwarden/clients/pull/12354 and the changes will be included in the `2025.1`-release.

Closing this now.

**Comment by BenjaminMichaelis** [comment]
@djsmith85 I loaded 2025.1 and am not seeing this and don't see it explicitly in the release notes on [github](https://github.com/bitwarden/clients/releases/tag/web-v2025.1.0) - is there some feature flag or similar in front of this behavior?

![Image](https://github.com/user-attachments/assets/3e966367-6eca-4e9f-8051-81cecec514fa)

**Comment by djsmith85** [comment]
Hi @BenjaminMichaelis: I spoke with the team and also tried reproducing this myself with with 2025.1 and wasn't able to:

View item: 
![Image](https://github.com/user-attachments/assets/17f9c4c3-976d-460d-b581-f5ace0645344)

As of 2025.1 and greater all users (cloud and self-hosted) should see the new extension UI which is depicted in the 4th screenshot you attached.

Kind regards,
Daniel

**Comment by BenjaminMichaelis** [comment]
> Hi [@BenjaminMichaelis](https://github.com/BenjaminMichaelis): I spoke with the team and also tried reproducing this myself with with 2025.1 and wasn't able to:
>
> As of 2025.1 and greater all users (cloud and self-hosted) should see the new extension UI which is depicted in the 4th screenshot you attached.
> 
> Kind regards, Daniel

@djsmith85 - Upon closer inspection; I see the difference now; I appreciate you looking into this more.

Where I still see an issue is custom fields, they do not expand like the password field (you are correct that specifically the password field is resolved in 2025.1 and greater). I should of been clear that this was part of the original issue.

![Image](https://github.com/user-attachments/assets/ad2b2086-b493-4ba6-ab19-da3dc138713b)

Is it worth reopening this issue for that aspect?

**Comment by BenjaminMichaelis** [comment]
@djsmith85 I notice also on iOS that it shows the full value for custom fields with no need to scroll; could we match that behavior on the extension as well?

**Comment by BenjaminMichaelis** [comment]
@djsmith85 just looping back around to this again to get your opinion

**Comment by djsmith85** [comment]
@BenjaminMichaelis Thanks for the reminder, this got lost in a slew of other notifications.

This should be addressed with https://github.com/bitwarden/clients/pull/13402

Kind regards,
Daniel
