### ISSUE TITLE
API Key for email alias username generation does not persist across logins

### ISSUE THREAD

**Issue by pnaimoli** [bitwarden/clients#13730]
### Steps To Reproduce

1. Go to Tools -> Generator -> Username
2. Select 'Type: Forwarded email alias', 'Service: Fastmail', 'API Key: [enter your API key]'
3. Click the 'Generate email' button to verify masked emails are being created as expected
4. Navigate elsewhere to verify the API key persists across _this session_
5. Log out, log in.
6. Go back to Tools -> Generator -> Username, API Key is gone

Please note that this is also reproducible in the browser extension, not just the web vault.

### Expected Result

API key should persist

<img width="1840" alt="Image" src="https://github.com/user-attachments/assets/d4bd2c50-58bb-496f-9555-682913b08a60" />

### Actual Result

API Key does not persist

<img width="899" alt="Image" src="https://github.com/user-attachments/assets/cbf9de03-2c17-4c5b-bc06-e21bcd5d37e0" />

### Operating System

macOS

### Operating System Version

Sonoma 14.4 (23E214)

### Web Browser

Firefox

### Browser Version

Librewolf 135.0.1-1

### Build Version

Version: 2025.2.0  SDK: 'main (28c7e29)'

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by pnaimoli** [comment]
For another reproduction of this bug on a different setup, see [this reddit thread](https://www.reddit.com/r/Bitwarden/comments/1imgpz0/fastmail_api_key_not_being_saved_for_generating/).

**Comment by daniellbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by stvev1337** [comment]
I also have this issue, and I've had to create the third API key for the same email alias service.

**Comment by mbartenschlag** [comment]
This issue persists to today.

**Comment by stvev1337** [comment]
sorry i didnt give an update earlier.
reinstalling bitwarden fixes this problem and a related issue where the ui is buggy within this same menu. just a warning, you'll lose your settings.
edit: i just woke up

**Comment by greaterthanstar** [comment]
I've gotten this issue forever, until current day. but now I've got a much bigger problem, the fastmail generator returns an error for a good key. i tried diagnosing it for network problems and came up empty. probably need a different ticket though. android, mobile app

**Comment by greaterthanstar** [comment]
> I've gotten this issue forever, until current day. but now I've got a much bigger problem, the fastmail generator returns an error for a good key. i tried diagnosing it for network problems and came up empty. probably need a different ticket though. android, mobile app 

solved my own issue. if you get an error trying to generate an email, theres a known bug that can only be fixed by wiping data and cache and then completely uninstalling BW and reinstalling. just in case anyone stumbled onto this thread because of that one .

**Comment by roffelofski** [comment]
I'm sadly also running into this problem, almost a year later :'(

**Comment by bronydell** [comment]
I also experience something similar with Fastmail. The API key that I put for generating masked emails is not saved across different devices, making me to keep API key stored somewhere to be put on new device and once I log out - the API key is gone. Frustrating.

**Comment by sayidabyan** [comment]
still happening with simplelogin. kinda frustrating tbh.

**Comment by Alchemytr** [comment]
@daniellbw  - I can confirm this issue is still present, specifically when using DuckDuckGo (DDG) for email aliases.

To help isolate the cause, I have verified that completely uninstalling and reinstalling Bitwarden does not resolve the problem.

Additionally, while the original report specifies the LibreWolf extension on macOS, I am experiencing this bug across the entire Bitwarden ecosystem. This includes browser extensions across all operating systems, as well as the standalone desktop apps and mobile apps (Android and iOS).

Could you advise if I should open separate issues for these other platforms, or if the scope of this existing ticket can be expanded? I am more than happy to log them if it helps progress a fix.

**Comment by pamperer562580892423** [comment]
> I am experiencing this bug across the entire Bitwarden ecosystem.

Though I can understand the desire for settings, API keys etc. to persist between log out / log in, I'm personally not sure if this is a bug. I guess it's more like a missing feature.

When one logs out from a BW client/app, it's expected that the local vault data gets deleted.

<img width="892" height="157" alt="Image" src="https://github.com/user-attachments/assets/43530eeb-abb3-4710-9326-cad7432f9133" />

&nbsp;

(screenshot from: https://bitwarden.com/help/vault-timeout/#session-timeout-action)

And as much as I want my own DDG API key to persist - I wouldn't want my API key floating around in residual data either. (at least not unencrypted, potentially)

So, again, FWIW, I guess this is a missing feature.

PS: Just in case it matters to someone: the API keys persist between **locking** and **unlocking** the vault. (as _locking_ does not delete the local data)

**Comment by Alchemytr** [comment]
Thanks for the additional context, @pamperer562580892423. 

I agree that deleting locally cached data on logout is the correct behaviour, and I also agree that I wouldn't want API credentials left behind in unencrypted residual data.

I think my original use of the term "bug" was a bit imprecise. My concern is really about the user experience rather than the logout behaviour itself.

The fact that the API key survives a lock/unlock cycle suggests it's already being stored securely while the local vault exists. What I'm questioning is why it can't be restored after the next login in the same way that the rest of the encrypted vault is.

From my understanding of Bitwarden's architecture, vault items are encrypted client-side, synchronised, and then re-downloaded and decrypted after authentication. An alias provider API key is also a long-lived secret, so I don't immediately see why it couldn't be modelled similarly (or as an encrypted account setting), rather than existing only as client-local configuration.

There may well be an architectural or product-design reason for that distinction that I'm unaware of, and I'd be interested to understand it if so. Otherwise, this feels more like a missing capability than an unavoidable consequence of clearing local data on logout.
