### ISSUE TITLE
Firefox extension popout fails to load after unlocking

### ISSUE THREAD

**Issue by phobiac** [bitwarden/clients#16191]
### Steps To Reproduce

1. Follow prompt to unlock the bitwarden extension (using master password or using biometrics does not seem to make a difference)
2. Click on the extension icon to load the popout to interact with the vault
3. Popout does not load correctly, it's just an empty rectangle
4. Sidebar view also does not load

### Expected Result

Be able to open an interaction with the vault after unlocking

### Actual Result

See the screenshot below, it is self explanatory.

<img width="1437" height="1012" alt="Image" src="https://github.com/user-attachments/assets/36e51c81-705d-4f0f-915b-59da1c878a74" />

### Screenshots or Videos

I am not the only person experiencing this, see this extension review posted ~12 hours ago
https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/reviews/2484570/
> ...Now, suddenly, I can log in, but after, the little window stays completely empty....

### Additional Context

In the hope this is something to work with to pin this down... Here is the browser console log output when set to use multiprocess mode. These log lines occur whenever opening and then closing the extension popout. The sendRemoveListenter error comes up after clicking the extension icon again to close the popout.

```
WebAssembly is supported in this environment [main.js:856:509556](moz-extension://74859770-fb76-4ccd-8be9-dc278821447e/popup/main.js)
WASM SDK loaded in 36ms [main.js:1:130211](moz-extension://74859770-fb76-4ccd-8be9-dc278821447e/popup/main.js)
State version: 72 [main.js:1:130211](moz-extension://74859770-fb76-4ccd-8be9-dc278821447e/popup/main.js)
sendRemoveListener on closed conduit {446900e4-71c2-419f-a6a7-df9c091e268b}.1511828498077 11 [ConduitsChild.sys.mjs:122:13](resource://gre/modules/ConduitsChild.sys.mjs)
    _send resource://gre/modules/ConduitsChild.sys.mjs:122
    removeListener resource://gre/modules/ExtensionChild.sys.mjs:715
    removeListener resource://gre/modules/ExtensionChild.sys.mjs:971
    register chrome://extensions/content/child/ext-storage.js:165
    removeListener resource://gre/modules/ExtensionCommon.sys.mjs:2961
    revoke resource://gre/modules/ExtensionCommon.sys.mjs:2983
    close resource://gre/modules/ExtensionCommon.sys.mjs:2988
    unload resource://gre/modules/ExtensionCommon.sys.mjs:983
    unload resource://gre/modules/ExtensionPageChild.sys.mjs:279
    unload resource://gre/modules/ExtensionPageChild.sys.mjs:322
    destroyExtensionContext resource://gre/modules/ExtensionPageChild.sys.mjs:494
    observe resource://gre/modules/ExtensionPageChild.sys.mjs:395
```
I also had this warning come up once or twice but it does not seem as easy to replicate
```
downloadable font: Glyph bbox was incorrect (glyph ids 4 5 6 7 13 18 21 22 23 28 35 37 38 54 63 65 66 74 75 78 81 82 88 89 94) (font-family: "bwi-font" style:normal weight:400 stretch:100 src index:1) source: moz-extension://74859770-fb76-4ccd-8be9-dc278821447e/popup/fonts/bwi-font.c53459659794d90d0237.ttf 
```

### Operating System

Windows

### Operating System Version

Microsoft Windows 11 Home 10.0.26100 Build 26100

### Web Browser

Firefox

### Browser Version

142.0 (64-bit)

### Environment Versions

This is inaccessible because the popout does not load, but the extension settings in firefox list it as version 2025.8.1 

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by nordic-style** [comment]
Same here.

<img width="448" height="672" alt="Image" src="https://github.com/user-attachments/assets/53c5a92a-eadb-4c01-b15d-ef96863ef56d" />

**Comment by phobiac** [comment]
I've done a full uninstall of the extension, restarted Firefox, and then reinstalled it and set it up again. Not ideal and an update shouldn't have lead to this but it did fix the issue for me. It seems like there was something cached that broke my install.

**Comment by nordic-style** [comment]
Just did that (uninstall - restart firefox - install plugin) - no change for me :(

<img width="413" height="702" alt="Image" src="https://github.com/user-attachments/assets/cd9ece05-f12f-4259-8773-0753c59822a3" />

I am using Firefox on MacOS
OS: 15.6.1
Firefox: 142.0.1
BW Plugin: 2025.8.1

**Comment by nordic-style** [comment]
Just did a full firefox reset (using about:support / Firefox cleanup) - without success.

**Comment by EthanDarling8** [comment]
Uninstalling the extension, clearing my cache, restarting firefox, and reinstalling fixed it for me.

**Comment by nordic-style** [comment]
I did that again - without success. What i did:
- remove extension
- clear all caches & site data
- restarted firefox
- reinstalled bitwarden extension
- logged in again (which works)
- still no passwords visible / searchable - but autofill works

HELP!

<img width="1641" height="1077" alt="Image" src="https://github.com/user-attachments/assets/b59186ce-c285-4d54-92a5-9fc4a8f5c1af" />

**Comment by phobiac** [comment]
This is a stretch as I think our issues might be different, but while looking for potential fixes I found [this post](https://community.bitwarden.com/t/firefox-extension-popout-window-size-and-being-partially-off-screen/88415/3) in the bitwarden community forum. It instructs turning off `privacy.resistFingerprinting` in the firefox `about:config` menu.

**Comment by Greenderella** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by erik-siverson** [comment]
I also am experiencing this issue.

Clicking the Bitwarden toolbar button opens the vault UI with just a loading spinner.

<img width="292" height="478" alt="browser extension vault tab" src="https://github.com/user-attachments/assets/9b7aae28-f250-4afc-bebc-99f65c5b4138" />

The other tabs along the bottom load correctly.

I prefer to keep the on-field auto-fill buttons disabled and typically go to the toolbar button to fill the fields but for now, I am able to right-click the fields and fill through the context window.

The vault loads correctly through the mobile app.

The vault.bitwarden.com experience is harder to explain:

- there are no folders
- vault entries do appear
- vault entries do not open for editing
- clicking "Copy username" and "Copy password" from the ... menu works
- clicking "+ New" opens the drop-down menu to select what type of item to create but clicking any of them simply closes the menu without bringing up the UI to actually create the item

<img width="423" height="536" alt="web interface filter panel" src="https://github.com/user-attachments/assets/82914fc6-3f5f-433a-aaf9-6f341741c65f" />

The stand-alone desktop app behaves the same way the web interface does.

My work account has no issues in any of the apps I tested - only my personal account.

Please feel free to reach out if there is more information I can provide to help track down the cause.

**Operating System**
Fedora 42: KDE Plasma (three machines)
Windows 11 Pro 24H2 26100.4946 (one machine)

**Web Browser**
Firefox 142.0.1 and 143.0b7 (64-bit)

**Extension Version**
Version: 2025.8.1

SDK: 'main (29c6158)'

Server version: 2025.8.0

**Desktop App Version**
Version 2025.8.2
SDK 'main (29c6158)'
Shell 36.4.0
Renderer 136.0.7103.149
Node 22.15.1
Architecture x64
_The Flatpak via Flathub instances and the Windows instance share the same version details._

**Comment by kewtgh** [comment]
> This is a stretch as I think our issues might be different, but while looking for potential fixes I found [this post](https://community.bitwarden.com/t/firefox-extension-popout-window-size-and-being-partially-off-screen/88415/3) in the bitwarden community forum. It instructs turning off `privacy.resistFingerprinting` in the firefox `about:config` menu.

Mine was set to  “false”  before. But the problem still happened.
My system environment: Win11 24H2, Firefox 142.2

<img width="1397" height="922" alt="Image" src="https://github.com/user-attachments/assets/69e6749a-1baf-436a-afbf-343d755093b0" />

**Comment by sirqix** [comment]
I have ubuntu 24 and I received a new firefox update and have the same problem. Also tried setting the privacy.resistFingerprinting and it didn't help me either.

**Comment by mightyflub** [comment]
I'm having this exact same issue but also on Brave and Edge (As well as now Waterfox after an extension update today). To compound the issue when I try to edit an entry in the desktop app the window appears blank and in the webvault clicking on a vault entry to do anything does nothing. This all seems to have started happening for me a few days ago. Only the IOS version works for me (I have no android devices) This is all on Windows 11. There's a chap on reddit having the issue on MacOS

**Comment by mightyflub** [comment]
> I also am experiencing this issue.
> 
> Clicking the Bitwarden toolbar button opens the vault UI with just a loading spinner.
> <img alt="browser extension vault tab" width="292" height="478" src="https://private-user-images.githubusercontent.com/110146871/484820608-9b7aae28-f250-4afc-bebc-99f65c5b4138.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY5MTcwNjYsIm5iZiI6MTc1NjkxNjc2NiwicGF0aCI6Ii8xMTAxNDY4NzEvNDg0ODIwNjA4LTliN2FhZTI4LWYyNTAtNGFmYy1iZWJjLTk5ZjY1YzViNDEzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkwM1QxNjI2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGExYTc2Nzk1YzNlOGFjZDQwMWU0Zjk5NjRjY2E3MDFkZjgyZTlhMmMxZjU3NTRiYmI0Nzg3ZGQ1ZTA3Njk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.n87JQAE9BLDOU79Izl5pu_kqXCbpCDxaOtMKk8rGQgA">
> 
> The other tabs along the bottom load correctly.
> 
> I prefer to keep the on-field auto-fill buttons disabled and typically go to the toolbar button to fill the fields but for now, I am able to right-click the fields and fill through the context window.
> 
> The vault loads correctly through the mobile app.
> 
> The vault.bitwarden.com experience is harder to explain:
> 
>     * there are no folders
> 
>     * vault entries do appear
> 
>     * vault entries do not open for editing
> 
>     * clicking "Copy username" and "Copy password" from the ... menu works
> 
>     * clicking "+ New" opens the drop-down menu to select what type of item to create but clicking any of them simply closes the menu without bringing up the UI to actually create the item
> 
> 
> <img alt="web interface filter panel" width="423" height="536" src="https://private-user-images.githubusercontent.com/110146871/484826599-82914fc6-3f5f-433a-aaf9-6f341741c65f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY5MTcwNjYsIm5iZiI6MTc1NjkxNjc2NiwicGF0aCI6Ii8xMTAxNDY4NzEvNDg0ODI2NTk5LTgyOTE0ZmM2LTNmNWYtNDMzYS1hYWY5LTZmMzQxNzQxYzY1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkwM1QxNjI2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZmZlYjg5NDNiMzY3NDg4ZDVjYjA2NjYzMmFmMzdiNjljYjhmMjEwOTA2MTE5NTI1NWZhNGQ2Y2UxNzI2OWZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xlGbjLKs7PklFRmNNP8__wNE8-YYrhds1SweFQdxRI0">
> 
> The stand-alone desktop app behaves the same way the web interface does.
> 
> My work account has no issues in any of the apps I tested - only my personal account.
> 
> Please feel free to reach out if there is more information I can provide to help track down the cause.
> 
> **Operating System** Fedora 42: KDE Plasma (three machines) Windows 11 Pro 24H2 26100.4946 (one machine)
> 
> **Web Browser** Firefox 142.0.1 and 143.0b7 (64-bit)
> 
> **Extension Version** Version: 2025.8.1
> 
> SDK: 'main (29c6158)'
> 
> Server version: 2025.8.0
> 
> **Desktop App Version** Version 2025.8.2 SDK 'main (29c6158)' Shell 36.4.0 Renderer 136.0.7103.149 Node 22.15.1 Architecture x64 _The Flatpak via Flathub instances and the Windows instance share the same version details._


I'm experiencing the exact same issues in the desktop app and web vault on Windows 11 24H2

**Comment by nick-livefront** [comment]
Hi! I am unable to recreate the indefinite spinner issue locally. For anyone experiencing this issue, are their any error logs in the console?

You can inspect an extension in FireFox by navigating to `about:debugging` > `This FireFox` > `Bitwarden extension` > `Inspect`, a window should then open and you can view the extension Console Tab.

**Comment by mightyflub** [comment]
> Hi! I am unable to recreate the indefinite spinner issue locally. For anyone experiencing this issue, are their any error logs in the console?
> 
> You can inspect an extension in FireFox by navigating to `about:debugging` > `This FireFox` > `Bitwarden extension` > `Inspect`, a window should then open and you can view the extension Console Tab.
> 
> In my video there are SignalR connection errors logged - those are unrelated to this issue.
> 
>  Screen.Recording.2025-09-03.at.1.51.37.PM.mov


The problem occurs in chromium browsers as well. How do we get the logs from there? There also appears to be a related issue viewing and editing vault items in the web vault and the desktop app.

**Comment by nick-livefront** [comment]
>The problem occurs in chromium browsers as well. How do we get the logs from there? There also appears to be a related issue viewing and editing vault items in the web vault and the desktop app.

Hi @mightyflub, Before logging in on Chromium browsers you can right click or control click on the extension window and select "Inspect" to launch the dev tools, from there you can select the "Console" tab.

<video src="https://github.com/user-attachments/assets/2b31decf-2aee-4bd8-8826-246ffd5ddf1f" />

**Comment by mightyflub** [comment]
<img width="2520" height="1187" alt="Image" src="https://github.com/user-attachments/assets/7a5fdeea-5e5c-4909-8ef2-c65b8e3e76da" />

**Comment by nick-livefront** [comment]
@mightyflub Thank you for providing the screenshot, that will help in debugging this!

**Comment by erik-siverson** [comment]
In Firefox, I get three instances of the following error in the extension's console:
```
console-log.service.ts:51:17
Unhandled error in angular CryptoError: The cipher's MAC doesn't match the expected value
    It bitwarden_wasm_internal_bg.js:4131
    symmetric_decrypt_string bitwarden_wasm_internal_bg.js:2821
    decryptString encrypt.service.implementation.ts:46
    o main.js:856
    invoke zone.js:398
    onInvoke ng_zone.ts:473
    invoke zone.js:397
    run zone.js:113
    I zone.js:2537
    invokeTask zone.js:431
    onInvokeTask ng_zone.ts:450
    invokeTask zone.js:430
    runTask zone.js:161
    y zone.js:612
    promise callback*d zone.js:588
    g zone.js:599
    scheduleTask zone.js:420
    onScheduleTask zone.js:273
    scheduleTask zone.js:411
    scheduleTask zone.js:207
    scheduleMicroTask zone.js:227
    I zone.js:2527
    A zone.js:2461
    S zone.js:2369
    T zone.js:2385
    next firstValueFrom.ts:61
    next Subscriber.ts:161
    _next Subscriber.ts:119
    next Subscriber.ts:75
    i map.ts:58
    _next OperatorSubscriber.ts:70
    next Subscriber.ts:75
    i filter.ts:72
    _next OperatorSubscriber.ts:70
    next Subscriber.ts:75
    i filter.ts:72
    _next OperatorSubscriber.ts:70
    next Subscriber.ts:75
    i map.ts:58
    _next OperatorSubscriber.ts:70
    next Subscriber.ts:75
    i from-chrome-event.ts:35
    write console-log.service.ts:51
    error console-log.service.ts:28
    handleError Angular
    next bootstrap.ts:117
    next Subscriber.ts:161
    _next Subscriber.ts:119
    next Subscriber.ts:75
    next Subject.ts:68
    i errorContext.ts:29
    next Subject.ts:61
    emit event_emitter.ts:136
    onHandleError ng_zone.ts:517
    Angular 2
        invoke
        run
    runOutsideAngular ng_zone.ts:279
    onHandleError ng_zone.ts:517
    Angular 14
        handleError
        runTask
        invokeTask
        invoke
        0
    (Async: setTimeout handler)
        c
        scheduleTask
        onScheduleTask
        scheduleTask
        scheduleTask
        scheduleMacroTask
        g
        o
        e
    setTimeout timeoutProvider.ts:24
    i reportUnhandledError.ts:14
    b Subscriber.ts:242
    error Subscriber.ts:174
    _error Subscriber.ts:124
    error Subscriber.ts:91
    error Subject.ts:82
    i errorContext.ts:29
    error Subject.ts:75
    error share.ts:230
    error Subscriber.ts:172
    _error Subscriber.ts:124
    error Subscriber.ts:91
    _error Subscriber.ts:124
    error Subscriber.ts:91
    _error Subscriber.ts:124
    error Subscriber.ts:91
    error Subject.ts:82
    i errorContext.ts:29
    error Subject.ts:75
    error share.ts:230
    error Subscriber.ts:172
    _error Subscriber.ts:124
    error Subscriber.ts:91
    _error Subscriber.ts:124
    error Subscriber.ts:91
    _error Subscriber.ts:124
    error Subscriber.ts:91
    _error Subscriber.ts:124
    error Subscriber.ts:91
    _error Subscriber.ts:124
    error Subscriber.ts:91
    _error Subscriber.ts:124
    error Subscriber.ts:91
    _error Subscriber.ts:124
    error Subscriber.ts:91
    error Subject.ts:82
    i errorContext.ts:29
    error Subject.ts:75
    error share.ts:230
    error Subscriber.ts:172
    _error Subscriber.ts:124
    error Subscriber.ts:91
    _error Subscriber.ts:124
    error Subscriber.ts:91
    _error Subscriber.ts:124
    error Subscriber.ts:91
    g innerFrom.ts:94
    invoke Angular
    onInvoke ng_zone.ts:473
    Angular 4
        invoke
        run
        I
        invokeTask
    onInvokeTask ng_zone.ts:450
    Angular 14
        invokeTask
        runTask
        y
    (Async: promise callback)
        d
        g
        scheduleTask
        onScheduleTask
        scheduleTask
        scheduleTask
        scheduleMicroTask
        I
        A
        S
        T
    next firstValueFrom.ts:61
    next Subscriber.ts:161
    _next Subscriber.ts:119
    next Subscriber.ts:75
    i map.ts:58
    _next OperatorSubscriber.ts:70
    next Subscriber.ts:75
    i filter.ts:72
    _next OperatorSubscriber.ts:70
    next Subscriber.ts:75
    i filter.ts:72
    _next OperatorSubscriber.ts:70
    next Subscriber.ts:75
    i map.ts:58
    _next OperatorSubscriber.ts:70
    next Subscriber.ts:75
    i from-chrome-event.ts:35
```

**Comment by sirqix** [comment]
So the debugging log says "CryptoError: The cipher's MAC doesn't match the expected value". I did a google and I was able to find this thread from  September of 24, also in bitwarden. Looks like a regression perhaps?

https://github.com/dani-garcia/vaultwarden/discussions/5011

**Comment by nadnerb33** [comment]
I'm also getting this error on Firefox and Chrome across multiple machines.

> CryptoError: The cipher's MAC doesn't match the expected value

I *think* this started after upgrading the plugin a week or so ago - it's currently not working for me on v2025.8.2 on FF & Chrome
I get the loading icon on the vault page, but the vault does seem to be unlocked as I can use auto complete and also the extension icon updates with the number of logins available for each site I visit:

<img width="414" height="650" alt="Image" src="https://github.com/user-attachments/assets/53def453-1c49-4e26-87fe-533e7d5f8dbf" />

For what it's worth, on another machine the Firefox extension is on v2025.6.1 and this is working fine with the same BW account.

**Comment by SergeantConfused** [comment]
Hello everyone,

Thank you all for your input. For anyone that's seeing `The cipher's MAC doesn't match the expected value`, including @erik-siverson, @sirqix, and @nadnerb33, could you all please open the browser's Developer Tools (F12) and log into your individual Bitwarden accounts via the Bitwarden Web App and share with us screenshots of what you see in the Console and Network tabs? Please be sure to share those directly with the Bitwarden Support team via a [support ticket](https://bitwarden.com/help/).

Thank you in advance,

**Comment by mightyflub** [comment]
So send them in a ticket rather than post them here? The support system wanted to close my ticket because it had been open too long.
For reference the web site gives the same cipher errors as the extension

I'm not sure how to save the network logs from f12 but there's reference to a token operation that's sat pending even after I've fully logged in

**Comment by SergeantConfused** [comment]
Hi @mightyflub,

A screenshot of the Console tab would do. Could you also please include your GitHub username in the ticket's body, so I'd find it?

Thank you in advance,

**Comment by mightyflub** [comment]
Ticket raised

**Comment by sirqix** [comment]
> Hello everyone,
> 
> Thank you all for your input. For anyone that's seeing `The cipher's MAC doesn't match the expected value`, including [@erik-siverson](https://github.com/erik-siverson), [@sirqix](https://github.com/sirqix), and [@nadnerb33](https://github.com/nadnerb33), could you all please open the browser's Developer Tools (F12) and log into your individual Bitwarden accounts via the Bitwarden Web App and share with us screenshots of what you see in the Console and Network tabs? Please be sure to share those directly with the Bitwarden Support team via a [support ticket](https://bitwarden.com/help/).
> 
> Thank you in advance,

Opened ticket #700720

**Comment by sirqix** [comment]
I should add I now notice that although I can log into the web interface (which I never do), I cannot  edit any of my vault entries there either. I thought this problem was just restricted to the plugin but clearly thats not the case. Just thought you'd like that extra data point.

**Comment by mightyflub** [comment]
Is there any sign of this being fixed? Currently the only way I can access my vault is via mobile.

**Comment by Darklesss** [comment]
I'm also experiencing intermittent issues similar to the OP (not the loading spinner, but just a blank rectangle when I try to unlock the extension). Running Firefox 142.0.1 on Pop_OS 22.04, with extension version 2025.6.1. See the attached screenshot from immediately after entering my password correctly.


<img width="650" height="855" alt="Image" src="https://github.com/user-attachments/assets/c0495e57-5b1a-407a-a7dc-c2eb62f0a568" />


This has happened 2-3 times over the past few weeks, and when it does I can't unlock or use my vault (note in the screenshot that the vault is still locked). Clicking inside the rectangle does nothing. Clicking outside makes it go away, but the vault is still locked. Trying again just gets me the empty rectangle again.

When this is happening, if I try instead to unlock my vault by clicking in a username/password field in a website and entering my Bitwarden password in the popup, the popup informs me that my tab has crashed (see screenshot)


<img width="650" height="855" alt="Image" src="https://github.com/user-attachments/assets/ddecefc4-12df-45b7-815e-d201c207d82f" />


If I try logging in through the Bitwarden vault website in this state I get a similar result


<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/5af82dd0-221d-4d6c-b388-fcea5829f2c6" />


When this happens closing and restarting Firefox sometimes fixes it and sometimes doesn't - the first couple times I had to restart the laptop to get Bitwarden to work again, but this morning closing and restarting Firefox a couple times worked.

Most of the time (such as now) the extension and vault website work just fine, so this isn't a massive issue for me. But it's frustrating when it does come up, so thank you for looking into it.

**Comment by sirqix** [comment]
I want to update I have done some testing. I have opera with the bitwarden extension 2025.2.1 and it works perfectly. Then, when I update the plugin to 2025.8.2, thats where the problem with the no-vault-display/spinner starts. So, this would strongly suggest its a plugin bug that started with 2025.8.2

I love bitwarden and am still functional since autofill and such is working, but this is an annoying issue and I would like again to ask for any update or status just so we know where we are at.

**Comment by kewtgh** [comment]
Found an update of September 25, but this problem still existed.
What should we do to solve this problem? It is quite inconvenient to use.
Is this problem related with the account? Or database broken? 
Whatever the operating system is, Mac, Linux, or Windows, the problem existed. Whatever Chrome or Firefox, the same.
But login a different account in the same environment, all works great.

**Comment by nordic-style** [comment]
I would guess that somehow broken credentials break the plugin.

**Comment by SergeantConfused** [comment]
Hello everyone,

For anyone that is still encountering this behaviour in the Bitwarden browser extension, could you please log into your individual Bitwarden account via the Bitwarden Web App whilst the browser's Developer Tools (F12) are running and send us screenshots of the Console and Network tabs? The details inside may assist; please send those screenshots directly to the [Bitwarden Support](https://bitwarden.com/help/) team.

By the way, @Darklesss, please update your browser extension and please feel free to reach out to the [Support team](https://bitwarden.com/help/) if you run into any trouble with the up-to-date Firefox extension or the Web App; what you're describing is slightly different from what this GitHub thread is about. 

Thank you all in advance,

**Comment by erik-siverson** [comment]
I've opened ticket #710048 with more information from my developer console.  Please let me know if there's any other information you can use.

**Comment by izhovkin** [comment]
Same happens with MS Edge extensions, blank popup after unlocking.

**Comment by nordic-style** [comment]
I just exported all my passwords and found a lot of this:
  "folders": [
    {
      "id": "8ab29ee5-6a70-4802-b940-6fb01ef63f96",
      "name": null
    },
    {
      "id": "89007a86-e980-4edf-8e30-e9cb7dff0bde",
      "name": null
    },
    {
      "id": "69ca67e7-5949-4758-85b2-ee037f876ff3",
      "name": null
    },
    {
      "id": "9829d1c3-21b4-441c-901e-c9e21481e24f",
      "name": null
    },

after deleting all the "name": null entries the plugin works again.

**Comment by mightyflub** [comment]
Did you edit the json and reimport? Did you need to delete all the original entries first?

**Comment by brendan33** [comment]
thanks @nordic-style 

I managed to repair my vault without exporting/importing.
In the plugin, go to Settings > Vault Options > Folders 
You'll then see some folder entries saying something like "[Failed to decode]".
I didn't want to delete them (not sure what happens to the content)
So I renamed them all and then synced my vault. Then I disabled/enabled plugin, logged in and it works again.

I do remember in the past that I seemed to have a lot of logins assigned to [empty] folder name - no idea where they came from originally. Possibly when I imported my data from LastPass a few years ago?

**Comment by mightyflub** [comment]
Looking in the iOS app (The only way I can view my vault currently) I can see I have over 10 folders with no name. And in the iOS app there's no way to delete them

Also lol after importing a few json files it would seem the system doesn't ignore duplicates. I'm going to have quite a large cleanup job when this is all fixed.

**Comment by mightyflub** [comment]
I've deleted all my folders with no names on the iOS app, resynced and now my browser plugin is working again. Thanks Brendan33. Amazing work. Now I just have to delete all those duplicates I managed to acquire with my imorts

**Comment by pamperer562580892423** [comment]
Just reading the latests posts here, I wonder if this might be a related bug fix PR: https://github.com/bitwarden/clients/pull/16796 ? @SergeantConfused

**Comment by mightyflub** [comment]
That looks exactly what it was in my case.

**Comment by nordic-style** [comment]
> Did you edit the json and reimport? Did you need to delete all the original entries first?

Yes - you can delete all with one click.

**Comment by kewtgh** [comment]
The problem is account-related. 
I solved this problem by deleting my account and re-registered a new one.

!!! **Don't forget to export all your passwords and notes.**

Use your web app.

**Comment by QuentinBouvier** [comment]
I have the same issue, completely blank screen when connected. There is no fingerprinting resisting activated, and I tried uninstalling and reinstalling the extension.

<img width="404" height="698" alt="Image" src="https://github.com/user-attachments/assets/7ff68e69-f54e-4135-b5e9-d3cc77da4f26" />

Nothing in the firefox console.

Note that I'm accessing a self-hosted vault, if it's of any help.

**Comment by sirqix** [comment]
I just want to update and say I have noticed now the functionality now works. No idea how or why but the popout now works correctly again. I also see in my vault a small number of entries that are labeled as 'BROKEN'. But everything I care about does appear to be here, so it seems this is resolved.

Although I love bitwarden and pay for the premium just because I want to support 'em, I want to complain loudly how badly this problem was handled and the lack of transparency or follow up. I have participated behind the scenes in an ongoing support ticket concerning this issue that suddenly stopped receiving responses. Ive sent follow up queries to support that have gone unanswered. The engagement here in this forum has been minimal at best. I totally don't expect a formal individualized support response like if I was dealing with a show stopper cisco bug and I have TAC working on it, but at the same time, just basic engagement with the user community would have been really super appreciated. 

I would love some kind of changelog or other announcement just detailing what the deal is/was, what these new 'broken' entries are, and how it was solved. Otherwise, Im good here and damm happy to see this fixed as it was a major annoyance.

**Comment by edomod** [comment]
I'm experiencing the exact same problem.

In my case:
- The vault doesn't load in any environment (web, browser extension, desktop app)
- Autofill is completely non-functional
- The desktop app is unusable
- Only the mobile app works for me

This makes it impossible for me to use Bitwarden in its full capacity. The situation is critical since I depend on the vault to access my accounts.
I hope this issue gets resolved as soon as possible.

<img width="381" height="600" alt="Image" src="https://github.com/user-attachments/assets/50dd8904-ce83-4b4e-b3e8-8aa6734ded66" />

**Comment by sirqix** [comment]
> I'm experiencing the exact same problem.
> 
> In my case:
> 
> * The vault doesn't load in any environment (web, browser extension, desktop app)
> * Autofill is completely non-functional
> * The desktop app is unusable
> * Only the mobile app works for me
> 
> This makes it impossible for me to use Bitwarden in its full capacity. The situation is critical since I depend on the vault to access my accounts. I hope this issue gets resolved as soon as possible.
> 
> <img alt="Image" width="381" height="600" src="https://private-user-images.githubusercontent.com/82822454/521843429-50dd8904-ce83-4b4e-b3e8-8aa6734ded66.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ3NjQ1MDksIm5iZiI6MTc2NDc2NDIwOSwicGF0aCI6Ii84MjgyMjQ1NC81MjE4NDM0MjktNTBkZDg5MDQtY2U4My00YjRlLWIzZTgtOGFhNjczNGRlZDY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjAzVDEyMTY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjYjljZGRlY2VjMDY0NmZkZTE4MGFkMTkzZWRiYWY0ZTNkMGQzMjM4MmQ1NmY3NzM2YTEyNjRmOTg1NmE4YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v3e6nMdG6coyuoLK-S5St9lfHXSLquKhb1Va9S-MF0Q">

This has gotten resolved but but warden has been 100% closed about this. no public or private comments  I am aware of, but, it looks to me that the fix involved renaming certain vault entries or possibly deleting duplicates and it's something I think they did on their end quietly. Very irresponsible, bitwarden, we want transparency and God dammit respond to your support email, I'm not paying you for nothing...

**Comment by edomod** [comment]
Fixed! I exported my passwords, deleted and recreated my account, then re-imported the passwords. Everything is working now vault loads, autofill functions, and the desktop app is operational.

**Comment by phobiac** [comment]
For whatever it is worth, this issue seems to have people coming in with two similar but distinct issues. My original reported problem is that the pop-up in the extension does not load at all. I have had this happen a few times since reporting this and the recent times have all been resolved by fully closing and re-opening Firefox, which lends support for it being some sort of cache issue. 

For the people who are having the popup load partially but not pull in data from your vault, or even worse the desktop client also will not load, I believe you are dealing with something entirely different. This issue does not seem like the appropriate place for a problem that seems to need manipulation of the data saved in the vault itself to solve (per some of the suggested fixes).

Regardless, I do wish there was more communication from Bitwarden on the problem as both issues mean it is essentially non-functional and harder to count on for password management.

**Comment by warwickmm** [comment]
I'm also experiencing this with Brave 1.87.192 using the extension:

Version: 2026.1.1
SDK: 'main (8e5efd8)'
Server version: 2026.2.1

Disabling/enabling the extension resolves the problem, but that's obviously not a fix.  The problem occurs daily.

**Comment by sirqix** [comment]
Bitwarden completely buried this issue which came on without explanation, was never responded to adequately by bitwarden, but was ultimately resolved apparently by a mass change to all client wallets by resetting/clearing out certain entries which may have been duplicates or other detritus. Bitwarden did not act responsibly here and I think they are hiding a breach

**Comment by diesieben07** [comment]
This issue still exists for me.
I can reproduce it like this:
1. Extension configured to sign out on browser restart (Settings > Account Security > Timeout "On Browser Restart", Timeout action "Log out"
2. Sign out of the extension (User Avatar -> Log out)
3. Go to a website where you want to log in
4. Hit the "autofill" shortcut (Ctrl-Shift-L) 
5. Extension will pop up the "Log in" dialog _in a window_ (not the usual overlay)
6. Log in (in my case I have 2FA required with a YubiKey - I do not know if that is a factor)

Now the extension is in this broken state and won't load anything but a blank window. It can usually be fixed by just disabling and re-enabling the extension.

**Comment by pamperer562580892423** [comment]
@diesieben07 I must confess I now didn't read all other comments again... but your Steps of Reproduction are completely different than those of the original post (which also was about "unlocking" and not "log in")... so I think it may be better to open a new bug report about the issue you describe @diesieben07 (may be related to the original issue, or may not be related to the original issue...).

(BTW, knowing about your extension version, browser (including the version) and OS (including the version) would be helpful in any case)

**Comment by diesieben07** [comment]
@pamperer562580892423 Thanks for the info, I will open a new issue!

**Comment by phobiac** [comment]
I'm closing this as it has been fixed for me for a while now.

**Comment by VarunAgw** [comment]
Happening again for me since a month now

**Comment by phobiac** [comment]
I would recommend opening a new issue describing your exact problem as this one got a bit confusing with people describing an entirely different problem from what I originally reported.
