### ISSUE TITLE
Bitwarden foregrounds itself on vault lock

### ISSUE THREAD

**Issue by OlehAhieienko** [bitwarden/clients#16575]
### Steps To Reproduce

1. Start Bitwarden client
2. Unlock vault
3. Minimize window or send it to background
4. Wait till vault is locked

### Expected Result

Bitwarden's window with "Vault unlock" prompt stays in background

### Actual Result

Windows with "Vault unlock" prompt pops to foreground

### Additional Context

It may not be bug per se, but this thing should be configurable at least

### Operating System

Linux

### Operating System Version

Arch Linux

### Installation method

Other

### Build Version

2025.8.1

### Issue Tracking Info

- [x] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

This has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by purelines** [comment]
This annoying behavior started in the fall of 2023 and has been a daily inconvenience since then. I had to switch the timeout setting to "On system lock" instead of 15 minutes, because no matter what I'm doing, writing code or watching a full-screen video, Bitwarden keeps popping up to say it has locked itself.

Please fix this already!

**Comment by cj-wong** [comment]
This is an issue on my machine:

- OS: Bazzite
- Installation: Flatpak
- Desktop: KDE Plasma

**Comment by cj-wong** [comment]
Looks like the problem has been solved on my end with version 2025.12.1, the current latest release.

Version 2025.12.1
SDK 'main (93a331f)'
Shell 39.2.6
Renderer 142.0.7444.226
Node 22.21.1
Architecture x64

**Comment by bb010g** [comment]
I think this issue is a duplicate of:
- #11045

**Comment by cj-wong** [comment]
I don't think it is. I don't use workspaces, and I had this issue on my primary computer.

This issue isn't resolved for my Steam Deck on SteamOS stable using X11 (Plasma 6.2.5).

**Comment by cj-wong** [comment]
Regression to prior behavior on current release:

Version 2026.1.0
SDK 'main (8e5efd8)'
Shell 39.2.6
Renderer 142.0.7444.226
Node 22.21.1
Architecture x64

That is to say, Bitwarden puts itself in the foreground when locking, again.

**Comment by purelines** [comment]
> Looks like the problem has been solved on my end with version 2025.12.1, the current latest release.

I checked version v2025.12.1 and cannot confirm the fix (GNOME Shell 42.9, X11, AppImage): the app still moves to the foreground when the lock timeout triggers.

The issue is still present in the latest version v2026.2.1.
