### ISSUE TITLE
[1.49.0] Safari with square window, opening delay, wrong button focus and missing Biometrics option

### ISSUE THREAD

**Issue by kennymc-c** [bitwarden/clients#1692]
### Not fixed

⚠️  Since the recent 1.49.0 update the Safari extension now has a square window instead of a rectangular like in other browsers.

### Fixed

These bugs have been fixed and are no longer the focus of this ticket:

✅ (fixed with Safari 15)
Opening the window takes almost 3 seconds.

✅ (fixed)
The announced unlock with Biometrics option for this update is also missing. In Chrome it works for me.

✅ (fixed with Safari 15)
Also there is this glitch next to the popout icon:
<img width="74" alt="Bildschirmfoto 2021-03-13 um 01 13 21" src="https://user-images.githubusercontent.com/14995555/111011561-19717400-839a-11eb-856e-2628abdb5d89.png">

## Expected Result

⚠️ A rectangular window
✅ No delay between clicking and opening the window
✅ Unlock with Biometrics option
✅ Popout icon without glitch like this:
<img width="73" alt="Bildschirmfoto 2021-03-13 um 01 23 14" src="https://user-images.githubusercontent.com/14995555/111011770-b6341180-839a-11eb-8e71-7e2b8ba93277.png">

## Actual Result

⚠️ A square window
3 seconds delay between clicking and opening the window
Unlock with Biometrics option is missing
A glitch next to the popout icon

## Environment

- Operating system: macOS Big Sur 11.2.3
- Browser: Safari 14.0.3
- Build Version (go to "Settings" → "About" in the app): 1.49.0

**Comment by gshen42** [comment]
Second this. Also, maybe it's just me, but I feel the window also takes significantly more time to show up.

**Comment by shivpatel** [comment]
> Second this. Also, maybe it's just me, but I feel the window takes significantly more time than before to show up.

Agreed on the slowness and awkward UI now.

This release feels like a step back in terms of quality/experience. It's like I'm using a beta release.

**Comment by godly-devotion** [comment]
It seems the square window was fixed with this commit https://github.com/bitwarden/browser/commit/9063a98949f0b2656feafe19c64ecf6f2802b43d
As for the popout button, it seem the focus is set to the button causing it to have the highlight. Clicking on another item seems to remove the focus and the highlight on it. Maybe setting the initial focus on the Search bar instead will mitigate this issue as well as allow the user to immediately start typing.

**Comment by matt-from-uk** [comment]
> Second this. Also, maybe it's just me, but I feel the window takes significantly more time than before to show up.

Agreed - the window is now **very** slow to open. I hope that is just a bug. I don't think I would cope if it is going to be normal behaviour.

**Comment by kennymc-c** [comment]
Yes, opening the window is very slow. But after that everything seems to be as fast as before.
I also noticed that auto-fill is not functioning on sites where it worked before. I had to reenabled it after the update.

**Comment by lbroto** [comment]
Yes, opening the window is very slow, more than 3s between the click and the moment the window appears. There is a square window here too.

MacOS Big Sure 11.2.3, Safari 14.0.3, architecture: Silicon M1, Bitwarden extension release: 1.49.0

**Comment by l0rda** [comment]
I confirm these issues on M1:

1. 3 seconds delay between clicking and opening the window
2. Unlock with Biometrics option is missing
3. safari crashing if allow extension to work on all sites

but i cannot confirm glitch effect and square window

**Comment by Ghantaz** [comment]
I would like to add that autofill using the keyboard shortcuts is as snappy as before. The UI itself is quite snappy once its loaded.

**Comment by KondorB** [comment]
Second this. The update just broke the extension for no apparent reason. The window is tiny and opens with a significant delay. Also, who thought that this super annoying red counter is a good idea? Can't find a way to disable it.

<img width="48" alt="Снимок экрана 2021-03-14 в 12 28 19" src="https://user-images.githubusercontent.com/5469212/111063669-0b6a4300-84c1-11eb-88c8-e1af26847ce1.png">

**Comment by hexicans** [comment]
Hello
Same here, very long to open...

**Comment by Vinz87** [comment]
same here, small window dimension, and an annoying red badge on top of the minimalistic Safari design without a reason: I know exactly on which websites I have an account and how many of them.

**Comment by hacker1024** [comment]
Also, the dropdown buttons look like they're older than macOS Yosemite.

![image](https://user-images.githubusercontent.com/20849728/111605821-b6189380-882a-11eb-824d-2482ae501faf.png)

**Comment by andrewkr** [comment]
> and an annoying red badge on top of the minimalistic Safari design without a reason: I know exactly on which websites I have an account and how many of them.

I like the 'annoying red badge'!

**Comment by pwxn** [comment]
> > > and an annoying red badge on top of the minimalistic Safari design without a reason: I know exactly on which websites I have an account and how many of them.
> > 
> > 
> > I like the 'annoying red badge'!
> 
> that's totally legit, just give the user the option to choose :)

I believe the red badge issue is resolved in PR #1630 with an option to disable it.

**Comment by hacker1024** [comment]
IIRC the red badge was grey before, I think it fits the Safari UI more appropriately that way.

**Comment by oldenboom** [comment]
> It seems the square window was fixed with this commit [9063a98](https://github.com/bitwarden/browser/commit/9063a98949f0b2656feafe19c64ecf6f2802b43d)

This fix looks a bit weird. It adds a class to the body-element to modify the height using CSS but at the end the height is maximized with the important-modifier. Also wrote this comment to the merge-request.

**Comment by kennymc-c** [comment]
I just installed 1.49.1 with the desktop app update and not a single item from this issue seems to be fixed. I was at least hoping for the incorrect focus on the pop-out button, since that should be pretty easy to fix. 

The only issue that can be ignored for now is the missing biometrics option, which seems to be available for Safari at a later date. Unfortunately there was wrong information about this in the community forum.

**Comment by lbroto** [comment]
Same here. 1.49.1 does not solve anything: still long to opening delay, still square window.

**Comment by cscharf** [comment]
1.49.1 was not for any of these issues (there are no linked PRs here and this issue is still open). 1.49.1 was released as a Firefox patch to fix older versions of Firefox crashing and file upload for send not working in Chromium browsers on Linux. These issues are on the radar, however on a ticket such as this it's difficult because it's not listing a single issue, it's listing multiple, unrelated issues and folks are kind of piling on other things as well.

@kennymc-c , the report is much appreciated, but would be helpful for tracking if 1 issue = 1 issue in GitHub, otherwise it's difficult to provide a status on a single issue in GitHub that represents several different, unrelated issues.

The initial or 1st problem noted, square pop-out, is resolved with https://github.com/bitwarden/browser/pull/1714 and will be released in the next browser extension update. We are working through some other M1 Apple Silicone native/universal build items and will likely release it then.

**Comment by kennymc-c** [comment]
Thanks @cscharf 
Noticed that #1693 also seems to fix the pop-out button glitch issue. According to the screenshots of the pr, it looks like the focus is still on the pop-out button and not the search field as it used to be.

**Comment by green-brontosaurus** [comment]
@cscharf I speak for all of us when I say that I appreciate all of the work that you're doing on these bugs. Do you have any updates on (1) the long lag when clicking on the Bitwarden icon, and (2) the Bitwarden pop up not automatically minimizing when you click on your login information? Many thanks!

**Comment by cscharf** [comment]
@green-brontosaurus ,

> I speak for all of us when I say that I appreciate all of the work that you're doing on these bugs.

Of course, we ❤️  you guys and our community and want to give everyone an amazing product, making security accessible to everyone (for free).

> Do you have any updates on (1) the long lag when clicking on the Bitwarden icon, and (2) the Bitwarden pop up not automatically minimizing when you click on your login information?

No, unfortunately we've not had an opportunity to get to those. The "lag" seems to be a quirk with Safari in how its unloading and reloading the context state of the extension. Unlike the App Extension which always was running in the background, Safari treats Web Extensions as a 2nd class citizen, in true Apple fashion, works a bit differently than other browsers and we're only finding this out now that we've gone down that road. If you're on M1 hardware, there may be some issues with the extension package not being a `--universal` package (Apple Silicon/ARM), so since Rosetta2 naturally adds some overhead to both the Desktop app and underpinnings of the Web Extension through Safari, our hope is once we're able to get our universal build working (which we've had to do a few patches to electron-builder to support and get working) that will 🤞🏻  hopefully eliminate some of the lag.

> (2) the Bitwarden pop up not automatically minimizing when you click on your login information?

I haven't seen another issue for this particular problem, would you mind creating one so the team can work on validation and it gets on our board?

**Comment by green-brontosaurus** [comment]
> @green-brontosaurus ,
> 
> > I speak for all of us when I say that I appreciate all of the work that you're doing on these bugs.
> 
> Of course, we ❤️ you guys and our community and want to give everyone an amazing product, making security accessible to everyone (for free).
> 
> > Do you have any updates on (1) the long lag when clicking on the Bitwarden icon, and (2) the Bitwarden pop up not automatically minimizing when you click on your login information?
> 
> No, unfortunately we've not had an opportunity to get to those. The "lag" seems to be a quirk with Safari in how its unloading and reloading the context state of the extension. Unlike the App Extension which always was running in the background, Safari treats Web Extensions as a 2nd class citizen, in true Apple fashion, works a bit differently than other browsers and we're only finding this out now that we've gone down that road. If you're on M1 hardware, there may be some issues with the extension package not being a `--universal` package (Apple Silicon/ARM), so since Rosetta2 naturally adds some overhead to both the Desktop app and underpinnings of the Web Extension through Safari, our hope is once we're able to get our universal build working (which we've had to do a few patches to electron-builder to support and get working) that will 🤞🏻 hopefully eliminate some of the lag.
> 
> > (2) the Bitwarden pop up not automatically minimizing when you click on your login information?
> 
> I haven't seen another issue for this particular problem, would you mind creating one so the team can work on validation and it gets on our board?

@cscharf For sure! Can you please confirm that you see the post on your end? Here's a link to it: https://github.com/bitwarden/browser/issues/1742

**Comment by cscharf** [comment]
> For sure! Can you please confirm that you see the post on your end?

Confirmed, Thank you!

**Comment by aiotter** [comment]
The absence of biometric option on safari 14.0.3 took me here.
![image](https://user-images.githubusercontent.com/37664775/119247976-f1d42e80-bbc8-11eb-82ec-923cb473f53f.png)

AFAIK the biometric support on Safari is available just after 11 May, so I feel it really weird it was reported here, the issue opened on 13 May.

@cscharf Should I report my issue here or create new one? If I missed the corresponding issue, I appreciate it if you can take me there.

**Comment by tgreer-bw** [comment]
@aiotter the biometrics option is in version 1.50+ of the extension (paired with v1.26+ of the Desktop app) - it's still in review with apple at the moment.

**Comment by kennymc-c** [comment]
Apart from the now working biometrics option, all other bugs are unfortunately still present in 1.50.0.

**Comment by Sixfiveone** [comment]
Are these Safari bugs being addressed?

The delay when clicking on the extension is still present and is becoming incredibly frustrating to deal with on a daily basis. It may not seem like a big deal, but it is. I don't want to use a different browser. I REALLY don't want to move away from Bitwarden, either.

Please fix these Safari issues. I beg you.

**Comment by hexicans** [comment]
> Are these Safari bugs being addressed?
> 
> The delay when clicking on the extension is still present and is becoming incredibly frustrating to deal with on a daily basis. It may not seem like a big deal, but it is. I don't want to use a different browser. I REALLY don't want to move away from Bitwarden, either.
> 
> Please fix these Safari issues. I beg you.

Hi

Personnaly, I use the old version of Bitwarden given by @cscharf and working perfectly.
I invite you to do the same ...

https://github.com/bitwarden/browser/issues/1732#issuecomment-842576787

**Comment by aiotter** [comment]
For me, on Safari 14.1.1, the bug of square popup still exists. I don't feel too much delay. It's like just a 1s for me.

**Comment by kennymc-c** [comment]
And again...nothing has been fixed in 1.51.1 
@cscharf Will these bugs ever be resolved?

**Comment by cscharf** [comment]
@kennymc-c , was the square pop-out not resolved?

**Comment by kennymc-c** [comment]
@cscharf no, the square pop-out, the wrong text focus and the delay on opening are still present

**Comment by cscharf** [comment]
Okay, the text focus and square pop-out are easy enough fixes, assigning someone to work on these now. The delay to open we're still (yes still, and likely will be until it just magically stops one day) waiting for Apple to respond to our open issues, this is one of them. If history repeats itself Apple will never respond or communicate around the issue and it'll just resolve itself; but after tracing this down the delay is 99% within Safari's internals before calling our extension to paint.

**Comment by cscharf** [comment]
Hi @kennymc-c , at this point I've left the initial focus issue to Thomas to resolve when he's able. As for the other issues we are not going to address those right now:

* On the square popup window; this was done on purpose due to a WebKit issue documented [here](https://developer.apple.com/forums/thread/663184) and [here](https://bugs.webkit.org/show_bug.cgi?id=218704) which have yet to be resolved upstream by Apple
* On the slow opening time, please refer here: https://github.com/bitwarden/browser/issues/1732
* On any other issues please search our issues list for existing reports or open a new item for them.

This issue will ultimately be converted to a single issue/resolution: Focus on load to search text box.

**Comment by kennymc-c** [comment]
Just updated to Safari 15.0 and the focus problem seems to be fixed. Also the opening delay is now almost gone like is was mentioned in #1732 with the technology preview version.

**Comment by kennymc-c** [comment]
@cscharf Should I reopen this issue until the webkit bug is fixed or create a new issue for this? Maybe this could lead to confusion because other issues where this webkit bug was mentioned link here.

**Comment by cscharf** [comment]
Let's reopen this one and repurpose it specifically for the Webkit bug that has us limited to the 440px "square" popup so as not to create confusion, thanks for the question and clarification @kennymc-c

**Comment by aiotter** [comment]
@kennymc-c Can you edit the title of this issue so that the new purpose will be clear to everyone?

**Comment by kennymc-c** [comment]
@aiotter The title has always included the popout window size problem. Or what do you mean by that?

**Comment by aiotter** [comment]
@kennymc-c Now this issue is focusing on square window only, so shouldn't the title include only that? And on the current title, as the issue is still opened, it seems the rest of the problems being still unfixed.

**Comment by kennymc-c** [comment]
@aiotter I think deleting the other issues from the title maybe confuse other people. This issue contains more than one bug and not all of them are fixed.
Splitting up the remaining bug into a new issue would be an option but this was already discussed earlier.

**Comment by Crocmagnon** [comment]
I've recently started using safari again, the square window is really annoying.

**Comment by createchange** [comment]
Just bringing attention to the square window issue again. Not a dealbreaker for me, but would be nice to have fixed.

**Comment by kennymc-c** [comment]
As mentioned [before](https://github.com/bitwarden/browser/issues/1692#issuecomment-880977768) this issue is caused by a WebKit bug that needs to be solved first.

**Comment by thisispiers** [comment]
Firefox 106 on macOS 12.6, the window is 300px in height the first time Bitwarden is opened in a tab, but reopening the extension increases window size. Quite annoying for websites with lots of credentials.

**Comment by Savjee** [comment]
The issue seems to be fixed in Safari 16.1 (on macOS Ventura 13.0.1).

Tested with the demo extension attached to the WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=218704
Hoping we can get a larger window size now ;)

https://user-images.githubusercontent.com/817109/205869829-a83986fc-096f-415b-9208-b28136f33b10.mov

**Comment by kennymc-c** [comment]
@cscharf Are there any updates on this since the WebKit bug seems to be fixed? This is even more annoying with the new Extension UI.

**Comment by eliykat** [comment]
Thanks for the heads up @Savjee! I've opened a PR to revert the workaround. It looks good to me but QA will also give it a good going over before merge to confirm.

**Comment by Pierre-G** [comment]
@eliykat I still have a square window. Any news on your PR ?

**Comment by eliykat** [comment]
Hi @Pierre-G, I'll ask the team handling the issue to post any updates in this thread.

**Comment by dani-garcia** [comment]
The PR solving this issue is now merged but it won't make the cut for April's release, which is tomorrow. If everything goes well it should be available on the March release.

**Comment by HazemAM** [comment]
@dani-garcia next year? 😱

**Comment by dani-garcia** [comment]
I meant May, so next month, seems like I get to buy a calendar for my office 😃

**Comment by Pierre-G** [comment]
Bitwarden client has now been updated on Mac App Store, solving the square window issue. Thanks @dani-garcia for your help on this!
