### ISSUE TITLE
Menu bar wont rest to the dark theme

### ISSUE THREAD

**Issue by pfanzola** [bitwarden/clients#17451]
### Steps To Reproduce

I'm on Bitwarden Linux (flatpak), Fedora 42, when i apply the dark mode the menu bar of the app goes in dark theme, as it should be, but when i reboot or shutdown my pc it returns to the light theme. I've tried several times without solution. I've got this issue only in KDE, on GNOME this works fine.

Step to reproduce:

    apply dark theme

<img width="1095" height="76" alt="Image" src="https://github.com/user-attachments/assets/4987f8d3-a058-4c00-aa38-76ea72eb0d1c" />

    close the session/reboot/shutdown and the menu bar returns to the light mode.

<img width="1097" height="82" alt="Image" src="https://github.com/user-attachments/assets/3888a1ed-a146-4bfe-8536-3f31410d6cfb" />

Workaround: installing the END OF LIFE  breeze gtk3 dark theme/runtime solve this issue.

### Expected Result

dark theme work as expected

### Actual Result

light theme menubar instead of the dark one

### Operating System

Linux

### Operating System Version

FEDORA 42

### Installation method

Flatpak

### Build Version

2025.11.0

### Issue Tracking Info

- [x] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by pfanzola** [comment]
This issue is only visible on KDE, without the org.gtk3.breeze-dark runtime installed (wich is EOL) using the org.gtk3.breeze runtime wich is for now supported. No other setups required just a fresh install of fedora 43 kde edition with the dark theme applied

**Comment by Chapien** [comment]
Is there any chance of this being fixed?

**Comment by pfanzola** [comment]
Bitwarden 2026.3.1 is still affected by this issue. 
The only workaround is installing an old (eol) runtime org.gtk3.breeze-dark, while on GNOME systems it works perfectly.
specs: fedora 44, kde plasma 6.6

**Comment by Chapien** [comment]
> Bitwarden 2026.3.1 is still affected by this issue. The only workaround is installing an old (eol) runtime org.gtk3.breeze-dark, while on GNOME systems it works perfectly. specs: fedora 44, kde plasma 6.6

How do you install an out of date runtime on flatpak? Do you just pin it and then run the application with the runtime?

**Comment by Chapien** [comment]
Figured it out. For those curious, you can install this EOL runtime with:
`flatpak install flathub org.gtk.Gtk3theme.Breeze-Dark`

That said, this is not a long-term solution, and Bitwarden should not be using EOL runtimes.

**Comment by rowschank** [comment]
I have this issue on openSUSE Tumbleweed KDE Plasma 2026-06-10 release using Bitwarden 2026.5. All the "GTK-like" elements do not obey dark mode: e.g. Toolbar, Help -> About Bitwarden, etc. 

<img width="1278" height="77" alt="Image" src="https://github.com/user-attachments/assets/380eb63b-a1fc-490d-baa9-1d81a9c05e48" />

<img width="260" height="274" alt="Image" src="https://github.com/user-attachments/assets/38193da5-345a-4231-afbf-574550ae0d7e" />

For info, this problem used to exist earlier in Bitwarden I think (late 2025), but was fixed in early 2026 before the app got redesigned.

**Comment by pfanzola** [comment]
update: still not working in bitwarden 2026.6

<img width="1251" height="124" alt="Image" src="https://github.com/user-attachments/assets/c54e7331-dbcf-4f21-b395-960a0d95752c" />

**Comment by pfanzola** [comment]
> For info, this problem used to exist earlier in Bitwarden I think (late 2025), but was fixed in early 2026 before the app got redesigned.

Indeed I experienced this too

**Comment by rowschank** [comment]
> update: still not working in bitwarden 2026.6
> 
> <img alt="Image" width="1251" height="124" src="https://private-user-images.githubusercontent.com/221717063/613533027-c54e7331-dbcf-4f21-b395-960a0d95752c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODI0NTg1MjksIm5iZiI6MTc4MjQ1ODIyOSwicGF0aCI6Ii8yMjE3MTcwNjMvNjEzNTMzMDI3LWM1NGU3MzMxLWRiY2YtNGYyMS1iMzk1LTk2MGEwZDk1NzUyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDYyNlQwNzE3MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NWUzMTNhZjg3MTY2MGE4YTdiNGFjYmY2Yzc3NTAzMTZiZTU3MzRmYWQxOTM3NmExNGExYzI0MWI3NTE1M2FhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.dU8eXq9qP3eqO3jW1wFwoUBPWV07aosGZlA_kA-_Y4Q">

Same, not working on OpenSUSE KDE either.
