### ISSUE TITLE
Unlock with Biometrics missing on Mac when started in clamshell mode

### ISSUE THREAD

**Issue by hayeskl** [bitwarden/clients#2572]
### Steps To Reproduce

1. After installing 1.32.0 from the Mac App Store on mac with Touch ID enabled
2. Go to Bitwarden Preferences 
3. Scroll down to 'Security'
4. Only Unlock with PIN is available

### Expected Result

There should be an Unlock with Biometrics option under the Unlock with PIN option

### Actual Result

The Unlock with Biometrics option is not present

### Additional Context

My mac is using Apple's M1 Max chip.

### Operating System

macOS

### Operating System Version

12.3

### Installation method

Mac App Store

### Build Version

1.32.0

**Comment by sampl3x** [comment]
Is this issue fixed now? So can Bitwarden be unlocked with Apple keyboard with integrated touch id button when the macbook is in clamshell mode?

**Comment by mada199122** [comment]
Yes I confirm now it works with apple keyboard with Touch ID when the MacBook is in clamshell mode

**Comment by hayeskl** [comment]
This issue was not related to the apple keyboard with Touch ID.  It is for users with an Apple Watch unable to use biometric to unlock the device because the option is completely removed when in clamshell mode.

**Comment by RateThePaladin** [comment]
This functionality is still not working for me. Using latest Safari browser extension on a 2019 MacBook Pro. Unlock with apple watch works with the lid open but not when in clamshell mode, plugin errors out with "Browser biometrics is not supported on this device". +1 to the importance of this functionality, would significantly improve my experience with the product.

**Comment by dbosompem** [comment]
Hi @RateThePaladin, thanks for bringing this up. The team would make time to investigate so we can improve the behavior.

**Comment by RateThePaladin** [comment]
Thanks for looking into this @dbosompem!

**Comment by Schokobecher** [comment]
Is there any progress on this?

**Comment by LordShedy** [comment]
I can report that this has happened to me as well. I discovered that I can reproduce this issue following:

1. log out of all Bitwarden Vaults,
2. install the app (either via Mac App Store or brew works the same – 10.1 and 11),
3. install and log in while mac lid is opened,
4. the TouchID is visible

but when the step 3 is done with lid closed (clammed mode), then the TouchID never shows up again

**Comment by mbarbero** [comment]
I just pushed a [PR to electron](https://github.com/electron/electron/pull/36935) and BitWarden should inherit the enhanced behavior whenever it will upgrade to a version that will include this fix.

**Comment by Schokobecher** [comment]
My guess is it will be a while since #3415  has yet to be accepted (or received public feedback)

**Comment by x2on** [comment]
@vanitalo i have exactly the same issue with Mac Mini (Ventura 13.2) and the Apple Touch ID keyboard.

**Comment by Schokobecher** [comment]
It's been over a year by now :(
@fedemkr will this issue we solved together with PR #3415 ?

**Comment by andyfore** [comment]
I am having this issue as well, however my use case is slightly different as I don't use a TouchID keyboard.  I have an original Apple Bluetooth Magic Keyboard, as well as an Apple Watch.  If I start my MacBook Pro in non-clamshell mode and login first, then allow Bitwarden to start before closing the screen we are good because the method used in the code detects the presence of the TouchID keyboard on the laptop.

If I simply start the laptop, then close the lid, the app doesn't know that the TouchID keyboard is present, thus eliminating the ability to unlock via TouchID at all.

**Comment by andyfore** [comment]
Has there been any work on this issue? I am up to date and I still experience the lack of biometric support when my Mac is started in clamshell mode.

**Comment by gergles** [comment]
To be clear, this also occurs in macs not used in clamshell mode, and means that biometrics can't be used after the system is put to sleep by closing the lid, as I reported in #5591. I assume the issues have the same root cause but just wanted to be explicit that clamshell mode isn't a prerequisite for the problem. 

I sitll have the problem in 2023.10.1 and macOS 14.2.

**Comment by djdaveet** [comment]
Can confirm I have the same problem.   Waiting for this to get solved.
