### ISSUE TITLE
Chrome does not redirect to desktop app while SSO login

### ISSUE THREAD

**Issue by Greenderella** [bitwarden/clients#2606]
## Describe the Bug

When you only have Bitwarden's AppImage in your Linux machine, if you click Enterprise Single Sign On your browser opens.

After you authenticate yourself with SSO, if you are using Firefox (Version 88.0.1 in this case) you can **"Choose an application to open the bitwarden link."** and select the AppImage file, and you get correctly redirected to the desktop app (see images _firefox 1_ and _firefox 2_). 

But, if you are using Chrome (Version 90.0.4430.93 in this case), after you authenticate yourself with SSO you can only select the option "Open xdg-open?" and then you get nothing but a blank page stuck at https://bitwarden.yourURL.com/identity/Account/ExternalCallback (see image _chrome_)

## Steps To Reproduce

1. Open Bitwarden's AppImage desktop app
2. Click on Enterprise Single Sign On
3. Chrome should open
4. Authenticate yourself with SSO
5. Click on "Open xdg-open?"
6. Blank page stuck at https://identity.bitwarden.com/identity/Account/ExternalCallback

![SSO jumpcloud](https://user-images.githubusercontent.com/5418577/120519969-8a418e80-c3d3-11eb-916c-0f05febdcd97.gif)

## Expected Result

The browser should redirect back to the desktop app in order to conclude the login process by introducing email + master password.

## Actual Result

A blank page stuck at https://identity.bitwarden.com/identity/Account/ExternalCallback

## Screenshots or Videos

![firefox 1](https://user-images.githubusercontent.com/5418577/120509538-e226c800-c3c8-11eb-809f-cfbd2e2bc864.png)
![firefox 2](https://user-images.githubusercontent.com/5418577/120509542-e3f08b80-c3c8-11eb-83a5-2c1a79047151.png)
![chrome](https://user-images.githubusercontent.com/5418577/120509551-e652e580-c3c8-11eb-80a8-ec873e29a097.png)

## Environment

- Operating system: Ubuntu 20.04.2 LTS
- Browser: Chrome Version 90.0.4430.93
- Installation method: AppImage
- Build Version: 1.26.5
- Self-hosted? Yes

## Additional Context

This [issue](https://github.com/bitwarden/desktop/issues/551) could be related.

The issue is not present with the snap installation.

**Comment by trmnl-cmdr** [comment]
I arrived here after having this same issue with the figma-linux and postman snap packages. It seems to affect all snaps that require redirection to the browser in order to log in.

**Comment by trmnl-cmdr** [comment]
I arrived here after having this same issue with the figma-linux and postman snap packages. It seems to affect all snaps that require redirection to the browser in order to log in.

**Comment by neffets** [comment]
same here. Ubuntu 22.04, chrome is default browser, AppImage in version bin/AppImage/Bitwarden-2022.9.1-x86_64.AppImage

**Comment by neffets** [comment]
Solution:

Create a .desktop file in ~/.local/share/applications
~/.local/share/applications/bitwarden.desktop
<pre>
[Desktop Entry]
Name=Bitwarden
GenericName=Passwortmanager
Exec=$HOME/bin/AppImage/Bitwarden-2022.9.1-x86_64.AppImage --no-sandbox %U
TryExec=$HOME/bin/AppImage/Bitwarden-2022.9.1-x86_64.AppImage
Icon=$HOME/.local/share/icons/hicolor/256x256/apps/bitwarden.png
StartupWMClass=Bitwarden
StartupNotify=true
Terminal=false
Type=Application
Version=1.0
Categories=Utility;Security;Qt;
MimeType=application/x-bitwarden;x-scheme-handler/bitwarden;
X-GNOME-Autostart-enabled=true
X-GNOME-Autostart-Delay=2
X-KDE-autostart-after=panel
X-LXQt-Need-Tray=true
</pre>

Then run
> update-desktop-database ~/.local/share/applications

1) the '%U' in the Exec line solves the problem, that bitwarden opens again and really becomes the sso-url as parameter
2) the update-desktop-database, re-registers the x-scheme protocol handlers

**Comment by laurentvasseurtekos** [comment]
Hello everyone , I faced kind of the same issue with the snap packages on ubuntu 22.04. I fixed the issue by updating my file `/var/lib/snapd/desktop/applications/bitwarden_bitwarden.desktop` like this : 

```
[Desktop Entry]
X-SnapInstanceName=bitwarden
Name=Bitwarden
Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/bitwarden_bitwarden.desktop /snap/bitwarden/current/bitwarden %U
Terminal=false
Type=Application
Icon=/snap/bitwarden/current/meta/gui/icon.png
StartupWMClass=Bitwarden
GenericName=Password Manager
Comment=A secure and free password manager for all of your devices.
Categories=Utility;
```
I hope it will help you :)

**Comment by TheBestPessimist** [comment]
This issue happens on windows as well

**Comment by wrosenauer** [comment]
I used the workaround in https://github.com/bitwarden/clients/issues/2606#issuecomment-1268993899 before successfully a few months ago but I cannot get it to work anymore. Did anything change in the appimage? Or any hints?
The only feedback from calling the appimage with the callback uri seems to be:
(node:8457) DeprecationWarning: file property is deprecated and will be removed in v5.

**Comment by guillemglez** [comment]
Having the same issue for the snap package of Bitwarden

Version 2023.10.1
Shell 25.9.1
Renderer 114.0.5735.289
Node 18.15.0
Architecture x64

**Comment by seanchristians-vention** [comment]
Hi there,

This issue is still happening on Ubuntu with both the AppImage and Snap package.

This is a problem for our org because we use SSO + Trusted Devices and I want my users to be able to register their desktop app to approve login requests.

Bitwarden 2023.10.1
Chrome browser
Ubuntu 22.04

**Comment by lastlockmichael** [comment]
I am also having the same issue. 

Running xdg-open https://identity.bitwarden.com/account/ExternalCallback does not work either.

Ubuntu 22.04.3:LTS

**Comment by seanchristians-vention** [comment]
We're coming up on 3 years with this issue open. Has a fix been roadmapped yet?

**Comment by Felixoid** [comment]
The arch linux package has a [scheme handler](https://gitlab.archlinux.org/archlinux/packaging/packages/bitwarden/-/blob/f658d58eecabe1778ac31dfec31f746439ddffcf/bitwarden.desktop#L7) in its desktop file, and it still doesn't work

I need to open the developer console and copy the `location` header to handle it properly. Opening it as `bitwarden-desktop 'bitwarden://.....'` plays the trick.

**Comment by gjuuz** [comment]
still no solution for chrome running on windows?

**Comment by gjuuz** [comment]
> Hey all, this issue is fixed for both AppImage (for just SSO), and snap (for SSO as well as other protocols). I've linked the changes fixing this.
> 
> [@gjuuz](https://github.com/gjuuz) Seems like an unrelated issue, since this GitHub issue is talking about Linux clients specifically. Please open another ticket to provide details, specifically, if you are using the portable client, or if you have installed this app.

i opened another issue but the issue is exactly the same as described in this report.
