### ISSUE TITLE
Firefox client : can't access property "keys", i is undefined

### ISSUE THREAD

**Issue by homer8173** [bitwarden/clients#4076]
### Steps To Reproduce

1. Go to 'firefox'
2. Click on 'login'
3. On submit, i get this message
![image](https://user-images.githubusercontent.com/8720867/202378781-bd84bf7d-ce9b-46de-b281-ef5cbfc0328e.png)

### Expected Result

login

### Actual Result

auth fail

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/8720867/202379058-fb9c9ca9-46b0-4ce3-8d43-ed36c84bfd57.png)

### Operating System

Windows

### Operating System Version

11

### Shell

PowerShell

### Build Version

2022.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by iivvoo** [comment]
Same here, firefox 107.0 on ubuntu, after entering a valid 2fa code (invalid codes don't trigger the error).
Uninstalling and re-installing the extension doesn't work, but it seems to preserve state (it remembered me), so that might be related.

Not sure how I got the state to clear in the end, once it required me to enter my email address, the problem seems to have resolved itself.

**Comment by rokejulianlockhart** [comment]
Firefox 109.0a1 (2022-12-11) (64-bit), for me.

**Comment by tomershvueli** [comment]
I just came across this bug as well (latest version of Firefox addon on a Mac). 

I was also able to resolve it by 'resetting' the extension entirely. It seems a simple uninstall won't work as some of the settings are saved. I uninstalled the addon, and then quit Firefox entirely. Then reinstalled and was able to login just fine.

**Comment by objecttothis** [comment]
Same issue here on Firefox Developer edition 111.0b6
![image](https://user-images.githubusercontent.com/17935339/221966626-d2760560-f6a7-43be-8e63-25ae64026dd7.png)

**Comment by rokejulianlockhart** [comment]
@tomershvueli, reinstallation is usually enough for me.

**Comment by objecttothis** [comment]
> @tomershvueli, reinstallation is usually enough for me.

Yes, uninstall > close Firefox > open Firefox > reinstall is the **workaround** but it's just a workaround. The issue still needs to be resolved.

**Comment by PlaceboPRS** [comment]
Keep getting this off and on, Firefox 114.0.2 64bit

**Comment by BlueRaja** [comment]
This is happening to me now, so I dug into a bit.  The `i` that is undefined is `account` [here](https://github.com/bitwarden/clients/blob/db2427e05c46c0ba5f77cacebba2c82c7c3b2421/libs/common/src/platform/services/state.service.ts#L529). It seems every time `getAccount` is called, the stacktrace goes into `getAccountFromDisk` and then `this.storageService.get<TAccount>(options.userId, options)`. After that it's hard to me to follow the trace because of the code obfuscation.

**Comment by mibmal** [comment]
I'm getting this on build 116.0.1

**Comment by kit-finknottle** [comment]
Not getting "can't access property keys", but I am getting "i is undefined".

Bitwarden extension Version: 2023.7.1
Firefox version 116.0.3 (64-bit)
MacOS: 12.6.3 (Intel chip)

![bitwarden error](https://github.com/bitwarden/clients/assets/65868822/0ab30044-53a8-45b2-a630-84d697aa06fd)

**Comment by kit-finknottle** [comment]
My error went away after I cleared cache and restarted my browser.

**Comment by lbraglia** [comment]
same here with firefox 102.15.1esr-1~deb12u1, client Version 2023.9.1 on debian stable

no of the above workaround worked for me..

please

**Comment by dicobalt** [comment]
Same "i is undefined" error. Tried uninstalling reinstalling plugin in Firefox, clearing all browser data options for all time, rebooting, removed app based 2fa, can't get Bitwarden plugin to work in Firefox. Bitwarden app works fine in other browsers, the Bitwarden website, and also the Windows Store app.

**Comment by dicobalt** [comment]
Fixed, had to remove Bitwarden from Firefox (not just disable using the slider). reboot then was able to log in normally. Now the fingerprint phrase is correct again.

**Comment by DarkVoyage** [comment]
That login problem in Firefox is a shame! Thanks for advice above, it worked!

**Comment by andmpel** [comment]
How has this been open for a year?

**Comment by garrettw** [comment]
@andmpel because it's still a problem. For me, it fixed itself for a while, but it recently started happening again, which is why I find myself on this page again.

**Comment by andmpel** [comment]
@garrettw that was my point, how has this not been fully fixed though the bug has been known for this long.

**Comment by traveller-kino** [comment]
This is still an issue.
115.7.0esr (64-bit) / W11 Pro

**Comment by sebastianr6** [comment]
I keep running into this issue every few weeks, on multiple machines.

**Comment by 4fd81048-Brian** [comment]
Firefox v 123.0.1 Extension version 2024.2.0 removing and reinstalling extension fixed it.

**Comment by nz2o** [comment]
Still an issue apparently. It's been a while.

**Comment by homer8173** [comment]
Nobody care this issue, maybe they are focus on selling their company ...

**Comment by roblatour** [comment]
I am having this problem too.  Am working with a selfhosted version of Bitwarded.  Chrome extension works fine.  Firefox extension shows this error:

**Comment by trmartin4** [comment]
@roblatour is this consistently reproducible?

If so, could you check the console to get more details on the error that you're seeing?  You should be able to see the console errors by going to `about:debugging` and selecting "This Firefox" and "Inspect" on the Bitwarden extension.

I realize that the full error details were provided earlier, but we have done significant refactoring of the extension and I would like to see where it is causing issues now.

Thank you.

![Image](https://github.com/user-attachments/assets/6b274605-0e0b-4f29-847f-ac6a3c7464d9)

**Comment by roblatour** [comment]
@trmartin4 thanks - i think I found the problem, it was however not too evident from the error messages.

I had my self  hosted set up as http://domainname.com in my Bitwarden settings, it should have been https://domainname.com

**Comment by RokeJulianLockhart** [comment]
> https://github.com/bitwarden/clients/issues/4076#event-16415515680

@trmartin4, https://github.com/bitwarden/clients/issues/4076#issuecomment-2661608051 isn't the sole cause of this, because I haven't ever entered a custom instance URI, yet have experienced this.

**Comment by andmpel** [comment]
I concur with @RokeJulianLockhart this isn't the root issue. I simply switched from firefox as this was too much a of problem. But doesn't fix the problem.
