### ISSUE TITLE
Organization sort order is not alphabetical

### ISSUE THREAD

**Issue by BlackDex** [bitwarden/clients#4263]
### Steps To Reproduce

The sort order of the organizations in the top-left, both web-vault and desktop clients (and probably also mobile) is not alphabetical. The sort-order seems to be linked to the date/time the user is added to that organization.

To reproduce:
1. Create at least 3 new organizations, something like, `A-Business`, `H-Business`, `Z-Business`.
2. Invite a new user to all these organizations, start with `H`, then `Z` then `A`
3. Let that new user accept the invites in the exact same order.
4. Confirm the user in that exact same order.
5. Check the interface, see that the sort order is not alphabetical.

### Expected Result

Organizations are sorted alphabetical.

### Actual Result

Organizations are sorted by creation/joined date it looks like.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/610450/208412610-f2de2960-9208-41a3-b083-da4054fb0b07.png)

### Additional Context

This issue seems to have appeared since v2022.11.x.
It does sort it correctly in v2022.10.x.

### Operating System

Linux

### Web Browser

Chrome, Firefox

### Build Version

v2022.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi @BlackDex 

Thank you for your report. This bug should be fixed on the January release: https://github.com/bitwarden/clients/pull/4015

Let us know if there is anything else we can assist you in the meantime.

**Comment by BlackDex** [comment]
Thanks @Greenderella, not regarding this specific issue no.

**Comment by djsmith85** [comment]
@BlackDex: Closing this now, as it should be solved with the changes made with #4015 which will be available in the 2023.1 release.

Feel free comment if this is still an issue with 2023.1, and we'll re-open.

**Comment by sightkick** [comment]
Today I updated to WebVault 2023.02 and the problem with the unsorted vaults still persists. On Firefox, Chrome, Safari and still in a private window. 
![Xnip2023-03-18_13-45-56](https://user-images.githubusercontent.com/57866026/226114145-700ff4f9-6966-490c-87a2-9f87d7a0a5ab.jpg)

**Comment by BlackDex** [comment]
@djsmith85 , @Greenderella  as @sightkick noted, this isn't fixed  yet in any released version. It is in master though, but nowhere else as far as i can tell.

**Comment by JonTheNiceGuy** [comment]
@djsmith85 Please can this issue be reopened until it is released, so we have some way of tracking this?

**Comment by djsmith85** [comment]
Hi @sightkick, @BlackDex and @JonTheNiceGuy I have passed the feedback onto the team and I'm re-opening this.
