### ISSUE TITLE
Browser extension autofill causes login failure on paypal.com

### ISSUE THREAD

**Issue by TimoHocker** [bitwarden/clients#5915]
### Steps To Reproduce

1. Have a paypal account with active TOTP
2. Go to 'paypal.com'
3. Autofill with CTRL + SHIFT + L
4. Press enter or click on the login button

### Expected Result

Login should be possible with autofill. When copy-pasting each field individually (E-Mail, Password, TOTP Code) the login works fine.
In the past, the password was already filled in the background before the field was visible, so I'm assuming the same happens with the TOTP code since the TOTP autofill feature was added recently.

### Actual Result

Paypal shows an error 'please reenter the code'

### Screenshots or Videos

![Screenshot 2023-07-28 154356](https://github.com/bitwarden/clients/assets/35867059/94fb4ca3-138d-4cd8-a0d9-a1b743d3c956)

### Operating System

Windows

### Operating System Version

10.0.19045

### Web Browser

Firefox

### Browser Version

Developer Edition 116.0b8

### Build Version

2023.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by git-synful** [comment]
+1 on this issue, it has been happening to me as well on Firefox just within the last week.

**Comment by bpsib** [comment]
Same problem here.
![image](https://github.com/bitwarden/clients/assets/5899155/fc5690cd-b3e1-41bd-b553-13905681a69d)

**Comment by atjbramley** [comment]
Hi @TimoHocker, 

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by Stefan1286b** [comment]
I've got the same Problem.
The only way is to disable Bitwarden Plugin to login to Paypal.
![image](https://github.com/bitwarden/clients/assets/31766148/3aac17b3-8c96-4d21-864e-f2e1be1ed36d)
![image](https://github.com/bitwarden/clients/assets/31766148/720b74ff-82ed-41d3-b545-f40de9dd946d)
Problem is  in  Firefox and also in Chrome. Plugin Version 2023.7.0

**Comment by MrPistachios** [comment]
hitting this issue as well, it looks like this issue was fixed in the past but is now back
https://github.com/bitwarden/clients/issues/982

**Comment by jfpaccini** [comment]
+1

**Comment by ErikSlevin** [comment]
Same Here

**Comment by simonz21** [comment]
yup same here on PC & Mac, Chrome and Safari

**Comment by LukeWheeldon** [comment]
Not sure if it's clear for everyone, but an easy bypass is to copy and paste the login and password from Bitwarden (at least for me, on Firefox latest. It's the autofill that breaks the website. Hopefully this gets fixed, but using copy & paste is a lot more convenient than removing the extension altogether.

**Comment by cagonzalezcs** [comment]
@TimoHocker 

Thanks for providing the detailed report for this bug. This issue presents in a similar manner to #5880 and has been resolved with the merge of PR #5700 . The changes from that PR are set to release with `v2023.8`.

The closing comment on #5880 provides more context on why the issue existed and how it was fixed. If you have any further questions, please let me know.

**Comment by bpsib** [comment]
> Not sure if it's clear for everyone, but an easy bypass is to copy and paste the login and password from Bitwarden (at least for me, on Firefox latest). It's the autofill that breaks the website. Hopefully this gets fixed, but using copy & paste is a lot more convenient than removing the extension altogether.

I rather not copy and paste passwords. A workaround I found that works is to remove the Authenticator key from the PayPal Bitwarden item and have it in a separate item entry. I can then use the PayPal item for username and password to autofill then the PayPal authenticator key separate item for copy and pasting the TOTP verification code.

I really think there should be an option in Bitwarden to turn off attempted TOTP auto-filling in certain items to avoid problems like this in the future.

**Comment by tifo71** [comment]
Hello,

Same problem 
![image](https://github.com/bitwarden/clients/assets/130233722/b22d4e0d-1c16-40b1-99bf-dee407b7a061)

Please fix it

**Comment by usommerl** [comment]
I just encountered this issue while using Bitwarden version `2023.12.0`. Manually copying the credentials to the PayPal login form works fine, but it fails in the described manner when I try to use autofill.

**Comment by cagonzalezcs** [comment]
Hmmm, intersting... 

I'm re-opening this ticket and will do some investigation on this. What's weird is the regression happening months after the 2023.8.0 release... 

Regardless, going to dig into why this is happening when possible.

**Comment by TimoHocker** [comment]
Can confirm, this is happening again. The automatic TOTP filling is also active again, which probably causes this issue.
I would love to have automatic TOTP filling on most services, especially my teleport instance where I would have to click on the code field and then paste without the feature. But on Paypal it needs to be delayed or pointed at the correct field.

**Comment by bpsib** [comment]
Automatic TOTP filling should be an optional feature that is disabled by default for PayPal. It should not be forced upon us.

**Comment by koitsu** [comment]
> Can confirm, this is happening again. The automatic TOTP filling is also active again, which probably causes this issue. I would love to have automatic TOTP filling on most services, especially my teleport instance where I would have to click on the code field and then paste without the feature. But on Paypal it needs to be delayed or pointed at the correct field.

Can confirm this is happening to me as well.  It's my first time encountering it.  Additionally, I have "Auto-fill on page load" DISABLED (and have since day one) yet I see this problem.  I also use "Starts with" for "Default URI match detection" for a lot of very good/justified reasons, but I don't think this is relevant to the issue either.

The only workaround I've found, when experiencing it, is to go Back in the browser, then once again confirm/click whatever takes you to PayPal, then **manually** enter data into each of the fields (login, password, TOTP).  At any point using BitWarden to auto-fill any of those 3 fields results in various errors (the most famous being the "failed captcha" error, but you tend to get a different error during the TOTP phase).

If BitWarden devs need a guinea pig to test or analyse this problem, I'm game.  Just let me know what's needed.

**Comment by bpsib** [comment]
@koitsu I have a much better workaround that I have mentioned before but I will mention it again

The workaround I use is to clone the PayPal login in Bitwarden and then delete the authenticator key from the clone. I then use the cloned version of the login for PayPal and then copy the TOTP code from the original when it asks for it,

**Comment by koitsu** [comment]
> @koitsu I have a much better workaround that I have mentioned before but I will mention it again
> 
> The workaround I use is to clone the PayPal login in Bitwarden and then delete the authenticator key from the clone. I then use the cloned version of the login for PayPal and then copy the TOTP code from the original when it asks for it,

Can you explain how this works around whatever the problem is?  Effectively you're describing requiring **two** BitWarden vault entries for PayPal -- one used for the L/P information, the other used for the TOTP authenticator key (or more precisely the one-time code).  Is the bug in the browser plugin actually understood at this point, or are people just guessing + coming up with random "solutions"?

**Comment by bpsib** [comment]
It's because the last update activates TOTP auto-filling. The problem is that Bitwarden fills in a hidden field that it thinks is the TOTP field but is actually a captcha field.

**Comment by koitsu** [comment]
> It's because the last update activates TOTP auto-filling. The problem is that Bitwarden fills in a hidden field that it thinks is the TOTP field but is actually a captcha field.

Is that behaviour not controlled via the "Auto-fill on page load" feature?  Quoting myself: "Additionally, I have "Auto-fill on page load" DISABLED (and have since day one) yet I see this problem."

![screenshot](https://github.com/bitwarden/clients/assets/8430773/f18e1642-f589-47b3-861f-511803825b3d)

**Comment by slovia** [comment]
Hello lovely people,
The workaround by bpsib "solves" the problem for me too. I cloned the Paypal entry in Bitwarden, named the clone "... without TOTP" and deleted the TOTP field. Now this entry has only UN and PW. I use it to fill those fields via keyboard shortcut. Then for TOTP I use the "old" Paypal entry (which still has UN, PW and TOTP - and can be used again when the problem is fixed for good) to fill that field. Works but is not elegant at all ;-)
It seems that the problem is that Bitwarden tries to fill some additional field with the TOTP data. This happens with auto-fill or with any other "automatic" method. But not by copy-pasting the UN. That's why disabling autofill is the solution ONLY if you copy-paste but not when you use a keyboard shortcut or the entry in the context menu.
At least that's my understanding ;-)
Hope I didn't add more confusion to this.
And I hope a real solution will be available soon!

**Comment by slovia** [comment]
In case this is of any significance to anyone....
The described problem does not occur on a Japanese Paypal login page. I just bought something from ototoy, was sent to the Paypal login screen (which is in Japanese) and had no problem auto-filling UN, PW and TOTP.
This can actually easily be recreated. Go to https://www.paypal.com/jp/home, choose the login button (of the two buttons with rounded corners it is the white one reading ログイン) and then chose English and it won't work ("Enter code again"), switch to Japanese and with nothing else changed it will work with no problem.

**Comment by terryn-aie** [comment]
> Is that behaviour not controlled via the "Auto-fill on page load" feature? Quoting myself: "Additionally, I have "Auto-fill on page load" DISABLED (and have since day one) yet I see this problem."

If I understand correctly, the "Auto-fill on page load" explicitly does _not_ govern that setting, per the [help pages for Bitwarden](https://bitwarden.com/help/auto-fill-browser/#totp-auto-fill). Here's a quote from the relevant section (emphasis as quoted):

> Browser extensions **will not auto-fill your TOTP code if you're using auto-fill on page load**.

It does offer a tip that the "Automatic TOTP copying" can be turned off, but I haven't yet checked whether that also affects the TOTP auto-fill or not.

**Comment by terrehbyte** [comment]
> Is that behaviour not controlled via the "Auto-fill on page load" feature? Quoting myself: "Additionally, I have "Auto-fill on page load" DISABLED (and have since day one) yet I see this problem."

@koitsu, if I understand correctly, the "Auto-fill on page load" explicitly does not govern that setting, per the [help pages for Bitwarden](https://bitwarden.com/help/auto-fill-browser/#totp-auto-fill). Here's a quote from the relevant section (emphasis as quoted):

> Browser extensions **will not auto-fill your TOTP code if you're using auto-fill on page load**.

It does offer a tip that the "Automatic TOTP copying" can be turned off, but I haven't yet checked whether that also affects the TOTP auto-fill or not.

(Note: Sorry for the double notification - posted it from the wrong browser under the wrong account.)

**Comment by Mozoloa** [comment]
Same problem, it seems that it started recently, could be wrong, but it's definitely there

**Comment by jprusik** [comment]
I’m able to consistently reproduce the issue with the current production version of the extension (2023.12.1) on both [paypal.com](http://paypal.com/) and [sandbox.paypal.com](http://sandbox.paypal.com/):

![Screenshot 2024-01-03 at 5 03 39 PM](https://github.com/bitwarden/clients/assets/1556494/8d13aef5-a7a5-4ee0-9977-cc6ccbc4fa13)

However, when I test against a fresh build of the extension, I can not reproduce the issue on either, so this should be resolved with the next release.

Closing the issue for now; can revisit after release if the issue persists.

**Comment by Floyd-Schramm** [comment]
I am still having the same issue with the new release (2023.12.1). I tried removing and adding back the extension, but it did not help.

![PayPal Error](https://github.com/bitwarden/clients/assets/29488767/5dbd1290-2ff6-46c0-81f6-47e966616532)

![Screenshot 2024-01-06 161718](https://github.com/bitwarden/clients/assets/29488767/e717e1ee-c038-4115-ae1d-b143dbbfd810)

**Comment by koitsu** [comment]
2023.12.1 is not the version which should fix this.  Going purely off of what @jprusik said, the **next** release -- i.e. AFTER 2023.12.1 -- is the one which should fix it.

**Comment by Floyd-Schramm** [comment]
My bad, then I am back to patiently waiting for the new production version 😄

**Comment by jprusik** [comment]
> the next release -- i.e. AFTER 2023.12.1 -- is the one which should fix it.

This is correct; apologies if that wasn't clear.

**Comment by koitsu** [comment]
> My bad, then I am back to patiently waiting for the new production version 😄

FYI: 2024.1.0 is available now, give it a shot.

**Comment by Floyd-Schramm** [comment]
> FYI: 2024.1.0 is available now, give it a shot.
Yea, thanks for the update. Now it works perfectly again!

While testing, I found another bug, maybe not related to this one tough?
When using the new button for selecting which account info to fill in, the automatically copied OTP is for the wrong account.
Let's say I used Bitwarden to log into account A the last time I opened PayPal. When I now open PayPal, the account A info will be filled out. After selecting account B via the dropdown, as shown below, it correctly fills out the email address and password but copies the OTP for account A.
However, I did not encounter this issue when opening the Bitwarden extension and selecting account B there.
![image](https://github.com/bitwarden/clients/assets/29488767/ae2138c2-0178-4c71-96e6-762519d2ae08)

**Comment by wesleycoder** [comment]
I've just stumbled on this for the first time, and I'm wondering why this issue is closed, I think this should be reopened.
I have Autofill enabled on page load.
![image](https://github.com/bitwarden/clients/assets/22945955/773b2675-2fe7-4f5e-9e02-f780ddfc09d0)

If you all need more info or more testing I can put some time to help.
I appreciate all the effort :)

**Comment by wesleycoder** [comment]
Maybe @jprusik has context to look into this one more time?
Happy to help in any way I can

**Comment by jprusik** [comment]
I was also able to repro on 2024.1.1; will look into it

**Comment by CodingMarkus** [comment]
Is PayPal maybe doing that intentionally to break password managers? After all this issue was fixed on Aug 16, 2023 and now it is back for the second time within a single year. Is auto filling maybe violating their AUP? Or do they want to force users to always provide the OTP code in a separate step? I'd be fine to click Bitwarden 3 times and have it fill in one field after another, as long as that prevents that issue from happening again in the future.

**Comment by jprusik** [comment]
Paypal is a high value target, so I imagine automated attacks are something they need to mitigate regularly. Speculatively speaking, I'm guessing that is their primary concern in regards to login behaviors.

In any case, we have a fix merged in for this issue which should go out with the next release!

**Comment by bin101** [comment]
@jprusik I can reproduce it now again with 2024.1.1

**Comment by jprusik** [comment]
> I can reproduce it now again with 2024.1.1

The fix was not included in the 2024.1.1 patch release, but is still part of `main`. We should expect to see it in the next minor release (I will verify with our team internally).

**Comment by danielpsf-grover** [comment]
>The fix was not included in the 2024.1.1 patch release, but is still part of main. We should expect to see it in the next minor release (I will verify with our team internally edit: It is currently included in the Release Candidate for the v2024.2.0 release).

I can confirm it works on the `2024.2.0`, but only up to the TOTP. When it inserts the MFA code it returns all the numbers back to 0 and fails.

**Comment by jprusik** [comment]
> When it inserts the MFA code it returns all the numbers back to 0 and fails.

This is a separate/unrelated issue which we're tracking internally around Paypal's use of a input-per-character pattern for the totp entry.
