### ISSUE TITLE
Vault timeout action changes to "Lock" despite being set to "Log out"

### ISSUE THREAD

**Issue by rj667** [bitwarden/clients#6430]
### Steps To Reproduce

1. Go to 'Settings' in the browser plugin
2. Click on 'Vault timeout action', change to 'Log out' and confirm if asked.
3. Click on 'Settings' twice. After the second time, the timeout action changes back to 'Lock'
Even if you don't do step 3, after a while the timeout action has changed to "Lock" which is noticeable because the plugin doesn't ask for the 2nd factor (I have 2FA enabled) and unlocks with just my password.
This behavior is new since a month or two. Before that it would really log me out after my custom vault timeout of 12h.

### Expected Result

I would expect the 'Vault timeout action' to stay on whatever I set it to, in this case to 'Log out'

### Actual Result

The value of 'Vault timeout action' changes back to 'Lock'. It does that over time or after selecting 'Settings' twice.

### Operating System

Windows

### Operating System Version

Windows 10 and 11

### Web Browser

Microsoft Edge

### Browser Version

I see it on Edge and Edge for Business, and Chrome, all latest version.

### Build Version

Version 117.0.2045.36 (Official build) (64-bit)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by insurw** [comment]
OT but how do updates like to happen? Don't BW devs do _basic app testing_ before pushing an update?
Same thing a while ago when in the Android app you couldn't paste 2fa codes into the app.

**Comment by SergeantConfused** [comment]
Hi @rj667,

Thank you for your report. I was able to reproduce this behaviour and I have flagged it to our Engineering team.

If you wish to add any further information, such as screenshots or screen recordings, please feel free to do so at any time - our Engineering team will be happy to review them.

Thank you again,

**Comment by agreenbhm** [comment]
I know saying "me too" isn't helpful, but I wanted to stress the importance of this issue being resolved as I just noticed it happening to me as well which means I was running a lower-security setup for the past 2 weeks without realizing it.

**Comment by jcglza** [comment]
@agreenbhm Chiming in just like you to emphasize that for users like me with a Yubikey, I prefer to make the Yubikey challenge every day instead of just imputing the master password. It would be very appreciated if this bug is fixed.

**Comment by yRob69** [comment]
I confirmed the same issue with Brave and Firefox as well, on three different systems.
Brave Extension ver - 2023.9.1
Firefox Extension ver - 2023.9.1

**Comment by bibsen** [comment]
Same here...
This serious bug should be fixed immediately

Is it possible to roll back to a secure version of the plugin while waiting for a fix ?

**Comment by jcglza** [comment]
@bibsen I would rather manually log out until the bug is fixed as opposed to playing with older versions, but that's just my opinion.

**Comment by jcglza** [comment]
I found a quick way to produce the bug, if it helps in anything to the developers.

https://github.com/bitwarden/clients/assets/42979427/16a4c15f-3bf5-4f60-8999-8b9059c1c942

**Comment by agreenbhm** [comment]
Just updated to the latest release (2023.10.0) and it appears that the issue is resolved.

**Comment by rj667** [comment]
Confirmed, the timeout action keeps it value of "log out", and after the vault timeout the session is indeed logged out.
Thank you!

**Comment by jcglza** [comment]
Hasn't been fixed on Firefox :( I assume it's coming soon.

**Comment by CarlosJoseChaconChavarria** [comment]
working for android, I just had to enabled auto fill back on, it was off

**Comment by t-hg** [comment]
Using Bitwarden on my Linux Desktop:

Version 2024.3.0
Shell 28.2.4
Renderer 120.0.6099.291
Node 18.18.2
Architecture x64

I can confirm that is still an issue. Further, the problem exists not only for the "Vault timeout action" but also for the "Vault timeout". No matter what value I set (e.g. "30 seconds"), it will reset to "On restart"

**Comment by Erz3** [comment]
Same with flatpak version 2024.3.0

**Comment by trmartin4** [comment]
@Erz3 @t-hg can you confirm whether this is still occurring with the latest desktop version?  We addressed some issues with saving settings on Linux in the `2024.4.1` release.

**Comment by t-hg** [comment]
Hi @trmartin4,
For my experience I can confirm that the issue has been addressed and is fixed now.
Thank you.

**Comment by trmartin4** [comment]
Thank you for the feedback.  I am going to close this issue as resolved.  If the issue recurs please feel free to re-open or create a new issue.
