### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by okarmusk** [bitwarden/clients#8175]
### Steps To Reproduce

1. Install Bitwarden via snap on Ubuntu 23.10 or upgrade already installed version to `2024.2.0`
2. Try to run it

### Expected Result

Desktop client starts normally.

### Actual Result

Desktop client is unable to start properly.

Console log when trying to run Bitwarden from terminal:
```
~$ bitwarden 
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Conf._deserialize (/snap/bitwarden/104/resources/app.asar/main.js:6657:43)
    at get store [as store] (/snap/bitwarden/104/resources/app.asar/main.js:6868:43)
    at new Conf (/snap/bitwarden/104/resources/app.asar/main.js:6721:32)
    at new ElectronStore (/snap/bitwarden/104/resources/app.asar/main.js:11083:3)
    at new ElectronStorageService (/snap/bitwarden/104/resources/app.asar/main.js:56338:22)
    at new Main (/snap/bitwarden/104/resources/app.asar/main.js:56825:31)
    at 64164 (/snap/bitwarden/104/resources/app.asar/main.js:45181:18)
    at __webpack_require__ (/snap/bitwarden/104/resources/app.asar/main.js:60701:42)
    at /snap/bitwarden/104/resources/app.asar/main.js:60757:37

(bitwarden:7105): Gtk-WARNING **: 22:26:26.703: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name

(bitwarden:7105): Gtk-WARNING **: 22:26:26.705: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name

(bitwarden:7105): Gtk-WARNING **: 22:26:26.706: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name

(bitwarden:7105): Gtk-WARNING **: 22:26:26.759: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name

(bitwarden:7105): Gtk-WARNING **: 22:26:26.761: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name

(bitwarden:7105): Gtk-WARNING **: 22:26:26.762: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name
Driver does not support the 0x46a8 PCI ID.
libGL error: failed to create dri screen
libGL error: failed to load driver: iris
[7188:0302/222626.801071:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
Driver does not support the 0x46a8 PCI ID.
Warning: vkCreateInstance: Found no drivers!
Warning: vkCreateInstance failed with VK_ERROR_INCOMPATIBLE_DRIVER
    at CheckVkSuccessImpl (../../third_party/dawn/src/dawn/native/vulkan/VulkanError.cpp:101)
    at CreateVkInstance (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:493)
    at Initialize (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:379)
    at Create (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:301)
    at operator() (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:556)
```

### Operating System

Linux

### Operating System Version

Ubuntu 23.10

### Installation method

Snap

### Build Version

2024.2.0

### Issue Tracking Info

- [x] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @okarmusk,

Thank you for this report. I was unable to reproduce this behaviour in testing, and I've escalated this for further investigation; If you have more information that you think may help us, please feel free to add it below. 

In the meantime, could you please clarify the following?
1. What CPU and GPU are you using?
2. Is this a physical machine or a VM? 
3. Does the .AppImage release work as expected on that same machine?


Thank you,

**Comment by hvisage** [comment]
hit the "exact" same one before (on macOS) and now I have it again, using the official Apple Store package, yes, removed and installed again, so it's some other user data that is corrupted (and here I will use the word corrupted as in killing power on the computer when earth leakage tripped in the house)

```
Uncaught Exception:
SyntaxError: Unexpected token '', "N^�"... is not valid JSON
at JSON.parse (<anonymous>)
at Conf._deserialize (/Applications/Bitwarden.app/Contents/Resources/app.asar/main.js:10084:43)
at get store [as store] (/Applications/Bitwarden.app/Contents/Resources/app.asar/main.js:10295:43)
at new Conf (/Applications/Bitwarden.app/Contents/Resources/app.asar/main.js:10148:32)
at new ElectronStore (/Applications/Bitwarden.app/Contents/Resources/app.asar/main.js:14523:3)
at new ElectronStorageService (/Applications/Bitwarden.app/Contents/Resources/app.asar/main.js:93011:22)
at new Main (/Applications/Bitwarden.app/Contents/Resources/app.asar/main.js:93603:31)
at 64164 (/Applications/Bitwarden.app/Contents/Resources/app.asar/main.js:75972:18)
at __webpack_require__ (/Applications/Bitwarden.app/Contents/Resources/app.asar/main.js:97497:42)
at /Applications/Bitwarden.app/Contents/Resources/app.asar/main.js:97553:37
```

**Comment by hvisage** [comment]
so my question related to this: Which file to be removed to fix?

**Comment by jamesonhacking** [comment]
Same problem here on Kubuntu 22.04.3 LTS. Tried Bitwarden-2024.4.3-x86_64.AppImage and older versions to no avail. Please fix.

A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unterminated string in JSON at position 1028096 (line 23320 column 74)
at JSON.parse ()
at Conf._deserialize (/tmp/.mount_BitwarxT5YbM/resources/app.asar/main.js:8930:43)
at get store [as store] (/tmp/.mount_BitwarxT5YbM/resources/app.asar/main.js:9141:43)
at new Conf (/tmp/.mount_BitwarxT5YbM/resources/app.asar/main.js:8994:32)
at new ElectronStore (/tmp/.mount_BitwarxT5YbM/resources/app.asar/main.js:13369:3)
at new ElectronStorageService (/tmp/.mount_BitwarxT5YbM/resources/app.asar/main.js:92221:22)
at new Main (/tmp/.mount_BitwarxT5YbM/resources/app.asar/main.js:92847:31)
at 64164 (/tmp/.mount_BitwarxT5YbM/resources/app.asar/main.js:75981:18)
at __webpack_require__ (/tmp/.mount_BitwarxT5YbM/resources/app.asar/main.js:96754:42)
at /tmp/.mount_BitwarxT5YbM/resources/app.asar/main.js:96810:37

**Comment by jamesonhacking** [comment]
Actually, I just fixed the problem using this:

`mv ~/.config/Bitwarden ~/.config/Bitwarden.old`

Now Bitwarden opens normally.

**Comment by thegrandpoobah** [comment]
In case you are like me and wondering where the data is located in various OSes, there is a useful article here: https://bitwarden.com/help/data-storage/

In my case, my `data.json` file was completely blank (~/snap/bitwarden/current/.config/Bitwarden). deleted that file and Bitwarden opened fine, but had lost all the different accounts I had setup.

no reason i can think of why this file was corrupted, but here we are.

**Comment by trmartin4** [comment]
@okarmusk are you still experiencing this issue?  If this has been resolved with a subsequent release of the application we'd like to close the ticket.

Thank you.

**Comment by james9001** [comment]
> Actually, I just fixed the problem using this:
> 
> `mv ~/.config/Bitwarden ~/.config/Bitwarden.old`
> 
> Now Bitwarden opens normally.

Thank you, this worked for me. (was attempting to run the 2024.10.2 AppImage)

**Comment by mhzawadi** [comment]
I have this issue, just installed 2025.1.0 (36032) and now get the below error.

I have removed the app and reinstalled, deleted `~/Library/Containers/com.bitwarden.desktop/Data/Library/Application Support/Bitwarden` and both still get the error below

I have a Macbook Pro 15-inch 2017 running MacOS 13.7.2, Apple app store install of the app

```
Uncaught Exception:
Error: dlopen(/Applications/Bitwarden.app/Contents/Resources/app.asar.unpacked/node_modules/@bitwarden/desktop-napi/desktop_napi.darwin-x64.node, 0x0001): symbol not found in flat namespace '_OBJC_CLASS_$_ASPasskeyCredentialIdentity'
at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
at Module._extensions..node (node:internal/modules/cjs/loader:1602:18)
at Object.func [as .node] (node:electron/js2c/node_init:2:2786)
at Module.load (node:internal/modules/cjs/loader:1295:32)
at Module._load (node:internal/modules/cjs/loader:1111:12)
at c._load (node:electron/js2c/node_init:2:16955)
at Module.require (node:internal/modules/cjs/loader:1318:19)
at require (node:internal/modules/helpers:179:18)
at Object.<anonymous> (/Applications/Bitwarden.app/Contents/Resources/app.asar/node_modules/@bitwarden/desktop-napi/index.js:109:29)
at Module._compile (node:internal/modules/cjs/loader:1484:14)
```
