### ISSUE TITLE
Safari Version 15.6.1 (macOS Catalina) extension won't work with latest update 2024.3.0

### ISSUE THREAD

**Issue by greymda** [bitwarden/clients#8348]
### Steps To Reproduce

1. Go to 'Safari on macOS Catalina'
2. Click on 'Bitwarden extension in Safari'

### Expected Result

Bitwarden extension loads up and can fill in or search within vault.

### Actual Result

White page loading, nothing happens.
<img width="548" alt="Screenshot 2024-03-15 at 15 02 01" src="https://github.com/bitwarden/clients/assets/9991596/226ff21c-f172-4c73-a470-7c4cdc9f74bc">

### Screenshots or Videos

<img width="548" alt="Screenshot 2024-03-15 at 15 02 01" src="https://github.com/bitwarden/clients/assets/9991596/b2da07e9-7e24-4018-aaf1-66f5b47ad366">

### Operating System

macOS

### Operating System Version

Catalina 

### Web Browser

Safari

### Build Version

15.6.1 (15613.3.9.1.16, 15613)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Gertcha** [comment]
I concur, same for me.

macOS Catalina 10.15.7
Safari 15.16.1
Bitwarden 2024.3.0 (21897)

When clicking on the extension in Safari, unable to login and use.

In addition, may or may not be related but when quitting the main Bitwarden app also get the following error each time:
![Screenshot 2024-04-01 at 08 08 59](https://github.com/bitwarden/clients/assets/12471825/3adb4096-dabb-4c0e-95f2-1252a3aab1bb)

**Comment by Gertcha** [comment]
Same issue is mentioned here: https://github.com/bitwarden/clients/issues/8339

**Comment by gusklein** [comment]
same error, same symptoms here.

**Comment by GaffelWiess** [comment]
I'm experiencing the same issue as listed above from greymda. Extension not loading 
![Screen Shot 2024-04-05 at 10 47 40](https://github.com/bitwarden/clients/assets/163954152/941cd675-3daa-4133-aeef-e16ff3f6b184)

**Comment by SergeantConfused** [comment]
Hello everyone,

Thank you all for your input. The Engineering department has been looking into this matter internally; This GitHub report will remain open for external tracking purposes for the time being.

I thank you in advance for your understanding and patience,

**Comment by zutz** [comment]
also have an issue with using latest update on macOS Catalina 10.15.7 on my rebuilt 2012 macbook pro and web browser latest chrome version
the automatic update on app store did not download and attempts to do it manually did not work.  i sent an issue report to bidwarden and was told to delete and reinstall the app 
but since its working right now and i see so many complaints from folks  using macOS Catalina 10.15.7 who did install update and ran into a lot of problems --- i decided wont update til i see some resolution.

**Comment by hpeyerl** [comment]
Happened to my wife as well.   Not helping the sales pitch for password managers and sticky notes might be making a comeback.  :-(

**Comment by 2ndMessiah** [comment]
![image](https://github.com/bitwarden/clients/assets/22229188/08fdc8c8-129e-4947-ac3b-765ec328e907)
Happening to me too. Catalina, Safari15.6.1

**Comment by snelling-a** [comment]
experiencing something similar. opened safari today and the extension was not on the list of extensions.

Safari: Release 192 (Safari 17.4, WebKit 19619.1.8.1)
Bitwarden: Version 2024.4.1 (23269)

**Comment by zutz** [comment]
same issue
Can’t open on safari at all

**Comment by dnisbetjones** [comment]
Can confirm this issue.

Catalina 10.15.7
Safari 15.6.1
Bitwarden 2024.4.1

**Comment by swilkins1337** [comment]
Not a single mention of this despite the age of this issue, but I can confirm the Web Vault doesn't load for me in Safari 15.6.1. I thought that might be useful information.

**Comment by zutz** [comment]
same 😔

**Comment by TheoCaparros** [comment]
Still loading the page for hours :/

**Comment by superfreeman1989** [comment]
Same problem in Sonoma

**Comment by terrywebbs** [comment]
> Not a single mention of this despite the age of this issue, but I can confirm the Web Vault doesn't load for me in Safari 15.6.1. I thought that might be useful information.

Interesting we got a mention in this thread here a month back: https://github.com/bitwarden/clients/issues/8339#issuecomment-2041519877 but I can't find anywhere that these issues raised in the current thread are being addressed?

**Comment by tdbear** [comment]
Mac OS 14.4.1, Safari 17.4.1, Bitwarden 2024.4.1 - same problem except I don't even get a spinner. Most of the times I get  tiny window/popup, sometimes a regular size window/popup.
<img width="104" alt="Screenshot 2024-05-18 at 20 29 02" src="https://github.com/bitwarden/clients/assets/79653/546e6243-5198-43ed-aea6-e6bb31327e30">

**Comment by CrayCJ** [comment]
Ok, I cannot wait any longer, I downgraded.

**Here's how to downgrade to an earlier version of Bitwarden (at your own risk):**

1. Open **Apple's App Store** on your Mac > menu bar: "App Store" > "Preferences" > **untick automatic updates**.
App Store can be closed now.

- _Comment: Unticking this will prevent App Store from updating any of your app automatically, so this is your job from now on, sorry - this is good practice anyway as seen with this app... With this ticked, App Store updates any earlier version of Bitwarden you install intermediately, defeating the purpose._

2. Open your **Applications folder** (or where Bitwarden is installed) and **drag the Bitwarden App to the Trash**, thereby deleting your currently installed version of Bitwarden.

- _Comment: It should not be necessary to delete any further files, e.g. in ~/Library, etc. (like with [App Zapper](https://www.appzapper.com) or similar). **Do not uninstall the Bitwarden Safari Browser Extension** (in Safari > Preferences > Extensions) - for me uninstalling this lead to weird behaviour: Safari did at first not show the Extension of the in step 3 installed earlier Version of Bitwarden, it appeared suddenly after some time, though?!_

3. Go to https://github.com/bitwarden/clients/releases and **download an earlier version of the _Desktop_ version of Bitwarden** of your choosing. I went with [Desktop v2023.12.1](https://github.com/bitwarden/clients/releases/tag/desktop-v2023.12.1) as I remembered it working last year. Maybe a newer version might also work. Download the **universal.dmg** (or .zip) there (for me that was: [Bitwarden-2023.12.1-universal.dmg](https://github.com/bitwarden/clients/releases/download/desktop-v2023.12.1/Bitwarden-2023.12.1-universal.dmg)). **Open the .dmg (or .zip) and drag the Bitwarden app to your Applications folder**.

- _Comment: The above mentioned version **did not allow me to logout within the Safari extension**. I was therefore unable to enter the correct login email. I was able to fix this by repeating step 2 and 3 with an even earlier version ([Bitwarden-2023.5.1-universal.dmg](https://github.com/bitwarden/clients/releases/download/desktop-v2023.5.1/Bitwarden-2023.5.1-universal.dmg)). Within that, I was able to logout in Safari, enter the correct info and enter my vault. Then I repeated step 2 and 3 once more and installed [Bitwarden-2023.12.1-universal.dmg](https://github.com/bitwarden/clients/releases/download/desktop-v2023.12.1/Bitwarden-2023.12.1-universal.dmg) mentioned above._

4. Now, your Safari Extension should work again. **It is possible that you need to allow unsigned extensions in the developer menu of Safari** (> menu bar: "Preferences" > "Advanced" > tick "show developer menu"; then menu bar: "Developer" > "allow unsigned extensions", second from bottom) for the extension to show up. You might have to re-allow this every time Safari is started! The first time, you might also have to restart Safari and/or untick and retick the Bitwarden extension in Safari > menu bar: "Preferences" > "Extensions"...


For me, this workaround worked, but I still would prefer this issue to be resolved...
Cheers! :)

**Comment by hpeyerl** [comment]
> Interesting we got a mention in this thread here a month back: [#8339 (comment)](https://github.com/bitwarden/clients/issues/8339#issuecomment-2041519877) but I can't find anywhere that these issues raised in the current thread are being addressed? Have they abandoned legacy systems?

Not even Legacy systems.  There are commenters in this issue who are on current versions of MacOS and Safari and are experiencing the problem.  However, the comment you refer to mentions 'legacy systems' so I think Bitwarden has decided to abandon this bug.   Since it's tracked internally, we'll never really know but given the age of this issue, it's probably a safe bet that Safari+Bitwarden is a dead end.

**Comment by tdbear** [comment]
My problem was fixed after I unchecked "Unlock with touch ID" in the settings of Bitwarden desktop. Obviously I lots the Touch ID unlock but it works for me again now. Maybe the hangup on launch is related to accessing keychain?

**Comment by swilkins1337** [comment]
> My problem was fixed after I unchecked "Unlock with touch ID" in the settings of Bitwarden desktop. Obviously I lots the Touch ID unlock but the extension works for me again now. Maybe the hangup on launch is related to accessing keychain?

My Mac doesn't even have Touch ID, so I don't think that option would be there.

**Comment by terrywebbs** [comment]
> My problem was fixed after I unchecked "Unlock with touch ID" in the settings of Bitwarden desktop. Obviously I lots the Touch ID unlock but the extension works for me again now. Maybe the hangup on launch is related to accessing keychain?

No option to do that on my desktop version - I don't even have keychain enabled!

**Comment by atoussama** [comment]
between this issue not being solved on my Mac, and the iOS app also not bringing up logins for about two weeks now, I think it's time to stop recommending this app to anyone, and maybe look for alternatives.

**Comment by superfreeman1989** [comment]
As I noted above the app on safari is not locking properly as it’s still showing the red badge of number after the set time to lock, just won’t show the app interface when clicking on the icon. 

These small shops are just unreliable. Probably just one guy running the entire app in his bedroom. I’m moving to iCloud keychain.

**Comment by trmartin4** [comment]
Hello, 

I wanted to update that we are working on a potential resolution to this now.  We are confident that this was introduced with our latest Angular version update across our clients, and we are introducing additional polyfills for backward compatibility to attempt to address the issues occurring on older MacOS versions with this update.  We do need to maintain current Angular versions for a variety of reasons, and so we cannot revert this change.

**Comment by superfreeman1989** [comment]
> older MacOS versions

I'm on latest Sonoma.

**Comment by swilkins1337** [comment]
I'd have been fine with a version that works, even if it doesn't support the newest features, but I suppose they wouldn't want to maintain two different versions. Even if one is security fixes only.

**Comment by 2ndMessiah** [comment]
Just roll back to an earlier released version as aforementioned

Sam Wilkins ***@***.***>于2024年5月26日 周日11:07写道：

**Comment by terrywebbs** [comment]
@superfreeman1989 I am sure they will figure this one out too!

@CrayCJ Did you ever consider using Time Machine to roll back to an earlier version of the BitWarden APP?

I haven't tried this myself, but after some research in to restoring apps with Time Machine on the mac system, I thought logically they must be a way to combine this use to fix our issue.
https://apple.stackexchange.com/questions/300942/how-to-disable-updates-for-specific-app-in-mac-app-store

1. Open Apple's App Store on your Mac > menu bar: "App Store" > "Preferences" > untick automatic updates.
NOW it's IMPORTANT to mention you'll still need to update your core apps manually.

2. Open the APPLICATIONS folder, click the Time Machine icon and Enter Time Machine, find the Bitwarden app in a previous time and restore. 

3. Now you will need to restore any support library files for Bitwarden only from ~/Library/Application Support and ~/Library/Preferneces. NOT the complete path just the Bitwarden folders!

4. Enjoy

**Comment by terrywebbs** [comment]
> Vault
Version 15.6.1 (15613.3.9.1.16, 15613)
![bitwarden3](https://github.com/bitwarden/clients/assets/91281946/a28a1760-8b04-4565-8308-fc4efa58d7ea)

**Comment by swilkins1337** [comment]
> Just roll back to an earlier released version as aforementioned

Still wouldn't fix the Web Vault, which I have needed on some occasions.

**Comment by terrywebbs** [comment]
> > Just roll back to an earlier released version as aforementioned
> 
> Still wouldn't fix the Web Vault, which I have needed on some occasions.

Maybe it we also roll back safari to an earlier version - that might fix the vault?

**Comment by terrywebbs** [comment]
Still broken with latest Version 2024.5.0 (24604)

**Comment by swilkins1337** [comment]
> > > Just roll back to an earlier released version as aforementioned
> > 
> > 
> > Still wouldn't fix the Web Vault, which I have needed on some occasions.
> 
> Maybe if we also roll back safari to an earlier version - that might fix the vault?

I think the vault and extension are using stuff not properly implemented in Safari 15, so rolling back would make things worse.

**Comment by swilkins1337** [comment]
> Still broken with latest Version 2024.5.0 (24604)

"Bug fixes" Not the one that matters the most apparently.

**Comment by terrywebbs** [comment]
It's all broken now, no more updates for older macs as of 2024.5.0  Newer versions wont run on older macs.

So I uninstalled everything including the safari plugin and all references of Bitwarden. Then restored a known working copy from the Time Machine Backup.

1. Open Apple's App Store on your Mac > menu bar: "App Store" > "Preferences" > untick automatic updates.
NOW it's IMPORTANT to mention you'll still need to update your core apps manually, as and when they appear!

2. Within Safari Untick the safari Bitwarden extension and then uninstall the Bitwarden app (good idea to use an uninstall app to do this so you get all the Bitwarden files and folders, I use AppCleaner. 

4. Open the APPLICATIONS folder, click the Time Machine icon and Enter Time Machine, goto February 2024 (this is the last time it work in older Macs, since March it has failed miserably) find the Bitwarden app and restore.

5. Enjoy

**Comment by swilkins1337** [comment]
> Hello,
> 
> I wanted to update that we are working on a potential resolution to this now. We are confident that this was introduced with our latest Angular version update across our clients, and we are introducing additional polyfills for backward compatibility to attempt to address the issues occurring on older MacOS versions with this update. We do need to maintain current Angular versions for a variety of reasons, and so we cannot revert this change.

I guess with the minimum version change to Monterey, this isn't happening any more?

**Comment by swilkins1337** [comment]
I'm thinking about just abandoning this and just using iCloud Keychain. Unless there's an acceptable free alternative. I left LastPass for Bitwarden because they started charging for stuff I needed that used to be free.

**Comment by terrywebbs** [comment]
> I'm thinking about just abandoning this and just using iCloud Keychain. Unless there's an acceptable free alternative. I left LastPass for Bitwarden because they started charging for stuff I needed that used to be free.

Keychain has its own issues on older Macs too, that was The reason I moved over to Bitwarden … keychain stopped syncing and was very unreliable however it worked flawlessly on my iPhone as does Bitwarden 

using my Time Machine backup to revert to a known working Bitwarden is a life saver

**Comment by atoussama** [comment]
> > Hello,
> > I wanted to update that we are working on a potential resolution to this now. We are confident that this was introduced with our latest Angular version update across our clients, and we are introducing additional polyfills for backward compatibility to attempt to address the issues occurring on older MacOS versions with this update. We do need to maintain current Angular versions for a variety of reasons, and so we cannot revert this change.
> 
> I guess with the minimum version change to Monterey, this isn't happening any more?

I guess they just couldn't help themselves with one last bug fix before they raised the minimum OS support, didn't they? how convenient from you @Bitwarden!

**Comment by 2ndMessiah** [comment]
So... what if I don't have a time machine backup? Any workaround for for this ?

**Comment by terrywebbs** [comment]
> So... what if I don't have a time machine backup? Any workaround for for this ?

Disable the plugin uninstall Bitwarden (drag the app to the bin) then 

Download an earlier desktop version of Bitwarden 
(February 2024 is the latest stable)
https://github.com/bitwarden/clients/releases
 
If you are on an older mac you shouldn’t need to do much else apart from install the previous stable version ! 
newer macs will have to disable Apple Store updates !

**Comment by terrywebbs** [comment]
Solved my issues - I used OpenCore Legacy Patcher to update my Mac mini 2012 to Sonoma

Now I am running the latest Bitwarden 2024.6.1 on the latest Safari 17.5 - no issues, and for the first time I can log in to the Bitwarden Vault - Safari 15 was obviously too old to work with the latest website security!

If anybody is interested read the following: (this is perfectly legal - it only patches the kernels in memory)
Be aware it's not very clear but you will need 2 USB pen drives one for sonoma and one for the EiF boot patcher .
You will also need lots and lots of patients and be ready to fail, but do not give up.
https://dortania.github.io/OpenCore-Legacy-Patcher/START.html

It runs a bit slow but I am now saving not having to buy a new Mac for a while longer.

**Comment by atoussama** [comment]
just got things working for me since we were let down by Bitwarden (promising a fix for the issue and then discontinuing the support for 10.15 Catalina):

- uninstalled the app fully
- downloaded a previous working version (2024.2.0 is the most recent one that works)
- once installed, open safari and go to preferences
- under advanced tab, select “show develop menu”
- now go go the develop menu and check “allow unsigned extensions”
- go to preferences again, then extensions and activate bitwarden

seems like everything works perfectly, except that you have now to re-allow unsigned extensions every time Safari restarts, but that’s a small price to pay rather than update my entire MacOS.

**Comment by freqyfreqy** [comment]
> Hello,
> 
> I wanted to update that we are working on a potential resolution to this now. We are confident that this was introduced with our latest Angular version update across our clients, and we are introducing additional polyfills for backward compatibility to attempt to address the issues occurring on older MacOS versions with this update. We do need to maintain current Angular versions for a variety of reasons, and so we cannot revert this change.

I'm also on latest Sonoma. So doesn't seem to be restricted to old macs. Using M1 macbook air.

**Comment by zutz** [comment]
now on top of the Safari issues, I’m having problems on my iPhone (SE second generation)I use the free version of Bitwarden and I was wondering with the new problems cropping up if the paid version was any betterOn Aug 27, 2024, at 9:07 AM, freqyfreqy ***@***.***> wrote:﻿

Hello,
I wanted to update that we are working on a potential resolution to this now. We are confident that this was introduced with our latest Angular version update across our clients, and we are introducing additional polyfills for backward compatibility to attempt to address the issues occurring on older MacOS versions with this update. We do need to maintain current Angular versions for a variety of reasons, and so we cannot revert this change.

I'm also on latest Sonoma. So doesn't seem to be restricted to old macs. Using M1 macbook air.

**Comment by freqyfreqy** [comment]
the passwords seems to load into the extension now! But it doesn't seem to autocomplete. Progress!

**Comment by swilkins1337** [comment]
Clearly not for those of us on older systems that were left behind. I switched to iCloud Keychain around two months ago.

**Comment by freqyfreqy** [comment]
> the passwords seems to load into the extension now! But it doesn't seem to autocomplete. Progress!

Nope, doens't work anymore. Stopped working

**Comment by krolloWalker** [comment]
> just got things working for me since we were let down by Bitwarden (promising a fix for the issue and then discontinuing the support for 10.15 Catalina):
> 
> * uninstalled the app fully
> * downloaded a previous working version (2024.2.0 is the most recent one that works)
> * once installed, open safari and go to preferences
> * under advanced tab, select “show develop menu”
> * now go go the develop menu and check “allow unsigned extensions”
> * go to preferences again, then extensions and activate bitwarden
> 
> seems like everything works perfectly, except that you have now to re-allow unsigned extensions every time Safari restarts, but that’s a small price to pay rather than update my entire MacOS.

I did this, but when I was going to log into the safari extension it would not let me log in and gave me this error message: "An error has occurred. Webassembly support is required for the Argon2 KDF feature.” Anyone know how to fix?

**Comment by superfreeman1989** [comment]
Now another bug has appeared. The bitwarden window randomly pops up and can't be dismissed.

**Comment by superfreeman1989** [comment]
auto lock after x minutes also stopped working. vault stays open.

**Comment by swilkins1337** [comment]
@superfreeman1989 I think you should open new issues for new bugs. Well, after searching first.

**Comment by DimitriDR** [comment]
The problem still happens on macOS Sequoia on Safari 18.

**Comment by gpanders** [comment]
This started occurring for me today.

Bitwarden version 2025.11.0 
Safari Version 26.1 (21622.2.11.11.9)
macOS 26.1

The desktop app works. The extension does not.

This is what I see in the console:

<img width="1002" height="565" alt="Image" src="https://github.com/user-attachments/assets/7697c908-87d7-492b-928f-c10651b2544d" />

**Comment by cryptosteve2** [comment]
Same problem here after todays update to v2025.11.0 ...

**Comment by BlakeMyers17** [comment]
> Same problem here after todays update to v2025.11.0 ...

Seconded. Console log attached. 

[bitwarden_2025-11-0_console.log](https://github.com/user-attachments/files/23561727/bitwarden_2025-11-0_console.log)

**Comment by jarbro** [comment]
+1 on MacBook Air M3 running Tahoe 26.1.  As a paying customer this is silly.  ver. 2025.11.0 (50947)

**Comment by aDefrawy** [comment]
Same here, the extension not loading for me anymore :( 
Desktop app is okay!

Bitwarden version 2025.11.0  (50947)
Safari Version 26.1 (21622.2.11.11.9)
macOS 26.1

**Comment by theobredemann** [comment]
Same here
Desktop Ok, Safari extension on infinite loading

Bitwaden Version 2025.11.0 (50947)
Safari Version 26.1 (21622.2.11.11.9)
MacOS Version 26.1 (25B78)
MackBook Air M3

**Comment by pamperer562580892423** [comment]
I'm not sure if Bitwarden sees it the same way, but I would think the current issue with Safari extension version 2025.11.0 is [this one](https://github.com/bitwarden/clients/issues/17399) - and discussions about that current issue should probably be continued there: https://github.com/bitwarden/clients/issues/17399 (BTW, there is an update from a BW developer)

**Comment by simonschwitzky** [comment]
Happens on Bitwarden Apple AppStore 50947 and Safari 21622.2.11.11.9

**Comment by dimm0** [comment]
Same here, Safari Version 26.1 (21622.2.11.11.9), Bitwarden 2025.11.0 (50947)

**Comment by steven-rolph** [comment]
Experiencing this too

- macOS Tahoe, Version 26.1 (25B78)
- Safari Version 26.1 (21622.2.11.11.9)
- Bitwarden Password Manager Version 2025.11.0 (50947)

**Comment by pamperer562580892423** [comment]
@saaymeen @dimm0 @steven-rolph See here: https://github.com/bitwarden/clients/issues/17399
