### ISSUE TITLE
Error when syncing the vault on Linux desktop

### ISSUE THREAD

**Issue by zagota** [bitwarden/clients#8651]
### Steps To Reproduce

1. Go to 'File'
2. Click on 'sync vault'
3. Error sync vault

### Expected Result

sync vault

### Actual Result

Error sync vault

### Additional Context

I have installed version 2024.3.2 and can no longer synchronize the vault. I revert to 2024.3.0 and it works.
Server is self hosted.

### Operating System

Linux

### Operating System Version

Ubuntu 22.04 LTS

### Installation method

Snap

### Build Version

"About Bitwarden" The application crashes 

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by ahmedmoktaar** [comment]
I had the same issue, but it worked fine if you installed version 2024.3.2 from the .deb file.

**Comment by VividTextual** [comment]
Same issue here. Also Ubuntu 22.04 LTS.

**Comment by PeterDrake** [comment]
Same issue, Ubuntu 22.04.4 LTS.

Also, when I try to save a new entry, I get an error "Failed to decode access token; JWT must have 3 parts".

**Comment by justin-yan** [comment]
Echo-ing everyone else - 2024.3.2 snap install presented issues in multiple ways:

- saved TOTP tokens no longer displayed generated codes (said "Premium plan required")
- attempts to sync or add items resulted in the "JWT must have 3 parts" banner error
- a complete log-out and then log-in resulted in a spinner and no items appearing

Reverting to 2024.3.0 restored functionality

**Comment by marcosguedes** [comment]
I use snap and reverting versions worked (tip by @justin-yan . Full command: `sudo snap revert bitwarden`

**Comment by bacchilu** [comment]
> Hi everyone, thank you for the reports! We moved to storing our tokens in secure storage with this release, but unfortunately snap packages are sandboxed and we can't automatically enable access to the `password-manager-service` permission. If you're running into this issue there are a couple fixes:
> 
> 1. Ubuntu Software > Installed > Bitwarden > Permissions - turn on "Read, add, change or remove saved passwords"
> 2. Run the following: `sudo snap connect bitwarden:password-manager-service`
> 
> Please be sure to log out and back in after enabling this permission. If you encounter any issues please feel free to reach out, thanks!

Same problem on Ubuntu 23.10 Desktop and Bitwarden installed via snap package (current Bitwarden version: 2024.4.0).

```
Versione 2024.4.0
Shell 28.2.8
Renderer 120.0.6099.291
Node 18.18.2
Architecture x64
```

![Schermata del 2024-04-11 15-54-09](https://github.com/bitwarden/clients/assets/1101442/3d4878c0-0b63-4012-a9a9-5e3b9d9bb031)
nfortunately the described solution doesn't seem to work...

**Comment by pescepilota** [comment]
> > Hi everyone, thank you for the reports! We moved to storing our tokens in secure storage with this release, but unfortunately snap packages are sandboxed and we can't automatically enable access to the `password-manager-service` permission. If you're running into this issue there are a couple fixes:
> > 
> > 1. Ubuntu Software > Installed > Bitwarden > Permissions - turn on "Read, add, change or remove saved passwords"
> > 2. Run the following: `sudo snap connect bitwarden:password-manager-service`
> > 
> > Please be sure to log out and back in after enabling this permission. If you encounter any issues please feel free to reach out, thanks!
> 
> Same problem on Ubuntu 23.10 Desktop and Bitwarden installed via snap package (current Bitwarden version: 2024.4.0).
> 
> ```
> Versione 2024.4.0
> Shell 28.2.8
> Renderer 120.0.6099.291
> Node 18.18.2
> Architecture x64
> ```
> 
> Unfortunately the described solution doesn't seem to work...
> 
> ![Schermata del 2024-04-11 15-54-09](https://private-user-images.githubusercontent.com/1101442/321655582-3d4878c0-0b63-4012-a9a9-5e3b9d9bb031.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDU3MDQsIm5iZiI6MTcxMjg0NTQwNCwicGF0aCI6Ii8xMTAxNDQyLzMyMTY1NTU4Mi0zZDQ4NzhjMC0wYjYzLTQwMTItYTlhOS01ZTNiOWQ5YmIwMzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMTQyMzI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmIzYmRhMGE3MjhiNGI1ZGRlYmQxOWEyOWY2MWI5N2MzYzk5NDE1OGUzN2ViMTg5OGExM2RiZDczYzc0MDJkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RPzkxVvKjrNuzzMmVNek_ZJyS7utQqq1yMz0_Off9Lc)

Try logging out of your account (File > Esci > tuo account) and then logging back in. It worked for me

**Comment by sean-abercrombie** [comment]
My bug report was marked as closed and pointed towards here as the same issue. But I am not on a Linux platform so the fix doesn't apply to me, I am on Windows. Newest version 2024.4.0 does not resolve the issue. Still have to downgrade to below 2024.3.4 to restore functionality.

**Comment by janvkn** [comment]
I'm still experiencing this issue with the Arch Linux package. I had to rollback to 2024.3.0 and remove my `~/.config/Bitwarden` directory to get it to work.

Bitwarden is not a snap package on Arch Linux, so the `snap connect ...` workaround is not applicable.

**Comment by JohnTocher** [comment]
> > > Hi everyone, thank you for the reports! We moved to storing our tokens in secure storage with this release, but unfortunately snap packages are sandboxed and we can't automatically enable access to the `password-manager-service` permission. If you're running into this issue there are a couple fixes:
> > > 
> > > 1. Ubuntu Software > Installed > Bitwarden > Permissions - turn on "Read, add, change or remove saved passwords"
> > > 2. Run the following: `sudo snap connect bitwarden:password-manager-service`
> > > 
> > > Please be sure to log out and back in after enabling this permission. If you encounter any issues please feel free to reach out, thanks!
> > 
> > 
> > Same problem on Ubuntu 23.10 Desktop and Bitwarden installed via snap package (current Bitwarden version: 2024.4.0).
> > ```
> > Versione 2024.4.0
> > Shell 28.2.8
> > Renderer 120.0.6099.291
> > Node 18.18.2
> > Architecture x64
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Unfortunately the described solution doesn't seem to work...
> > ![Schermata del 2024-04-11 15-54-09](https://private-user-images.githubusercontent.com/1101442/321655582-3d4878c0-0b63-4012-a9a9-5e3b9d9bb031.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDU3MDQsIm5iZiI6MTcxMjg0NTQwNCwicGF0aCI6Ii8xMTAxNDQyLzMyMTY1NTU4Mi0zZDQ4NzhjMC0wYjYzLTQwMTItYTlhOS01ZTNiOWQ5YmIwMzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMTQyMzI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmIzYmRhMGE3MjhiNGI1ZGRlYmQxOWEyOWY2MWI5N2MzYzk5NDE1OGUzN2ViMTg5OGExM2RiZDczYzc0MDJkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RPzkxVvKjrNuzzMmVNek_ZJyS7utQqq1yMz0_Off9Lc)
> 
> Try logging out of your account (File > Esci > tuo account) and then logging back in. It worked for me

This didn't work for me, even after a full reboot I get the same error. 
In the end I uninstalled the snap and reinstalled from the .deb file
I appreciate this means no automatic updates, but for now I'll take that over an update that might break things with no notice.
System is: Ubuntu 23.10 64 bit GNOME 45.2, Wayland WS

**Comment by shorawitz** [comment]
I too am seeing this issue and not using snap (I think when I first started w/Birwarden, snap wasn't available):
Ubuntu 23.10 KDE
Bitwarden-2024.4.1-x86_64.AppImage

**Comment by jlf0dev** [comment]
Hey ya'll, this turned out to be a little bigger than we initially thought. We're working on a fix in #8776 that should resolve the token errors being reported.

If anyone has the time to test #8776 on their system, we would also appreciate the help. We're looking to discover potential issues early on. Thanks!

**Comment by kaarelen** [comment]
bitwarden 2024.4.0-1
Arch Linux (rolling release, fully updated) without DE, barebone WM

01:00:41.323 › Error: Failed to decode access token: JWT must have 3 parts
01:00:41.323 › Received API exception: Error: Failed to decode access token: JWT must have 3 parts

on attempt to save new entry

I think it could be really better to make logs more informative. Application failed to do something (get it) with token because it (app) lacks permissions/dependencies/etc. It has to be in logs, because at this point logs are basically wrong, it's not decoding error. What do you think, @jlf0dev?

@janvkn so there is any normal workaround without roll backing? I really do not want to depend on some random desktop environment.

**Comment by tg-mw** [comment]
I had the same issue on Kubuntu 22.04.4 LTS (KDE).
The fix mentioned above did not work for me until I installed gnome-keyring.
It seems as if older versions of kwallet do not support the org.freedesktop.secrets DBus API, which seems to be necessary for Bitwarden to work properly.

**Comment by tabascosw** [comment]
I can confirm tg-mw comments. I use openSUSE Tumbleweed latest snapshot, installation of gnome-keyring made the appimage 2024-4.1 working again.

**Comment by shorawitz** [comment]
I have `gnome-keyring: 42.1` installed on kubuntu 23.10.  I can open Bitwarden-2024.4.1-x86_64.AppImage and view, but I try to edit an entry I get the error:

Received API exception: Error: Failed to decode access token: JWT must have 3 parts

**Comment by tabascosw** [comment]
I just played around a bit, de-installed gnome-keyring and installed the latest kwallet 6.1 (incl. pam-kwallet 6.04) and that also works, I can also edit entries.

**Comment by shorawitz** [comment]
:-(  Kwallet 6.1 is the latest in Github.  I won't see that in any Ubuntu distro I'll bet until next year (if I'm lucky.)  I'll have to figure something else out until it's fixed

**Comment by FraioVeio** [comment]
Same problem here on Arch.

```
~ $ bitwarden-desktop
15:26:26.424 › State version: 48
15:26:26.428 › Migrator MinVersionMigrator (to version 3) should migrate: false - up
15:26:26.428 › Migrator RemoveEverBeenUnlockedMigrator (to version 4) should migrate: false - up
15:26:26.429 › Migrator AddKeyTypeToOrgKeysMigrator (to version 5) should migrate: false - up
15:26:26.429 › Migrator RemoveLegacyEtmKeyMigrator (to version 6) should migrate: false - up
15:26:26.429 › Migrator MoveBiometricAutoPromptToAccount (to version 7) should migrate: false - up
15:26:26.430 › Migrator MoveStateVersionMigrator (to version 8) should migrate: false - up
15:26:26.430 › Migrator MoveBrowserSettingsToGlobal (to version 9) should migrate: false - up
15:26:26.430 › Migrator EverHadUserKeyMigrator (to version 10) should migrate: false - up
15:26:26.431 › Migrator OrganizationKeyMigrator (to version 11) should migrate: false - up
15:26:26.431 › Migrator MoveEnvironmentStateToProviders (to version 12) should migrate: false - up
15:26:26.432 › Migrator ProviderKeyMigrator (to version 13) should migrate: false - up
15:26:26.432 › Migrator MoveBiometricClientKeyHalfToStateProviders (to version 14) should migrate: false - up
15:26:26.432 › Migrator FolderMigrator (to version 15) should migrate: false - up
15:26:26.432 › Migrator LastSyncMigrator (to version 16) should migrate: false - up
15:26:26.432 › Migrator EnablePasskeysMigrator (to version 17) should migrate: false - up
15:26:26.433 › Migrator AutofillSettingsKeyMigrator (to version 18) should migrate: false - up
15:26:26.433 › Migrator RequirePasswordOnStartMigrator (to version 19) should migrate: false - up
15:26:26.433 › Migrator PrivateKeyMigrator (to version 20) should migrate: false - up
15:26:26.433 › Migrator CollectionMigrator (to version 21) should migrate: false - up
15:26:26.433 › Migrator CollapsedGroupingsMigrator (to version 22) should migrate: false - up
15:26:26.433 › Migrator MoveBiometricPromptsToStateProviders (to version 23) should migrate: false - up
15:26:26.433 › Migrator SmOnboardingTasksMigrator (to version 24) should migrate: false - up
15:26:26.434 › Migrator ClearClipboardDelayMigrator (to version 25) should migrate: false - up
15:26:26.434 › Migrator RevertLastSyncMigrator (to version 26) should migrate: false - up
15:26:26.434 › Migrator BadgeSettingsMigrator (to version 27) should migrate: false - up
15:26:26.434 › Migrator MoveBiometricUnlockToStateProviders (to version 28) should migrate: false - up
15:26:26.434 › Migrator UserNotificationSettingsKeyMigrator (to version 29) should migrate: false - up
15:26:26.434 › Migrator PolicyMigrator (to version 30) should migrate: false - up
15:26:26.434 › Migrator EnableContextMenuMigrator (to version 31) should migrate: false - up
15:26:26.434 › Migrator PreferredLanguageMigrator (to version 32) should migrate: false - up
15:26:26.435 › Migrator AppIdMigrator (to version 33) should migrate: false - up
15:26:26.435 › Migrator DomainSettingsMigrator (to version 34) should migrate: false - up
15:26:26.435 › Migrator MoveThemeToStateProviderMigrator (to version 35) should migrate: false - up
15:26:26.435 › Migrator VaultSettingsKeyMigrator (to version 36) should migrate: false - up
15:26:26.435 › Migrator AvatarColorMigrator (to version 37) should migrate: false - up
15:26:26.435 › Migrator TokenServiceStateProviderMigrator (to version 38) should migrate: false - up
15:26:26.435 › Migrator MoveBillingAccountProfileMigrator (to version 39) should migrate: false - up
15:26:26.435 › Migrator OrganizationMigrator (to version 40) should migrate: false - up
15:26:26.436 › Migrator EventCollectionMigrator (to version 41) should migrate: false - up
15:26:26.436 › Migrator EnableFaviconMigrator (to version 42) should migrate: false - up
15:26:26.436 › Migrator AutoConfirmFingerPrintsMigrator (to version 43) should migrate: false - up
15:26:26.436 › Migrator UserDecryptionOptionsMigrator (to version 44) should migrate: false - up
15:26:26.436 › Migrator MergeEnvironmentState (to version 45) should migrate: false - up
15:26:26.436 › Migrator DeleteBiometricPromptCancelledData (to version 46) should migrate: false - up
15:26:26.436 › Migrator MoveDesktopSettingsMigrator (to version 47) should migrate: false - up
15:26:26.437 › Migrator MoveDdgToStateProviderMigrator (to version 48) should migrate: false - up
15:26:27.281 › State version: 48
15:26:27.290 › Error: The name is not activatable
15:26:27.294 › Error: The name is not activatable
15:26:27.299 › Error: The name is not activatable
15:26:27.303 › Error: The name is not activatable
15:26:27.311 › Error: The name is not activatable
15:26:27.312 › Error: The name is not activatable
15:26:27.340 › Error: The name is not activatable
15:26:27.341 › Error: The name is not activatable
15:26:27.351 › Error: The name is not activatable
15:26:27.379 › Error: The name is not activatable
15:26:27.379 › Error: The name is not activatable
15:26:27.380 › Error: The name is not activatable
15:26:27.394 › Error: The name is not activatable
15:26:27.395 › Error: The name is not activatable
15:26:27.400 › Error: The name is not activatable
15:26:27.407 › Error: The name is not activatable
15:26:27.407 › Error: The name is not activatable
15:26:27.408 › Unable to fetch ServerConfig: Failed to decode access token: JWT must have 3 parts
15:26:27.410 › Error: The name is not activatable
15:26:27.422 › Error: The name is not activatable
15:26:27.459 › Error: The name is not activatable
15:26:28.381 › Error: The name is not activatable
15:26:28.398 › Error: The name is not activatable
15:26:28.413 › Error: The name is not activatable
```

**Comment by android10** [comment]
I was also having the same issue: 

 - **OS:** Arch Linux
 - **Bitwarden desktop version:** [bitwarden 2024.4.0-1](https://archlinux.org/packages/extra/x86_64/bitwarden/)
 - **Backend:** self-hosted
 - **Logs:**
 
```bash
22:16:25.680 › Error: The name is not activatable
22:16:25.759 › Error: The name is not activatable
22:16:25.762 › Error: The name is not activatable
22:16:25.764 › Error: The name is not activatable
22:16:25.766 › Error: The name is not activatable
22:16:25.774 › Received API exception: Error: Failed to decode access token: JWT must have 3 parts
22:16:25.776 › Error: The name is not activatable
22:16:25.778 › Error: The name is not activatable
22:16:25.797 › Error: The name is not activatable
22:16:25.810 › Error: The name is not activatable
22:16:25.813 › Unable to fetch ServerConfig: Failed to decode access token: JWT must have 3 parts
22:16:27.815 › Error: The name is not activatable
22:16:27.822 › Error: The name is not activatable
22:16:37.818 › Error: The name is not activatable
22:16:37.827 › Error: The name is not activatable
22:16:47.817 › Error: The name is not activatable
22:16:47.826 › Error: The name is not activatable
22:16:57.817 › Error: The name is not activatable
22:16:57.826 › Error: The name is not activatable
22:17:07.818 › Error: The name is not activatable
22:17:07.827 › Error: The name is not activatable
```

**Unfortunately none of the proposed solutions here worked for me,** so there is anything else we can do other than rolling back to an older version and clean up the Bitwarden Desktop Client **Cache** and **Settings:**

1. `sudo pacman -Rns bitwarden`
1. `rm -rf ~/.config/Bitwarden`
2. `ls /var/cache/pacman/pkg/bitwarden*`
3. `sudo pacman -U /var/cache/pacman/pkg/bitwarden-2024.3.0-1-x86_64.pkg.tar.zst` (install any other older version)
4. Wait for a fix in my case since I do not know the codebase :(

I hope that helps. 

**Issues happen and be always grateful with the teams, contributors or anyone involved in any open source project.**

Thanks for such a great project in any case! ❤️

**Comment by 1nv1zzz** [comment]
I've also faced the same issue. Fixed it by cleaning the cache and running Bitwarden with the parameter _--password-store=kwallet_ (I'm using arch+KDE).
For Gnome users needed parameter looks like this: --password-store=gnome-libsecret
I don't know the root cause of this issue, seems like something related to credentials storage because I've fixed the same issue with the Wire desktop application.

**Comment by ruanpereira** [comment]
OS: Arch Linux
WM: bspwm
Bitwarden desktop version: [bitwarden 2024.4.0-1](https://archlinux.org/packages/extra/x86_64/bitwarden/)

I also have installed KDE DE on my system, probably works the solution proposed above, using the parameter, but it is quite sad that RN is not working with Window Managers. 

Hope that something can be done. 
Love the app!!!!

**Comment by trmartin4** [comment]
Hello!

We are actively working on a solution to this problem.  The solution will be implemented with https://github.com/bitwarden/clients/pull/8913, which is currently in final development.  We will need to through remaining development, QA and release, so I cannot commit to a particular date at this point.

We appreciate your patience as we work through a solution to this issue.

**Comment by sjuliancarrizo** [comment]
> I had the same issue on Kubuntu 22.04.4 LTS (KDE). The fix mentioned above did not work for me until I installed gnome-keyring. It seems as if older versions of kwallet do not support the org.freedesktop.secrets DBus API, which seems to be necessary for Bitwarden to work properly.

I can confirm this in Kubuntu 22.04.4 LTS (KDE). Steps:
1_ sudo apt install gnome-keyring
2_ Download Appimage from Bitwarden website.
3_ At the first run, keyring asks to create a password. Just give one and then the app starts and works fine.

**Comment by trmartin4** [comment]
Hello,

For anyone experiencing this issue, we have a [build](https://github.com/bitwarden/clients/actions/runs/8971549439) available if you would like to download and verify that you are able to log in successfully _without_ necessarily installing `gnome-keyring` or `kwallet`.  **This is a non-production build still in review, so we do advise that you back up your vault before using.**

The change will detect whether there are issues with the OS credential store (Secrets Service in this case) and fall back to disk storage for the access token and refresh token if there are any problems storing it. Secure storage is the preference and the default, but we recognize that there may be circumstances in which that mechanism is not available and we need to support it without preventing the user from accessing their vault.

We are continuing to investigate the root cause of the reports of inconsistent behavior with Secrets Service implementations so that we can reduce the necessity to fall back to only the minimum possible number of users.

**Comment by ThomasBoom89** [comment]
> Hello,
> 
> For anyone experiencing this issue, we have a [build](https://github.com/bitwarden/clients/actions/runs/8971549439) available if you would like to download and verify that you are able to log in successfully _without_ necessarily installing `gnome-keyring` or `kwallet`. **This is a non-production build still in review, so we do advise that you back up your vault before using.**
> 
> The change will detect whether there are issues with the OS credential store (Secrets Service in this case) and fall back to disk storage for the access token and refresh token if there are any problems storing it. Secure storage is the preference and the default, but we recognize that there may be circumstances in which that mechanism is not available and we need to support it without preventing the user from accessing their vault.
> 
> We are continuing to investigate the root cause of the reports of inconsistent behavior with Secrets Service implementations so that we can reduce the necessity to fall back to only the minimum possible number of users.

Hello,
i am running arch linux without gnome-keyring and without kwallet.
Current bitwarden desktop version bitwarden 2024.4.3-1 doesn't work and shows the same error: 
1. Error: Failed to decode access token: JWT must have 3 parts 
2. Error: The name is not activatable

I tested the build you mentioned and was able to log in and also synchronize my vault, so this build seems to fix the problem, at least for me.
Thank you!

**Comment by tabascosw** [comment]
The mentioned build works for me as well.

**Comment by renatoliveira** [comment]
On version 2024.4.1 (23240) on a M3 mac (Sonoma 14.4.1 (23E224)) I also get this red popup at the top right of the app when trying to save a new login credential:

> Error: Failed to decode access token: JWT must have 3 parts

Quitting the app and opening it again doesn't do anything.

Installing [the version 2024.4.3 from the build artifact](https://github.com/bitwarden/clients/actions/runs/8971549439/artifacts/1476989128) mentioned before in this issue solved the problem.

**Comment by JohnTocher** [comment]
That build worked for me too.  I'm on Ubuntu 23.10, using the Bitwarden-2024.4.3-x86_64.AppImage

The numbers in the "About" dialog are the same as my installed version though, even though only the one from run 8971549439 allows me to make changes.

> Version 2024.4.3
> Shell 28.3.1
> Renderer 120.0.6099.291
> Node 18.18.2
> Architecture x64

**Comment by mamama1** [comment]
I managed to revert to 2024.3.0 on Fedora 40 KDE spin, worked for me.

**Comment by Caligatio** [comment]
For those using KDE and thus "using" kwallet as their secrets manager, there's [another step](https://wiki.archlinux.org/title/KDE_Wallet#Automatic_D-Bus_activation) that works for at least Arch users. In `~/.local/share/dbus-1/services/org.freedesktop.secrets.service` (you probably need to make a few levels of directories):

```
[D-BUS Service]
Name=org.freedesktop.secrets
Exec=/usr/bin/kwalletd6
```

A logout and/or reboot might be required but it worked like a champ after the above.

**Comment by uniconstructor** [comment]
Just updated to latest snao. Still unable to sync password base with server. 

Actions taken:
1) open bitwarden desktop
2) select any record
3) click "edit"
4) click "save"

Expected result: record saved locally and synced to server. Local changes persisted even if sync fails.
Actual result: record is not saved (**even local changes cannot be saved**). Sync failed with message "Failed to decode access token: JWT must have 3 parts".

Version 2024.5.0
Shell 28.3.1
Renderer 120.0.6099.291
Node 18.18.2
Architecture x64

**Comment by mamama1** [comment]
```
sudo flatpak update --commit=47213097bc0383ffeff5b00d706d0eb121192449fe3cace77923ab879bc248c1 com.bitwarden.desktop
flatpak mask com.bitwarden.desktop

```
that did the trick for me, for flatpak anyway.

**Comment by Meek97** [comment]
I was running into this issue as well on Linux Mint. I installed the Flatpak version through the LM Software Manager, and it didn't seem like it was able to sync properly. I could log in fine (I do not have MFA enabled for my vault log in), but none of my vault items would load. if i tried manually syncing i would get a generic "could not sync" error.
I tried the above mention work-around to downgrade to an earlier version and after re-launching I was prompted to log in again and the vault started to sync

**Comment by Benq87** [comment]
Sick and tired with this rubbish! Can`t they fix it for once  and forever.

**Comment by FraioVeio** [comment]
I confirm problem is fixed on bitwarden-2024.5.0-1 on arch :)

**Comment by tabascosw** [comment]
Still does not work in openSUSE Tumbleweed using the latest appimage 2024.5. It does not sync. Back to the build mentioned above, at least it doesn't auto update.

**Comment by 0xsimulacra** [comment]
I can comfirm the problem has been solved for me on openSUSE Tumbleweed with the recent update of "org.freedesktop..." related packages (version 23.08).

**Comment by solumath** [comment]
For folks with this problem. Be aware that the bitwarden writes in syslog that it doesn't have permissions. Mentioning because after a while my syslog was 30GB in size. :+1:

**Comment by mamama1** [comment]
> For folks with this problem. Be aware that the bitwarden writes in syslog that it doesn't have permissions. Mentioning because after a while my syslog was 30GB in size. 👍

more and more i get a feeling that this isn't quality software, but hipster software.

on fedora it is journalctl btw for anyone who is searching for the syslog file.

**Comment by trmartin4** [comment]
@solumath can you expand on this a bit, perhaps including an error message that you're seeing, as well as the distribution method that you're using for the application (Snap, etc.)?

We want to make sure to address this issue if possible.

**Comment by solumath** [comment]
> @solumath can you expand on this a bit, perhaps including an error message that you're seeing, as well as the distribution method that you're using for the application (Snap, etc.)?
> 
> We want to make sure to address this issue if possible.

Hey, thank you for reaching out. I didn't note the error. I vaguely remember it read out `bitwarden ... permission denied [13]...`. So don't think that will help, sorry. I tried to replicate but I upgraded to 2024.5.0 and can't reproduce it so It seems it was fixed in the meantime.

I'm on ubuntu 24.04, used snap manager. Version before was 2024.4.1

**Comment by trmartin4** [comment]
Hello,

As this thread has a lot of history, we felt it would be good to summarize the current status of the issue and the options available.

## Summary of current behavior
The current version (`2024.5.0`) uses `libsecret` to communicate over D-BUS with the `org.freedesktop.secrets` Secret Service implementation (e.g. `gnome-keyring`)  in order to store persistent authentication tokens if your vault timeout action is "Lock".  If there is no such service configured (or the application has issues communicating with the service), the current version does not have any built-in fallback to disk storage for the tokens, which is what is causing the errors experienced in this ticket.  **The mechanism for fallback will be introduced in the next release of our desktop application**, as we are doing extensive internal testing to make sure that we do not introduce any regressions in behavior across all of the affected OSes.

As there are a lot of different parties involved in that communication path, we have seen some issues arise and raised on this thread.  We'd like to highlight them below and make sure that the solutions are documented.  We will also be updating our Help Center documentation to reflect this in more detail as we release the next update.

#### 🗒️  Issue 1: The application doesn't have permission to communicate over D-BUS to the Secret Service
For our Snap sandboxed deployments, it is necessary to grant the application permission to access the service via D-BUS.  This can be done with `sudo snap connect bitwarden:password-manager-service`.

#### 🗒️ Issue 2: There is no Secret Service configured
As some have noted, configuring `gnome-keyring` will satisfy this requirement.  It was an oversight on our part to not provide documentation for those users who would not have such a provider configured by default.  

For those using `kwallet`, additional configuration may be required, as @Caligatio called out [here](https://github.com/bitwarden/clients/issues/8651#issuecomment-2119900100):
```
[D-BUS Service]
Name=org.freedesktop.secrets
Exec=/usr/bin/kwalletd6
```

In addition, there is a [recent bug](https://bugs.kde.org/show_bug.cgi?id=487348) reported with Flatpak and `kwallet` that would potentially affect Flatpak users who are attempting to use `kwallet` as their secret provider.

If you do not have a Secret Service configured, and prefer not to do so, [this](https://github.com/bitwarden/clients/actions/runs/9195397078) build is available to install.  This is the build currently under test for our next release.  **This is a development build and we recommend backing up your vault before use**.

Once again, we thank you for your patience as we work through this issue.  If there are any problems that do **not** conform to these assumptions, please raise them so that we can make sure that we take them into consideration.

**Comment by dom21121** [comment]
Good morning,
I'm running bitwarden snap on Ubuntu 22.04. After doing all the manipulations -> still doesn't  work.
Remove  /home/snap/bitwarden folder.
Re-launch bitwarden -> OK.

**Comment by chrisl84** [comment]
> Good morning, I'm running bitwarden snap on Ubuntu 22.04. After doing all the manipulations -> still doesn't work. Remove /home/snap/bitwarden folder. Re-launch bitwarden -> OK.

Same situation, tried all suggestions, but this one worked for me.

**Comment by AliOko** [comment]
For me, it works:
1.  log out 
2. uncheck 'remember email` 
3. log in
4. log out 
5. check `remember email`

**Comment by Epsicle** [comment]
> I'm still experiencing this issue with the Arch Linux package. I had to rollback to 2024.3.0 and remove my `~/.config/Bitwarden` directory to get it to work.

Thank you all for the incredible detail on this issue.

I am running Debian 12 and KDE Plasma desktop and experienced a similar issue on a new setup. After uninstalling bitwarden to switch my application manager (moved from snapd to [deb-get](https://github.com/wimpysworld/deb-get), a tool that just downloads the .deb directly from github) and I received a spinning buffering circle of doom.

While @janvkn had to roll back to 2024.3.0 and delete the .config file on Arch. I can confirm that on Debian 12 and KDE Plasma version 5.27.5 all that is required is to delete the ~/,config/Bitwarden folder after uninstalling the snap. After that, Bitwarden has been functioning as normal.

**Comment by rearden888** [comment]
> For those using KDE and thus "using" kwallet as their secrets manager, there's [another step](https://wiki.archlinux.org/title/KDE_Wallet#Automatic_D-Bus_activation) that works for at least Arch users. In `~/.local/share/dbus-1/services/org.freedesktop.secrets.service` (you probably need to make a few levels of directories):
> 
> ```
> [D-BUS Service]
> Name=org.freedesktop.secrets
> Exec=/usr/bin/kwalletd6
> ```
> 
> A logout and/or reboot might be required but it worked like a champ after the above.

I can also confirm this works for non-KDE desktops using kwallet.  In my case, using hyprland with kwallet as my secret store.  Works great.

**Comment by prettyboy42** [comment]
> Good morning, I'm running bitwarden snap on Ubuntu 22.04. After doing all the manipulations -> still doesn't work. Remove /home/snap/bitwarden folder. Re-launch bitwarden -> OK.

Wow It worked for me. Many thanks.

**Comment by aleoscar** [comment]
> For those using KDE and thus "using" kwallet as their secrets manager, there's [another step](https://wiki.archlinux.org/title/KDE_Wallet#Automatic_D-Bus_activation) that works for at least Arch users. In `~/.local/share/dbus-1/services/org.freedesktop.secrets.service` (you probably need to make a few levels of directories):
> 
> ```
> [D-BUS Service]
> Name=org.freedesktop.secrets
> Exec=/usr/bin/kwalletd6
> ```
> 
> A logout and/or reboot might be required but it worked like a champ after the above.

This solved the issue for me thanks! I'm using Arch and Hyprland as my WM and assume that the error was caused by "Issue 2" in @trmartin4 comment, others might have the same issue if they're not using a fully featured DE but rather some more minimal WM.

**Comment by tawhk** [comment]
> > For those using KDE and thus "using" kwallet as their secrets manager, there's [another step](https://wiki.archlinux.org/title/KDE_Wallet#Automatic_D-Bus_activation) that works for at least Arch users. In `~/.local/share/dbus-1/services/org.freedesktop.secrets.service` (you probably need to make a few levels of directories):
> > ```
> > [D-BUS Service]
> > Name=org.freedesktop.secrets
> > Exec=/usr/bin/kwalletd6
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > A logout and/or reboot might be required but it worked like a champ after the above.
> 
> I can also confirm this works for non-KDE desktops using kwallet. In my case, using hyprland with kwallet as my secret store. Works great.

I was having this issue on my  Garuda 

Version 2025.1.3
SDK 'main (28c7e29)'
Shell 33.3.2
Renderer 130.0.6723.191
Node 20.18.1
Architecture x64

And this solution worked for me. Thanks.

**Comment by eblakem** [comment]
I just deleted everything in ~/.config/Bitwarden directory and it works again (not on snap, just bitwarden-2025.2.1-1)

**Comment by juliend2** [comment]
It's May 2025 and I'm also getting this.
I'm using Version 2025.4.2
SDK 'main (f28b4ef)'
Shell 34.5.6
Renderer 132.0.6834.210
Node 20.19.1
Architecture x64

on Manjaro Linux.

Deleting the whole `~/.config/Bitwarden` as suggested by @eblakem did the trick. Thank you!
