### ISSUE TITLE
TypeError: globalThis.requestIdleCallback is not a function.

### ISSUE THREAD

**Issue by steviepitman** [bitwarden/clients#9647]
### Steps To Reproduce

1. open safari desktop
2. open any page
3. open the console
4. error message below is displayed in the console

### Expected Result

no error!

### Actual Result

Console error:
safari-web-extension://.......... /content/bootstrap-autofill-overlay.js
"TypeError: globalThis.requestIdleCallback is not a function. (In 'globalThis.requestIdleCallback(this.processMutations, { timeout: 500 })', 'globalThis.requestIdleCallback' is undefined)"

Clicking on the above 'bootstrap-autofill-overlay.js' link takes you to:
- 'Sources' tab
- 'Extension scripts' section
- displays "bootstrap-autofill-overlay.js Bitwarden Password Manager"

### Screenshots or Videos

<img width="618" alt="Screenshot 2024-06-14 at 15 28 04" src="https://github.com/bitwarden/clients/assets/56626152/ad9e3c75-a0af-4d8e-a365-692217983c69">
<img width="423" alt="Screenshot 2024-06-14 at 15 27 48" src="https://github.com/bitwarden/clients/assets/56626152/6dc1e2bd-588d-4e01-ac73-8dccaf2cbe3e">

### Operating System

macOS

### Operating System Version

Sonoma 14.5

### Web Browser

Safari

### Browser Version

Version 17.5 (19618.2.12.11.6)

### Build Version

Version 2024.6.0 (25275)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cagonzalezcs** [comment]
@steviepitman 

Thank you for this bug report. [This issue has been resolved](https://github.com/bitwarden/clients/pull/9643), though it was merged after the recent release window for the extension was cut. That said, you'll see the problem fixed in a future release of the Safari extension.

**Comment by marcolaux** [comment]
may I ask when this will find it's way into the App Store version? it seems still to be an issue.

**Comment by cagonzalezcs** [comment]
@marcolaux 

Definitely will continue to be an issue in that version, I'm sorry for that. 

I don't have final confirmation yet, but I've been working with my manager to get the fix for this in as a hotfix to the desktop application. Still working through that process with the team, but I'll let you know when this will released when I have a definitive answer.

**Comment by Fischmuetze** [comment]
Issue is still persistent in Version 2024.6.2 (25599)
macOS Sonoma 15.4
Safari 17.5

With active Bitwarden-Extension

![with_BW](https://github.com/bitwarden/clients/assets/19834496/a18b5ec6-e867-4945-85f6-96d25a9b7e08)

Without  active Bitwarden-Extension

![without_BW](https://github.com/bitwarden/clients/assets/19834496/c0ffbd9e-8b8e-4b32-9cd9-cd484e550ea6)

**Comment by Reginard** [comment]
> Issue is still persistent in Version 2024.6.2 (25599) macOS Sonoma 15.4 Safari 17.5
> 
> With active Bitwarden-Extension
> 
> ![with_BW](https://private-user-images.githubusercontent.com/19834496/341705267-a18b5ec6-e867-4945-85f6-96d25a9b7e08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMzU0MzUsIm5iZiI6MTcxOTAzNTEzNSwicGF0aCI6Ii8xOTgzNDQ5Ni8zNDE3MDUyNjctYTE4YjVlYzYtZTg2Ny00OTQ1LTg1ZjYtOTZkMjVhOWI3ZTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDA1NDUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNWEzNDE2NGIwNmEzYTU1NjQzZjk1NzEyYWYxZjcyM2I2YTY5ZTg0MzEwZjkwZDY2NjJjYzExOTMxMjQxOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9_ouinK-x-yHtjTEPWjg3nk8wsbHSK2mx6v3PiGUlzE)
> 
> Without active Bitwarden-Extension
> 
> ![without_BW](https://private-user-images.githubusercontent.com/19834496/341705276-c0ffbd9e-8b8e-4b32-9cd9-cd484e550ea6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMzU0MzUsIm5iZiI6MTcxOTAzNTEzNSwicGF0aCI6Ii8xOTgzNDQ5Ni8zNDE3MDUyNzYtYzBmZmJkOWUtOGI4ZS00YjMyLTljZDktY2Q0ODRlNTUwZWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDA1NDUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkYTJkYWQxMTljNzgzMjgzN2YxYWIyMmM5ZTk3MGQwN2ZjZGIyOWNkZGU0M2Y4NWU1YzQ0MzQ1NGVkMWFhYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MHFBIBrTJF6ERQAa3vfEuVWSKN_8bMXAdRcCLVL5FL4)

Same here

**Comment by nickdekruijk** [comment]
@Reginard @Fischmuetze Read the posts above you, it has been fixed but not released yet.
But that does make me wonder why are the release windows so long? Why not release quicker @cagonzalezcs ?

**Comment by differsthecat** [comment]
> @Reginard @Fischmuetze Read the posts above you, it has been fixed but not released yet. But that does make me wonder why are the release windows so long? Why not release quicker @cagonzalezcs, when is the next release?

Hi @nickdekruijk , to answer your question about our release windows, we have to go through various app stores and review processes for the extension, so it takes longer than some of our other clients like the web app. I will be working with the release team early this week to see when we can get the fix for this one out and will update you here.

**Comment by nickdekruijk** [comment]
> > @Reginard @Fischmuetze Read the posts above you, it has been fixed but not released yet. But that does make me wonder why are the release windows so long? Why not release quicker @cagonzalezcs, when is the next release?
> 
> Hi @nickdekruijk , to answer your question about our release windows, we have to go through various app stores and review processes for the extension, so it takes longer than some of our other clients like the web app. I will be working with the release team early this week to see when we can get the fix for this one out and will update you here.

Thanks for the clarification. I know app update reviews can be a pain but having only a fixed release schedule without even trying to submit (much needed) bug fixes just doesn't feel right to me. 
If only there was a TestFlight for the MacOs app (or at least I can't find it, did find the iOS beta)

**Comment by differsthecat** [comment]
> Thanks for the clarification. I know app update reviews can be a pain but having only a fixed release schedule without even trying to submit (much needed) bug fixes just doesn't feel right to me. If only there was a TestFlight for the MacOs app (or at least I can't find it, did find the iOS beta)

@nickdekruijk Of course. We do submit unscheduled releases to fix critical issues, but it can be disruptive to many teams, so we triage issues and try to identify reasonable workarounds if they are available. It's a process we are continually working on to streamline to make less disruptive. I understand it can be frustrating at times when there is an issue, we do very much take that into account. 

For this particular issue, we are submitting a fix today to the app store, so the fix will be out in the coming days!

**Comment by steviepitman** [comment]
Please feed back to whomever is responsible for (a) the product and (b) the release schedule. Because this has gone on for so long now I've had to uninstall BW and won't be returning to it in the future - solely because of:

1. the fact that your testing allowed such a bug into the live product in the first place
2. the poor resolution speed in fixing it (it's obviously not seen as a priority)

**Comment by marcolaux** [comment]
It also doesn't happen in some esoteric use cases. I see the endless loops happening on normal sites as well, resulting in an extensive CPU usage and battery drain.

I switched to Arc because of this and I'm not able to use Safari productively anymore.

**Comment by marcolaux** [comment]
newest version fixed it for me. many thanks

**Comment by alexandernst** [comment]
This bug totally messed our web app. Maybe you should improve your QA process. This should have **never** happened.
